### ISSUE TITLE
Need a diagram for all the images

### ISSUE THREAD

**Issue by castrojo** [ublue-os/main#130]
It'd be nice to have a diagram of all the images, which show which desktop comes with it (and perhaps the name and icon of each featured desktop) so that when non-Fedora-knowledgeable people see "sericia" they know that's sway, etc. We'll then stick it on the website. 

Help wanted on this one!

**Comment by EinoHR** [comment]
How does this look @castrojo. I'll PR on the website soon, but I'll see if you got comments first.

![ublue-images](https://github.com/ublue-os/main/assets/60004820/5c0c60f9-eb7c-4d90-abca-b667b617a9b4)

**Comment by akdev1l** [comment]
I like the color scheme a lot!

Could you make the boxes the same size? It seems a bit unbalanced as it is, maybe it's just my brain wanting regularity :)

**Comment by castrojo** [comment]
Works for me, but yeah let's use the same size box! (Some stuff is busted in website right now but hopefully we can sort it soon so we can PR this in).

**Comment by EinoHR** [comment]
> Could you make the boxes the same size? It seems a bit unbalanced as it is, maybe it's just my brain wanting regularity :)

Sure. Didn't think about that, it was just Figma autolayout changing the box sizes...

**Comment by flexagoon** [comment]
This should be updated with the recent naming changes

https://fedoramagazine.org/introducing-fedora-atomic-desktops/

**Comment by castrojo** [comment]
https://universal-blue.org/architecture/
