### ISSUE TITLE
Virtualbox setup

### ISSUE THREAD

**Issue by boredsquirrel** [ublue-os/main#141]
### Describe the package

Virtualbox is required for some use cases, and on Fedora OSTree its an absolute pain to setup.

1. Add another repo
2. Install the packages including kernel mods
3. sign the packages for secureboot to work

This sounds like a perfect usecase for your images!

### Image

All Images

**Comment by akdev1l** [comment]
I do think that this fits the spirit of uBlue (though not sure I would include that on the main image)

However it seems the problem comes from upstream. 

> that VirtualBox currently just supports Fedora36.

If VirtualBox doesn't support current Fedora releases then it just seems we cannot support that.

**Comment by trytomakeyouprivate** [comment]
I dont think that there is no F37 version actually means something. There are sometimes problems with the Kernel not being supported, this has to be tested. But afaik this has something to do with akmods, so if you build it correctly it should work??? Not sure if I understand the process completely.

**Comment by akdev1l** [comment]
we're pulling the akmods from rpmfusion - it looks they also have virtualbox https://rpmfusion.org/Howto/VirtualBox

if this is up to date and it works we can do it

**Comment by bigpod98** [comment]
this is my 2 cents im not sure this should fall under purview of main image also yes if there is no support for the version of fedora(think 38 image should only use 38 packages) any of such additions should fall into user maintained downstream forks

**Comment by castrojo** [comment]
Yeah virtualbox is too opinionated to be in main, and virt-manager and gnome boxes are better supported in the fedora ecosystem. This would be a nice downstream image for people who need it though!
