### ISSUE TITLE
More Modular design for installing

### ISSUE THREAD

**Issue by trytomakeyouprivate** [ublue-os/main#143]
There are some mods that are more specific. 

NVIDIA is a y/n and there are always two images. But now imagine additional things coming like

- Virtualbox support + signing
- QEMU support ootb
- custom drivers for Wifi cards
- some Davinci resolve mods
- ...

These would be way better in a modular design.

1. Block that adds packages to the install build
2. Block that adds additional commands

Somehow this could then be a "click to get" distro, where you get
- This distro exists, download it here
- This distro doesnt exist, here are the configs you can use to create your own repo

What do you think of that?

### Image

All Images

**Comment by bigpod98** [comment]
Creating examples of blocks is one thing but beyond that im not sure anything more should be done, due to multiple factors each one of said blocks if implemented in some sort of ISO/image would require a maintainer to be sustainable and even as such those would not fall under purview of main but more downstream repository

**Comment by castrojo** [comment]
Yeah I think the way this could work is you go to "assembler.myawesomeproject.com" and then click on a bunch of premade pieces as described and then an image comes out the other end. 

This sort of exists with builder: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/composing_a_customized_rhel_system_image/index

It'd be nice to have an ostree version of that.

**Comment by EinoHR** [comment]
It wouldn't be too hard create a web ui that can be used to add packages and blocks such as the ones in ublue-os/config. What this would require, though, is everything ublue be split into separate components that can just be pulled in to other images.

This is also kind of the mission of startingpoint, with less bling and ux...

**Comment by castrojo** [comment]
akmods allows for people to snag whatever mods they want into their custom image, so closing this.
