### ISSUE TITLE
No update since 13th april

### ISSUE THREAD

**Issue by Froggy232** [ublue-os/main#152]
Hi,
First, thanks you a lot for your work!
This is not really a bug, more of a question, but I don't know where to ask it unfortunally.
On my computer, I haven't had any upgrade since the 13th april.
Is this normal, or is there a problem with my installation?
If this is normal, is there a policy for upgrade? Like, are they release once a week or something like that?
When I was running fedora silverblue, I had update nearly every day.
Thanks you a lot!

**Comment by p5** [comment]
What does your `rpm-ostree status` output?

**Comment by Froggy232** [comment]
Yeah, I was pretty sure I was having a problem.
Thanks for your answer, my rpm-ostree status output is here : 


● ostree-unverified-registry:ghcr.io/ublue-os/silverblue-main:38
                   Digest: sha256:ad0075647b726da16603020ecf0cfec9d24014882ba8b21517ed422ed322e364
                  Version: 38.20230413.0 (2023-04-13T21:28:11Z)
      RemovedBasePackages: firefox firefox-langpacks 111.0.1-1.fc38
                           gnome-terminal-nautilus 3.48.0-1.fc38
          LayeredPackages: corectrl fontconfig-enhanced-defaults
                           fontconfig-font-replacements gedit gnome-console hack-fonts
                           langpacks-fr solaar
            LocalPackages: 'appimagelauncher-2.2.0-travis995~0f91801.x86_64'
                           ql800pdrv-3.1.5-0.i386
                Initramfs: -I /etc/crypttab 

  ostree-unverified-registry:ghcr.io/ublue-os/silverblue-main:38
                   Digest: sha256:ad0075647b726da16603020ecf0cfec9d24014882ba8b21517ed422ed322e364
                  Version: 38.20230413.0 (2023-04-13T21:28:11Z)
      RemovedBasePackages: firefox firefox-langpacks 111.0.1-1.fc38
                           gnome-terminal-nautilus 3.48.0-1.fc38
          LayeredPackages: corectrl fontconfig-enhanced-defaults
                           fontconfig-font-replacements gedit gnome-console hack-fonts
                           langpacks-fr solaar
            LocalPackages: 'appimagelauncher-2.2.0-travis995~0f91801.x86_64'
                           ql800pdrv-3.1.5-0.i386
                Initramfs: -I /etc/crypttab 


Thanks you

**Comment by p5** [comment]
Nice spot!  Our builds for Fedora 38 have been failing for a couple of days!
https://github.com/ublue-os/main/actions/runs/4709658847

I'm taking a look now

**Comment by Froggy232** [comment]
Nice, so there is no problem on my installation :D
Thanks you again for your work, ublue is a wonderfull os!

**Comment by Froggy232** [comment]
Hi,
Have you any update on the situation?
Thanks you

**Comment by castrojo** [comment]
Just waiting on the rpmfusion issue to be resolved, we're trying multiple times per day, thanks for your patience!

**Comment by Froggy232** [comment]
Nice, thanks!

**Comment by ayhc** [comment]
Possibly related - there have been no new upstream Silverblue or Kinoite composes since April 14th: https://github.com/fedora-silverblue/issue-tracker/issues/454

**Comment by bsherman** [comment]
It looks like the failures mentioned there are specific to ppc64/aarch64, but we only build x86_64 architecture at this time.

Also, the ublue-os is not directly upstreaming to the rpm-ostree remotes, but rather to https://quay.io/organization/fedora-ostree-desktops which are still building on a nice cadence.

**Comment by castrojo** [comment]
Alright, what we did for now is turn off the rpmfusion stuff and kicked off some builds, that should put everyone on the GA version of Fedora 38. 

When the codec stuff is sorted we'll turn it back on. We won't announce the 38 builds as being ready until then, in the meantime you at least won't be behind on the other updates.

**Comment by Froggy232** [comment]
Hi,
The last update is actually from 21th april.
Is it normal?
Thanks you

**Comment by akdev1l** [comment]
Fedora hasn't pushed any updates since then

**Comment by Froggy232** [comment]
Ok, thanks
