### ISSUE TITLE
Provide a rawhide build

### ISSUE THREAD

**Issue by abbra** [ublue-os/main#154]
Hello!

It would be nice to have an automatic rawhide target that builds this container against Fedora Rawhide. This is especially useful during next Fedora release development...

**Comment by abbra** [comment]
I am running my laptop on Silverblue Rawhide: `fedora:fedora/rawhide/x86_64/silverblue`

**Comment by abbra** [comment]
Here is `rawhide` tag in https://quay.io/repository/fedora-ostree-desktops/silverblue?tab=tags

**Comment by castrojo** [comment]
We've had this turned on in the past, the issue is that due to the rpmfusion modifications and other dependencies that the build wouldn't work for weeks at a time.

**Comment by abbra** [comment]
@castrojo sure. I would treat Rawhide builds as a 'best effort' ones. If you'd make them available, it would be enough if they at least get built once. Right now the problem is that unless you fork this repo, you cannot even start doing a customization because there is no to base a fork on.

The other option I have is to fork this repo and do my own builds for the `ublue-os/main` myself which is an additional overhead for everyone who would like to get Rawhide working at least occasionally.

**Comment by EinoHR** [comment]
I guess it would be possible to enable Rawhide builds but mention that they are unsupported, if that doesn't take up too much build time..

**Comment by castrojo** [comment]
This isn't feasible any time soon.

**Comment by Justinzobel** [comment]
Are you able to elaborate on what makes them not possible?

**Comment by akdev1l** [comment]
The’ll just fail to build a lot as rawhide is literally broken most of the time

**Comment by Justinzobel** [comment]
> The’ll just fail to build a lot as rawhide is literally broken most of the time

However, when a build succeeds it will be provided to the users of the image. As discussed earlier in this thread it could be provided with the disclaimer that `This is Rawhide and will be regularly broken and may not receive updates regularly. Use at your own risk` etc
