### ISSUE TITLE
ISO fails to install (2)

### ISSUE THREAD

**Issue by dhassault** [ublue-os/main#161]
### What happened?

I got a similar issue as #108. I tried the iso 1.1.0 and 1.3.1

1. Using the `Fedora Media Writer`  I get the error (on nvidia variations only I think):
```
error: .../...tpm.c:150:unknown TPM error.
```
- I have the secure boot disabled
I could solve this thanks to: https://discussion.fedoraproject.org/t/tpm-error-on-booting/76724
Using ventoy also solved the issue.

2. But then going forward it gets stuck before the installer (screen appears with ventoy)
![bug_error_ublue](https://user-images.githubusercontent.com/7040582/232977553-211a5813-f656-44c3-b4f5-15ad24108da8.jpg)

In terms of hardware, this is on my laptop Asus zenbook ux410 with 2 SSD (`nvme0n1` and `sda`).

**Comment by akdev1l** [comment]
Ventoy not working is a known issue due to a anaconda.  


The TPM error is interesting - did you try efi or bios boot when that happened?

**Comment by dhassault** [comment]
Got it for ventoy :ok_hand: 

I just re-created a USB drive using Fedora Media Writer. I tried efi and legacy mode and it behaves the same on both modes.

**Comment by akdev1l** [comment]
Do you get this error with the upstream fedora iso?

**Comment by dhassault** [comment]
I could run the live version (using ventoy) and run the installer from there. Is it the answer you need? Do you want me to run specific tests?

**Comment by akdev1l** [comment]
Sorry I meant when not using Ventoy with the upstream fedora ISO - do you get a TPM error?

Is the TPM error happening while using ventoy?

**Comment by dhassault** [comment]
My issue is actually 2 different issues. The TPM one is also reported here #175 and the `dracut-pre-pivot.service` one is here #173 . 
- using ventoy does not trigger this TPM issue
- the issue appears only when selecting nvidia variants first, not if I chose the non-nvidia ones only 
- Fedora ISO runs correctly (no TPM issue)

**Comment by dhassault** [comment]
Just for information, I could install ublue by installing silverblue first and then rebase.

**Comment by dhassault** [comment]
I tested in virtualbox on popos on another computer, I get the exact same issue. However, silverblue 38 works fine.

**Comment by castrojo** [comment]
Hi there,

This issue was filed on old ISOs. We have a new ISO generation tool, check here for download instructions: 

https://universal-blue.org/installation/

The new ISOs use a more reliable method of creation and should work much better, thanks!
