### ISSUE TITLE
Kickstart File /run/install/ks.cfg is missing

### ISSUE THREAD

**Issue by JohnAtl** [ublue-os/main#162]
### What happened?

Trying to install universalblue-38-x86_64-20230418.iso using Ventoy. It runs for a bit, then complains that the kickstart file is missing. I verified in the shell that the file isn’t there. 
this occurs whether I select the main or Nvidia install. 

### Relevant log output

```shell
anaconda. 38.23.4-2.fc38 for Fedora 38 started.
* Installation log files are stored in tmp during the installation
* shell is avallable on TTY2 and in second TX pane (ctrl+b, then press 2)
* when reporting a bug add logs from /tmp as separate text/plain attachments
16:32:12 Kickstart File /run/install/ks.cfg is missing.

(Manually corrected ocr of pic of screen)
```

**Comment by JohnAtl** [comment]
Wrote the iso to a usb stick, and it hung on boot.
Verified the image, lots of text, then hung at a blinking cursor on a blank screen. No way to know at what point it died. Perhaps I can record the monitor as it boots.     
Asus ProArt-Z790 Creator WiFi
i9-19300k
128GiB RAM
Crucial P5 1TiB and 2TiB SSDs

**Comment by bsherman** [comment]
Ventoy is known to not work properly with the Silverblue (and uBlue) netinstaller ISO. 

Is your second comment also about using Ventoy or with the ISO written directly to the USB stick with Fedora Media Writer?

**Comment by JohnAtl** [comment]
I found mention of Ventoy not working, so wrote it directly to a USB stick. I used balena etcher.
It went through much of the boot, but then hung.

**Comment by castrojo** [comment]
Hi there,

This issue was filed on old ISOs. We have a new ISO generation tool, check here for download instructions: 

https://universal-blue.org/installation/

The new ISOs use a more reliable method of creation and should work much better, thanks!
