### ISSUE TITLE
Installation under virt-manager failed

### ISSUE THREAD

**Issue by SampsonF** [ublue-os/main#171]
### What happened?

Installation aborted:  main/Silverblue

Host:  Fedora Silverblue 38, local
VM Platform:  virt-manager

The following error occurred while installing the payload. This is a fatal error and installation will be aborted.

The command 'ostree container image deploy --sysroot=/mnt/sysimage --image=ghcr.io/ublue-os/silverblue-main:38 --no-signature-verification' exited with the code 1.

### Relevant log output

```shell
fpaste --sysinfo
https://paste.centos.org/view/7e3f4e37

fpaste anaconda.log
https://paste.centos.org/view/67a781b1
```

**Comment by castrojo** [comment]
I've seen this when there's no network or there's been a transient network error. Unfortunately it seems that anaconda doesn't attempt any retries so it tends to be finicky. Can you double check that there's a stable internet connection and that the machine can get on the network? 

https://ublue.it/installation/ has screenshots if it helps. Thanks!

**Comment by SampsonF** [comment]
Internet is OK and stable .

My fpaste is directly run inside the VM guest.

**Comment by simon-truhter** [comment]
>Relevant log output 
offline 

i had no issues installing it via virt-manager

**Comment by castrojo** [comment]
Hi there,

This issue was filed on old ISOs. We have a new ISO generation tool, check here for download instructions: 

https://universal-blue.org/installation/

The new ISOs use a more reliable method of creation and should work much better, thanks!
