### ISSUE TITLE
Rebase to silverblue-main:38 failed from silverblue 38

### ISSUE THREAD

**Issue by SampsonF** [ublue-os/main#172]
`
$ rpm-ostree status
State: idle
Deployments:
● fedora:fedora/38/x86_64/silverblue
                  Version: 38.20230420.0 (2023-04-20T03:26:13Z)
               BaseCommit: ac255bb74eb7ab97628e4bd4f0371af039d8495ed5fcef0ee9e9dccb01855436
             GPGSignature: Valid signature by 6A51BBABBA3D5467B6171221809A8D7CEB10B464
          LayeredPackages: bridge-utils dmg2img git google-chrome-stable ibus-cangjie-engine-cangjie libvirt python3-pip qemu qemu-img qemu-kvm virt-install virt-manager
            LocalPackages: teamviewer-15.40.8-0.x86_64

  fedora:fedora/38/x86_64/silverblue
                  Version: 38.20230414.n.0 (2023-04-14T08:04:21Z)
               BaseCommit: 7f13707d7180ddf167cf796fee7e1d3238fc20517a6cc3aa03108eb2d325a467
             GPGSignature: Valid signature by 6A51BBABBA3D5467B6171221809A8D7CEB10B464
          LayeredPackages: bridge-utils dmg2img git google-chrome-stable ibus-cangjie-engine-cangjie libvirt python3-pip qemu qemu-img qemu-kvm virt-install virt-manager
            LocalPackages: teamviewer-15.40.8-0.x86_64

$ sudo rpm-ostree rebase ostree-unverified-registry:ghcr.io/ublue-os/silverblue-main:38
[sudo] password for fcc: 
Pulling manifest: ostree-unverified-image:docker://ghcr.io/ublue-os/silverblue-main:38
Importing: ostree-unverified-image:docker://ghcr.io/ublue-os/silverblue-main:38 (digest: sha256:65173fcfa7a4f2462493a426946d9ed9b7233f794ced3578bab63573e3842218)
ostree chunk layers stored: 0 needed: 65 (2.0 GB)
custom layers stored: 0 needed: 1 (199.4 MB)
Fetching ostree chunk sha256:c27bcb3acdc2 (95.0 MB)
Fetched ostree chunk sha256:c27bcb3acdc2
Fetching ostree chunk sha256:b47379dad44b (74.6 MB)
Fetched ostree chunk sha256:b47379dad44b
Fetching ostree chunk sha256:79fe48f58da0 (128.3 MB)
Fetched ostree chunk sha256:79fe48f58da0
Fetching ostree chunk sha256:970fa4efe61a (40.5 MB)
Fetched ostree chunk sha256:970fa4efe61a
Fetching ostree chunk sha256:44a204b4ee66 (45.1 MB)
Fetched ostree chunk sha256:44a204b4ee66
Fetching ostree chunk sha256:d304ed061edb (17.0 MB)
Fetched ostree chunk sha256:d304ed061edb
Fetching ostree chunk sha256:0792c1565fe9 (32.7 MB)
Fetched ostree chunk sha256:0792c1565fe9
Fetching ostree chunk sha256:6aec5c916d96 (10.5 MB)
Fetched ostree chunk sha256:6aec5c916d96
Fetching ostree chunk sha256:8b5e91bcc30d (29.9 MB)
Fetched ostree chunk sha256:8b5e91bcc30d
Fetching ostree chunk sha256:fea891fc73f8 (80.1 MB)
Fetched ostree chunk sha256:fea891fc73f8
Fetching ostree chunk sha256:08892a48cd4e (40.7 MB)
Fetched ostree chunk sha256:08892a48cd4e
Fetching ostree chunk sha256:a452563718fc (65.0 MB)
error: Importing: Unencapsulating base: Failed to invoke skopeo proxy method GetBlob: remote error: Get "https://ghcr.io/v2/ublue-os/silverblue-main/blobs/sha256:a452563718fc223d76f5425c37fc095fa13075b89a0ece4da2f228d97157035f": dial tcp 20.205.243.164:443: i/o timeout
[fcc@fedora ~]$ sudo rpm-ostree rebase ostree-unverified-registry:ghcr.io/ublue-os/silverblue-main:38
Pulling manifest: ostree-unverified-image:docker://ghcr.io/ublue-os/silverblue-main:38
Importing: ostree-unverified-image:docker://ghcr.io/ublue-os/silverblue-main:38 (digest: sha256:65173fcfa7a4f2462493a426946d9ed9b7233f794ced3578bab63573e3842218)
ostree chunk layers stored: 11 needed: 54 (1.4 GB)
custom layers stored: 0 needed: 1 (199.4 MB)
Fetching ostree chunk sha256:a452563718fc (65.0 MB)
Fetched ostree chunk sha256:a452563718fc
Fetching ostree chunk sha256:237ed8387e4d (32.5 MB)
Fetched ostree chunk sha256:237ed8387e4d
Fetching ostree chunk sha256:910ef69391af (27.1 MB)
Fetched ostree chunk sha256:910ef69391af
Fetching ostree chunk sha256:bfc5b9051305 (26.5 MB)
Fetched ostree chunk sha256:bfc5b9051305
Fetching ostree chunk sha256:a97516cd5823 (50.5 MB)
Fetched ostree chunk sha256:a97516cd5823
Fetching ostree chunk sha256:6d32f5230066 (21.5 MB)
error: Importing: Unencapsulating base: Failed to invoke skopeo proxy method GetBlob: remote error: Get "https://ghcr.io/v2/ublue-os/silverblue-main/blobs/sha256:6d32f5230066c9738419113ad92e4c1016aee41737720667e46329a82512ff73": dial tcp 20.205.243.164:443: i/o timeout
`

**Comment by akdev1l** [comment]
does this happen if you retry? (there is no harm to this operation failing)

this looks like a network timeout: `dial tcp 20.205.243.164:443: i/o timeout`

**Comment by SampsonF** [comment]
"https://ghcr.io/v2/ublue-os/silverblue-main/blobs/sha256:a452563718fc223d76f5425c37fc095fa13075b89a0ece4da2f228d97157035f": dial tcp 20.205.243.164:443: i/o timeout

"https://ghcr.io/v2/ublue-os/silverblue-main/blobs/sha256:6d32f5230066c9738419113ad92e4c1016aee41737720667e46329a82512ff73": dial tcp 20.205.243.164:443: i/o timeout

The above result already retried once.

I also think if I keep retrying, the whole download will success - how ever, with this, and the ISO installation failed (which the ISO is downloading online, so the failing very likely network related) indicates the infrastruction is not ready.

**Comment by akdev1l** [comment]
we're working on getting some redundancy by hosting images on quay, we don't control ghcr.io so there's really not much we can do about it other than try to set up other registries for redundancy sadly

**Comment by castrojo** [comment]
Closing this as it appeared to be an intermittent issue
