### ISSUE TITLE
Installer hangs after Finished dracut-pre-pivot.service - dracut pre-pivot and cleanup hook.

### ISSUE THREAD

**Issue by JohnAtl** [ublue-os/main#173]
### What happened?

Using the latest iso 1.3.3 written to a usb stick with balena etcher. 
After waiting a few minutes, ctrl+alt+del and shutdown messages were printed and system rebooted. 

Subsequent install of generic Silverblue went well, but needed to use basic graphics. 

![4D7005BD-A480-49BD-B65A-6720A3F952C2](https://user-images.githubusercontent.com/5720074/233791519-d68dca8a-f938-4053-9bf9-529cf96aa90f.jpeg)

**Comment by castrojo** [comment]
Thanks so much for filing these John!

**Comment by JohnAtl** [comment]
Installed fedora writer on popos, wrote a usb with the 4/21 iso. Tried booting a few of the Nvidia installs, but they hung at dracut… as above, or blank screen. 
Booting non-Nvidia with basic graphics worked, and I was able to install.

**Comment by pyrignis** [comment]
I have exactly the same issue as post one but the basic graphics boot mode does not solves it. Version 1.3.3 of the iso, non-nvidia silverblue.

**Comment by TempleOfTemplar** [comment]
+1( 
![Uploading 16858056334618749890518722181995.jpg…]()

**Comment by nullfrctl** [comment]
Experiencing this trying to install uBlue Silverblue NVIDIA

**Comment by ribenafan** [comment]
I think this might be related to https://bugzilla.redhat.com/show_bug.cgi?id=2193332

**Comment by AuraHerreroRuiz** [comment]
I have the same problem, tried the nvidia and non-nvidia options (planning to later rebase) as well as using the "with basic graphics" option.

In all those cases, I get almost same output as the original poster, with the only difference being `cancel waiting for multipath sibling devices of` ending with different devices.

**Comment by castrojo** [comment]
Hi there,

This issue was filed on old ISOs. We have a new ISO generation tool, check here for download instructions: 

https://universal-blue.org/installation/

The new ISOs use a more reliable method of creation and should work much better, thanks!
