### ISSUE TITLE
unknown TPM error when trying to boot from ISO.

### ISSUE THREAD

**Issue by pan1997** [ublue-os/main#175]
### What happened?

unknown TPM error when trying to boot from ISO. Don’t see this error in other ISOs, for example both latest arch iso and vanilla silverblue 37 iso boot correctly.]

### Relevant log output

```shell
error: ../../grub-core/commands/efi/tpm.c:150:unknown TPM error.
error: ../../grub-core/commands/efi/tpm.c:150:unknown TPM error.
error: ../../grub-core/commands/efi/tpm.c:150:unknown TPM error.

Press any key to continue…
```

**Comment by meisme-dev** [comment]
I have this issue too, doesn't happen on installed system and goes away when I disable the TPM

**Comment by Vashinator** [comment]
I am also getting this error this evening when selecting the nvida version. I used etcher to burn, will try Fedora media writer and try again first thing tomorrow morning.

**Comment by Pheoxy** [comment]
I tried this today using the fedora media writer and got the same TPM error.

I was also selecting NVIDIA but tested the base with the same effect.

**Comment by Vashinator** [comment]
I saw a post on reddit about Fedora 38. Their steps were:
1. Disable secure boot and TPM
2. Clear any secure boot or TPM keys
3. Install ISO
4. Turn secure boot and TPM back on.

I have confirmed my error is cleared after turning off TPM (secure boot was off for a different install).
My plan is to run the install and turn these back on. Will update once I have.

**Comment by osalbahr** [comment]
The exact same error message happened to me today with the pre-release iso on an Acer Predator laptop (I haven’t tried the latest iso yet). Following a suggestion in the ublue discord server, disabling TPM in the boot -> security menu seems to fix the issue. I’ll try with different fedora ISO’s too

![image](https://github.com/ublue-os/main/assets/54853250/d29967c4-4289-43b1-b1be-945eefdeee1e)


![](https://media.discordapp.net/attachments/1074422586894712912/1113851663833374720/IMG_1978.jpg)

**Comment by osalbahr** [comment]
Update: I was able to install on an external ssd by disabling tpm, but now the external ssd is not recognized as a bootable medium by my laptop even though I can boot into it on my MacBook Pro (Intel). I tried to also disable secure boot but that didn't work out:

![IMG_2401](https://github.com/ublue-os/main/assets/54853250/8eb6b0f0-13f0-4fef-8037-c5c28908a543)

 I am able to see the content of the desk from my Fedora Workstation, with the username I picked, after being prompted with the password:

![Screenshot from 2023-06-04 18-43-26](https://github.com/ublue-os/main/assets/54853250/a3aa5328-f73b-41d0-8748-90b09fa3074e)
![Screenshot from 2023-06-04 18-45-11](https://github.com/ublue-os/main/assets/54853250/5825e02e-04f2-41b3-9404-ebf9c1ad8b64)

lsblk:

![image](https://github.com/ublue-os/main/assets/54853250/e9220fd1-7536-42dc-b4e0-411b1a2eaa9c)

Note: Not sure if enabling disk encryption is related, as the Fedora Workstation I am using now is with disk encryption enabled

System info:
![image](https://github.com/ublue-os/main/assets/54853250/863ed16d-040e-446c-a39e-2b67c2d12e74)
