### ISSUE TITLE
Package Request: xfce4-clipman-plugin

### ISSUE THREAD

**Issue by un1c3** [ublue-os/main#181]
### Describe the package

I'd like to request the package `xfce4-clipman-plugin`. It is the clipboard manager for xfce and is an incredible quality of life tool.

### Image

Vauxite

**Comment by castrojo** [comment]
This seems fine to me, but I don't use vauxite day-to-day, some more feedback from XFCE users would probably be useful (it's nice to document why we're adding each package for future reference)

**Comment by castrojo** [comment]
Alright it should be in the next build in a few minutes, if you have any more recommendations send them along, thanks!
