### ISSUE TITLE
Typo after selecting kinoite main, "Install silverblue" in basic graphics mode

### ISSUE THREAD

**Issue by MichaelGame-Dev** [ublue-os/main#183]
### What happened?

After picking kinoite-main, I get the option to install kinoite-main:38 or install **silverblue**:38 in basic graphics mode.

I am running a 4k screen so ended up using basic graphics mode for this. It appears this is just a typo as I did end up with kinoite instead of silverblue.

Not sure about the other options.

### Relevant log output

```shell
This is before the installer.
```

**Comment by castrojo** [comment]
Hi there,

This issue was filed on old ISOs. We have a new ISO generation tool, check here for download instructions: 

https://universal-blue.org/installation/

The new ISOs use a more reliable method of creation and should work much better, thanks!
