### ISSUE TITLE
proper way to install waydroid

### ISSUE THREAD

**Issue by Je55eah** [ublue-os/main#186]
I installed uBlue main on virtualbox. My first goal was to run waydroid, but it was not listed in the software application. The Waydroid project recommends using dnf, but dnf is not present. yum is also absent. How am I meant to install a program such as Waydroid? I am new to Fedora and also new to uBlue.

**Comment by castrojo** [comment]
`rpm-ostree install waydroid` and then a reboot _should_ work but not sure if anyone's tested that so far.

**Comment by castrojo** [comment]
Oh neat, it worked, I was able to get it up and running!

**Comment by bsherman** [comment]
> Oh neat, it worked, I was able to get it up and running!

waydroid coming soon to a bluefin near you? :joy:

**Comment by Je55eah** [comment]
Thank you. 

Did you load the lineage os system in your tests?

I followed this guide:
https://www.linuxfordevices.com/tutorials/waydroid-on-linux

The program started and presented a short form.
After entering the links and successfully downloading the system I found that waydroid did not start again.

**Comment by Je55eah** [comment]
I ran it from the terminal and got the impression that wayland needed to be running. To this end I used rpm-ostree to install wayfire and then I selcted wayfire from the dm and logged in. After some configuration and two reboots wayfire kind of worked, but it doesn't open any applications. The waydroid apps did appear in the menu with the linux apps, but neither of them work on wayfire and only the linux applications work on gnome. 

If it did work I got the impression that wayfire would be a better desktop experience and I noticed that it used less ram and less cpu than gnome so that the resources used are closer to other dektops such as kde, xfce, budgie, and lxqt. Gnome on uBlue is the most resource hungry system I have tested, it even uses more than Windows 7. I wonder what it is doing and why anyone would want to use gnome. 

Rather than trying to make uBlue do something it isn't built for I'm looking for a different distro that has wayfire or another wayland desktop preconfigured. Thanks for telling me about rpm-ostree. This issue can be closed if no one else is interested in running waydriod.

**Comment by Je55eah** [comment]
btw:
According to this report gnome should not be heavier than kde. 

https://vermaden.wordpress.com/2022/07/12/desktop-environments-resource-usage-comparison/

Something might be misconfigured.

**Comment by bigpod98** [comment]
Well ublue has many different images including kde plasma 5 which just like gnome is by default wayland. (Yes gnome is wayland by default)

Regarding resource usage, resource usage is fairly high on all distribution is relatovly high and it isnt any higher on ublue then on fedora.

Which gnome based image were you saying with this high resource usage

**Comment by sekalengrengginang** [comment]
for waydroid it only works properly on Intel/AMD system
 Nvidia GPU users need to turn on software rendering

**Comment by Je55eah** [comment]
This computer has an integrated intel hd graphics 4000 gpu. Recently I have noted the following stats:
mx linux host system with only the desktop loaded:
10% memory used, 1% cpu used

host + virtualbox + guest with only the desktop loaded:
q4os + trinity:
26% memory used, 2% cpu used
solus + budgie:
32% memory used, 2% cpu used
Gecko (openSuse) + kde plasma:
31% memory used, 2% cpu used
mAid(Manjaro Arch) + (xfce/budgie/gnome hybrid?):
31% memory used, 2% cpu used
pclinuxos + lxqt:
26% memory used, 10% cpu used
windows 7:
89% memory used, 14% cpu used
uBlue-main(fedora sb) + gnome:
65% memory used, 50% cpu used
uBlue-main(fedora sb) + gnome (best case):
55% memory used, 24% cpu used
uBlue-main(fedora sb) + wayfire(semi-functional):
33% memory used, 2% cpu used

All of those scores are read from the mx host system so they naturally include the overhead of mx and virtualbox.

**Comment by Je55eah** [comment]
I did read that wayland was already included which is why I thought uBlue Fedora Gnome would be a good candidate as a waydroid host. Nonetheless, after installing waydroid, the program asked if waydroid was running. Installing wayfire was a heavy handed atteempt to solve the problem and there is probably a better way to enable it. Did any of the android applications run on your system when you tested it?

**Comment by bigpod98** [comment]
Well i cant really tell how much ram or cpu you have because procents are relative. 
On my systen using bluefin image is using about 7% which is 1.3GB, this image uses slightly modified gnome with extensions so its slightly heavier then one shipped in main image. Plus there are sone other daemons i wanted running active as well. This goes fairly in line in my experiance with a similarly loaded systems in past including ubuntu which in past used quite a bit more efficient gnome in my experiance

**Comment by bigpod98** [comment]
Gnome these days and for last few versions is treating wayland as a dependency which means it gets installed in most cases and gnomes default is to use wayland inatead of xorg but you can switch to xorg with that cog in lower right. Afaik we do not change that default

**Comment by Je55eah** [comment]
I can confirm that uBlue Gnome is also using 1.3gb on this system. Nonetheless, it seems to be using twice as much ram as the other linux systems and 10x more cpu. The host system reports 4.9gb used in total while the virtual machine is running and when virtualbox is closed that falls to 750mb. That means 2.85gb of anomalous ram use remains unaccounted for. Is gnome doing the windows thing where ram is predictively pre-allocated? The top processes listed were all gnome related, I don't imagine the elevated cpu utilization is as much of an issue for people running newer systems, but it does diverge greatly from the other linux peers. 

I'm not trying to complain about any of this, but it seemed to be worth reporting. 

Did any of the android apps run on your test system?

**Comment by bigpod98** [comment]
Cpu is running in normal amounts, host is never good way to look at guest os consuption as this includes any overhead from vm itself vm hypervisor, which virtualbox is fairly hungry afaik

**Comment by Je55eah** [comment]
Okay, the missing piece of the puzzle was to disable waydroid gpu acceleration as described here:
https://docs.waydro.id/faq/get-waydroid-to-work-through-a-vm
That impacted me because I am running uBlue on virtualbox.

I also got it to work on debian+gnome and feora silverblue+gnome, both of them were booted on virtualbox on the same system.

host + virtualbox + guest with only the desktop loaded:
debian + gnome:
43% memory used, 8% cpu used
fedora silverblue + gnome:
55% memory used, 2% cpu used

The memory utilization is not a great concern because these guest operating systems simply utilize more cache. The cpu utilization of uBlue is still way out of line compared to these other systems. The overhead from the virtual machine software and the host system is the same on all of the systems I have compared. uBlue is probably doing something that these other systems are not doing and it is taxing the cpu.3x-50x more than the other linux systems.

**Comment by bigpod98** [comment]
again 8% of what 2% of what, but based uppon the system im running right now without much running besides browser htop. and couple of deamons cpu rarely cracks 5% on one of cores

**Comment by bigpod98** [comment]
ok just did my own sanity check and loaded up ublue silverblue into kvm vm after letting it stabilize without running when on desktop on host i cirremtčy get stable performance between 0% and 5% with VM running. Memory consumption is in line with what i gave to VM on host side.

on VM side usage is between 0% and 2% consistently with 25% of ram used. which is in line with my expectations 25% being 1GB of ram

**Comment by Je55eah** [comment]
I already told you that the host system is a mid 2012 macbook pro. I'm not sure why this information is being received with disbelief when I have provided a long list of systems that were tested in the same manner. I also waited for the systems to fully load and settle down before taking note of the load.

`
$ lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   36 bits physical, 48 bits virtual
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              2
Core(s) per socket:              2
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           58
Model name:                      Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
Stepping:                        9
CPU MHz:                         2015.638
CPU max MHz:                     3600.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        5787.10
Virtualization:                  VT-x
L1d cache:                       64 KiB
L1i cache:                       64 KiB
L2 cache:                        512 KiB
L3 cache:                        4 MiB
NUMA node0 CPU(s):               0-3
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulne
                                 rable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Unknown: No mitigations
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitizatio
                                 n
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditiona
                                 l, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Vulnerable: No microcode
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat p
                                 se36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdt
                                 scp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology n
                                 onstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx
                                  smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt 
                                 tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault pt
                                 i ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsba
                                 se smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d

`

**Comment by bigpod98** [comment]
Why i find your info unbelivable because i cant confirm your findings simple as that.

Thanks for confirming your machine configuration while i dont have any dual core systems i did a test on my quad core laptop and did find numbers that were in line with my findings on my desktop.

But it would also help to know what config you used in VM.

on my desktop i configured mine with 4 corey 4gb of ram while on laptop it was 2 cores and 4gb of ram. Usage changed by predicted margin

**Comment by Je55eah** [comment]
I assigned both cores but I limited the guest to 90%. 

RAM is not a concern as the higher utilization is due to caching. Since you asked, the computer has 8GB and the guests have 4608MB allocated.

On newer computers this isn't likely to even matter, so I wouldn't stress over it greatly.
