### ISSUE TITLE
Flatpak Wine with AMG GPU not working

### ISSUE THREAD

**Issue by trytomakeyouprivate** [ublue-os/main#188]
I have a new laptop AMD Vega graphics card. Seeing from its performance it doesnt work in Wine. I read somewhere this was because of an old driver, but 

Used software: Lutris Flatpak, with Lutris Proton GE.

```
amd-gpu-firmware-20230404-149.fc38.noarch
xorg-x11-drv-amdgpu-23.0.0-1.fc38.x86_64
```

are both installed.

Just keep in mind, it seems "AMD = Intel = no problem" is not true. 

### Image

Kinoite

**Comment by joshua-stone** [comment]
Can you provide more informaton on what's not working, like system logs when running Wine? Have you checked to see if this is impacts upstream Fedora as well?

**Comment by trytomakeyouprivate** [comment]
```
flatpak run net.lutris.Lutris 
2023-04-30 15:39:10,090: Starting Lutris 0.5.12
2023-04-30 15:39:10,225: Running AMD Mesa driver 23.0.2 on AMD Radeon Vega 8 Graphics (raven, LLVM 15.0.7, DRM 3.49, 6.2.13-300.fc38.x86_64) (0x15d8)
2023-04-30 15:39:10,225: GPU: 1002:15D8 17AA:5125 (amdgpu drivers)
2023-04-30 15:39:10,611: Startup complete
2023-04-30 15:39:16,867: Unable to load libGLX_nvidia.so.0
2023-04-30 15:39:16,868: Unable to locate libGLX_nvidia
Discord ID: None
2023-04-30 15:39:17,041: Discord RPC Disabled or Discord APP ID Not Present
Started initial process 55 from gamemoderun /home/user/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-GE-Proton7-43-x86_64/bin/wine /home/user/Games/the-kraken-wakes/drive_c/Games/The Kraken Wakes/Kraken.exe
Start monitoring process.
gamemodeauto: 
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
SUCCESS!
SUCCESS!
Setting breakpad minidump AppID = 2100380
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561194789371904 [API loaded no]
Unable to read VR Path Registry from C:\users\user\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\users\user\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\users\user\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\users\user\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\users\user\AppData\Local\openvr\openvrpaths.vrpath
```

I have had the same extreme Graphics lag on standard Kinoite.

It seems it wants an NVIDIA GPU but doesnt find it?

This could be a similar thing like making Davinci Resolve working on AMD GPUs, so that an App wanting NVIDIA thinks it gets it, but its actually AMD.

[Here is a workaround for that](https://linuxgamecast.com/2023/02/davinci-resolve-on-linux-amd-gpu-drivers), basically:

- disable Wayland (maybe not needed?)
- `amdgpu-install --vulkan=pro --opencl=rocr,legacy`
- add user to group
- use OpenCL 
- have the amdgpu-pro drivers

On kinoite-main, there are installed:

```
ocl-icd-2.3.1-3.fc38.x86_64

amd-gpu-firmware-20230404-149.fc38.noarch
xorg-x11-drv-amdgpu-23.0.0-1.fc38.x86_64

mesa-vulkan-drivers-23.0.3-1.fc38.x86_64
vulkan-loader-1.3.243.0-1.fc38.x86_64
vulkan-tools-1.3.243.0-1.fc38.x86_64

mesa-filesystem-23.0.3-1.fc38.x86_64
mesa-libglapi-23.0.3-1.fc38.x86_64
mesa-libxatracker-23.0.3-1.fc38.x86_64
mesa-dri-drivers-23.0.3-1.fc38.x86_64
mesa-libgbm-23.0.3-1.fc38.x86_64
mesa-libEGL-23.0.3-1.fc38.x86_64
mesa-libGL-23.0.3-1.fc38.x86_64
mesa-vulkan-drivers-23.0.3-1.fc38.x86_64
mesa-va-drivers-freeworld-23.0.2-1.fc38.x86_64
```

**Comment by throwaway43** [comment]
@trytomakeyouprivate Not sure what you're trying to achieve, but wouldn't you rather prefer to use Wine only within Bottles or a dedicated Wine distrobox?

**Comment by firefoxlover** [comment]
@throwaway43 I am using Lutris flatpak.

Just it seems to have an issue utilizing my GPU. it should work normally on foss AMDGPU drivers though, which is weird.

**Comment by trytomakeyouprivate** [comment]
I am using Lutris Flatpak. Should have all wine stuff installed, but the drivers for FOSS amdgpu seem to not be used.

**Comment by throwaway43** [comment]
@trytomakeyouprivate Ah, okay. Thanks for clarifying! Did you try it in Bottles? Because, for all we know, the culprit might simply be Lutris. For whatever it's worth, Bottles has always worked better for me anyways.
