### ISSUE TITLE
Turn on lazurite builds

### ISSUE THREAD

**Issue by castrojo** [ublue-os/main#195]
lxqt is now lazurite upstream, we should turn this on for F39:

https://gitlab.com/fedora/ostree/ci-test/

**Comment by castrojo** [comment]
This looks like it was deferred to F40 at least, builds upstream are currently rawhide only.

**Comment by qoijjj** [comment]
Just tested lazurite from fedora-ostree-desktops, works well.  

ublue lxqt is currently borked in many ways. menu is completely missing, icons missing, non-functional apps. switching to lazurite will fix this.

**Comment by castrojo** [comment]
@qoijjj wants to work on this. 

Then we'll turn off the lxqt repos/packages at the end of F38 like we're going to do for budgie.

**Comment by qoijjj** [comment]
https://github.com/ublue-os/nvidia/pull/182
