### ISSUE TITLE
Problem with Pika Backup

### ISSUE THREAD

**Issue by Froggy232** [ublue-os/main#198]
Hi,
I try to use pika backup (from flathub) with the latest universal blue gnome.
When I try to mount an archive, I have an error message :  fuse : device not found, try 'modprobe fuse' first. 
If I type modprobe fuse in a terminal, I still have the error.
I have write a bug report on the Pika bug tracker, but the dev told me that the issue probably arise from the distribution.
So, I open a bug here, and will also try to do it on the silverblue bugtracker.
So far, I have also try to disable temporary selinux, and it didn't help.
Bug is very easily reproducible, you just need to mount an archive with Pika.
Thanks you!

**Comment by castrojo** [comment]
Sounds like we might need to add a fuse thing to the image. I've been meaning to try pika anyway so I'll take a look, but if someone knows the packages we need off hand please leave a comment.

**Comment by Froggy232** [comment]
Hi,
Thanks for your answer!
I will wait for a fix so.
Thanks again

**Comment by Froggy232** [comment]
Hi,
I can confirm that everything work on fedora silverblue 38, so it's probably some package that have been removed.
Thanks you

**Comment by EinoHR** [comment]
uBlue doesn't remove a lot of packages (see [packages.json](https://github.com/ublue-os/main/blob/a95ec2d42e059eb3595f31b5c1bc8251e1cb0662/packages.json#LL172C6-L172C6)). I think this is probably a difference between the official Fedora images and the testing ones we build ours on.

**Comment by Froggy232** [comment]
Nice, thanks for your answer.
Just by curiosity, does someone know why we are based on the testing image and not the regular one?

**Comment by castrojo** [comment]
Fedora won't have regular images until F39 which is why we're using their test images, see #78 for more info!

**Comment by Froggy232** [comment]
Nice, thanks you a lot, it makes a lot of sense.
I suppose mounting archive through pika will not work until we switch to the official image, so fedora 39?
Thanks you

**Comment by Froggy232** [comment]
Hi,
I just see that pika also doesn't connect to remote server, like borgbase one.
It throw me an error message : "Remote : ssh : could not resolve hostname XXX temporary failure in name resolution"
So far, I have tried to : 
- Disable the firewall
- Disable selinux
- Change DNS
- Try another connection
On a vm with fedora workstation 38, I don't have this error message (even though I have another one about Permission Denied, but probably related with my config).
I think this is also a problem related to universal blue, I will test with a fedora silverblue VM.
Thanks

**Comment by castrojo** [comment]
I am able to connect to things and make backups, but I am unable to confirm getting that fuse error, what steps are doing to get that error? thanks!

**Comment by Froggy232** [comment]
I had some errors in my flatseal configuration, everythings work well now.
Problem wasn't related to universal blue, sorry for the ticket.
Thanks you a lot
