### ISSUE TITLE
Kernel-tools incorporated into all ISOs

### ISSUE THREAD

**Issue by fiftydinar** [ublue-os/main#205]
### Describe the package

Useful if you want to debug or check which CPU governor is used, which CPU scaling driver is used, what are the current CPU frequencies etc.

My usecase:
Especially useful for AMD Zen 3 users such as me. Gnome-power-profiles use useless placeholder driver. So I use amd-pstate-active CPU scaling driver, powersave governor with power preference instead for better CPU efficiency.

CPU scaling driver used can be set on boot through kernel arguments.
However, to set governor & governor preference to work on boot through systemd startup script, I need to have kernel-tools installed, which has that info provided.

### Information on the package

Name         : kernel-tools
Version      : 6.2.6
Release      : 300.fc38
Architecture : x86_64
Size         : 269 k
Source       : kernel-tools-6.2.6-300.fc38.src.rpm
Repository   : fedora
Summary      : Assortment of tools for the Linux kernel
URL          : http://www.kernel.org/
License      : GPLv2
Description  : This package contains the tools/ directory from the kernel source
             : and the supporting documentation.

### Image

All Images

**Comment by castrojo** [comment]
This looks like a nobrainer to me, +1!

**Comment by Arcitec** [comment]
Agreed. It's small. It's official Kernel tools. It helps solve issues. It's small (did I say that?). It doesn't install any desktop shortcuts, so only people who need it will see it.
