### ISSUE TITLE
Better IDE integration (VSCode, etc...)

### ISSUE THREAD

**Issue by Arcitec** [ublue-os/main#207]
## :warning: Moved to Discussion: :point_right: https://github.com/orgs/ublue-os/discussions/155 :point_left: 

So let's only use this ticket for final solutions/tracking when it's done. Discussion should be done in the thread above.

**If you have any ideas, please only comment at the discussion link above.**

**Comment by bigpod98** [comment]
In my experiance flatpak of vscode is very badly maintained

**Comment by Arcitec** [comment]
> In my experiance flatpak of vscode is very badly maintained

In what way? It's very actively maintained, 308 commits and automatic updates of upstream and libraries:

https://github.com/flathub/com.visualstudio.code

Everyone's aware of the difficulty of running host's dev tools though, which is what `remote-containers` solves:

https://code.visualstudio.com/docs/devcontainers/containers

**Comment by bigpod98** [comment]
Its been a while since i last checked it but in past i couldnt really rely on it

**Comment by bigpod98** [comment]
And i understand why we want remote to work i havent run a single dev tooling in my systems main namespace for years noe

**Comment by Arcitec** [comment]
As a high level summary, the way I understand it is that the container workflows are like this:

- VSCode runs as a Flatpak "on the host".
- You use some extension to connect to remote containers.
- Those containers can be on other servers, or can be local Podman containers, so it's super flexible.
- You install your dev tools and some vscode server component (maybe) inside the container.
- You then tell the Flatpak VSCode's "remote containers" extension to connect to that particular container. This should give you a shell, access to all build tools, etc.

This is the overview of how I understand the process to be nowadays.

**Comment by Arcitec** [comment]
@bigpod98 Yes but we can't do that in the main images. Only developers want vscode. We need to figure out the container workflow.

**Comment by bigpod98** [comment]
We could just have recommended workflow and install nothing

**Comment by castrojo** [comment]
This might be better as a spec in the forums where we can freeform better so we can keeo this issue clean

**Comment by JohnAtl** [comment]
I used vscode to work in a container on my system.
After I got all the kinks worked out, the thing remaining was that if I ran code from outside the container (like hitting Super, typing code), it ran as root in the container. While this worked, it made files it touched (including from git commits) owned by root.
If I entered the container first, then typed 'code' at a terminal prompt, it ran fine as my regular user. 
Setup was fairly easy, I can try to find the procedure I used if that would be helpful.

**Comment by Arcitec** [comment]
@JohnAtl It sounds like you used another workflow, where you installed VSCode itself inside a container, exported it to the host (ie "distrobox export"), and then ran the shortcut?

The technique we'll be evaluating here is different. The high level summary is here:

https://github.com/ublue-os/main/issues/207#issuecomment-1548342560

I don't think it would have those permission issues, since it's a separated workflow.

@castrojo I agree, will create a discussion with the current info.

**Comment by A-Lovett** [comment]
> @JohnAtl It sounds like you used another workflow, where you installed VSCode itself inside a container, exported it to the host (ie "distrobox export"), and then ran the shortcut?
> 
> The technique we'll be evaluating here is different. The high level summary is here:
> 
> [#207 (comment)](https://github.com/ublue-os/main/issues/207#issuecomment-1548342560)
> 
> I don't think it would have those permission issues, since it's a separated workflow.
> 
> @castrojo I agree, will create a discussion with the current info.

One alternative I've done is:
1) Install vs code inside the container, but don't export it.
2) Launch vs code with the following command:
distrobox enter container-name -- code

This launches vs code inside the container and doesn't cause any permission issues, as far as I know. You just need to set up something to run that command for a given container. For example, in my setup I dynamically associate different workspaces with different distrobox containers, so when I enter the keyboard shortcut to launch vs code, it launches vs code inside my current workspace's associated container.

That said, installing vs code inside each distrobox container where one might want to use it is a bit onerous, plus it means you need to configure it each time. I've considered setting up a script that runs on top of "distrobox create" and does that work for you, but if there's a way to set up a cli command that launches vs code and enters a container via vs code's container extension, I might be interested.

**Comment by FruityWelsh** [comment]
I was using a fork of https://flathub.org/apps/com.visualstudio.code.tool.podman for vscodium ([my-fork](https://github.com/FruityWelsh/com.vscodium.codium.tool.podman)) to have podman reach back out to my system to access other containers. Would something like that be useful for what you all are thinking too?

A little more reading could be found her: https://developers.redhat.com/articles/2023/02/14/remote-container-development-vs-code-and-podman#run_container_images_on_your_remote_host

My personal reasoning was, I wanted every app that could be a flatpak to be a flatpak and I wanted to keep my dev containers as light as possible, just playing around with what I was working on and not stuff needed to host VSCode/VSCodium. 

Long run I would love to have a flatpak portal to ask what containers to give access too rather than just my whole system/user set of containers and lock it down some...

**Comment by castrojo** [comment]
This is best handled by downstream images.
