### ISSUE TITLE
Add xdg-terminal-exec

### ISSUE THREAD

**Issue by castrojo** [ublue-os/main#210]
### Describe the package

xdg-terminal-exec which will be useful for seapping out terminals, here's how distros are doing it: 

- https://github.com/Vladimir-csp/xdg-terminal-exec
- https://packages.ubuntu.com/source/lunar/xdg-terminal-exec
- https://packages.debian.org/sid/source/xdg-terminal-exec

and we'd need to find Fedora's plans/spec for this

### Information on the package

No packaging info

### Image

All Images

**Comment by bigpod98** [comment]
from my limited testing in silverblue unless you have gnome terminal or xterm(not shipped with fedora silverblue or ublue silverblue) or another terminal preprepared for this, opening an app from desktop that is run in terminal doesnt open anything, including no error message.
