### ISSUE TITLE
SDDM issues on custom images

### ISSUE THREAD

**Issue by gerblesh** [ublue-os/main#224]
when trying to install/use SDDM in a custom image you get a black screen and are unable to switch VTs.
To fix this you need to add the `sddm` user
```
adduser sddm
```
Curiously, while building the image, the `sddm` user is added but that change isn't reflected when booting/rebasing the image.
```

Downloading from 'fedora'...done
Installing 8 packages:
  desktop-backgrounds-compat-38.0.0-2.fc38.noarch (fedora)
  f38-backgrounds-base-38.1.1-1.fc38.noarch (fedora)
  freerdp-libs-2:2.10.0-1.fc38.x86_64 (fedora)
  libwinpr-2:2.10.0-1.fc38.x86_64 (fedora)
  sddm-0.19.0^git20230404.e652433-1.fc38.x86_64 (fedora)
  sddm-wayland-generic-0.19.0^git20230404.e652433-1.fc38.noarch (fedora)
  weston-11.0.1-2.fc38.x86_64 (fedora)
  weston-libs-11.0.1-2.fc38.x86_64 (fedora)
Installing: libwinpr-2:2.10.0-1.fc38.x86_64 (fedora)
Installing: freerdp-libs-2:2.10.0-1.fc38.x86_64 (fedora)
Installing: weston-libs-11.0.1-2.fc38.x86_64 (fedora)
Installing: weston-11.0.1-2.fc38.x86_64 (fedora)
Installing: f38-backgrounds-base-38.1.1-1.fc38.noarch (fedora)
Installing: desktop-backgrounds-compat-38.0.0-2.fc38.noarch (fedora)
Installing: sddm-wayland-generic-0.19.0^git20230404.e652433-1.fc38.noarch (fedora)
Installing: sddm-0.19.0^git20230404.e652433-1.fc38.x86_64 (fedora)
Created symlink /etc/systemd/system/display-manager.service → /usr/lib/systemd/system/sddm.service.
Creating group 'adbusers' with GID 973.
Creating group 'sddm' with GID 972.
Creating user 'sddm' (SDDM Greeter Account) with UID 972 and GID 972.
```

**Comment by castrojo** [comment]
This seems to be custom image related and not an issue with the images here? Can we close this?

**Comment by gerblesh** [comment]
Hi, yeah it's been a while. Basically because `/etc/passwd` has been overwritten by the client, changes to it on the image (adding the sddm user) aren't reflected when rebasing. So if you install an image from an ISO, or rebase from a system that already includes the user in `/etc/passwd`, you're able to boot just fine. Might be safe to close this as an "issue" and maybe put it as a note for people rebasing on the uBlue and BlueBuild websites. https://www.freedesktop.org/software/systemd/man/latest/systemd-sysusers.html would be a good solution for this problem.

**Comment by sneexy-boi** [comment]
Commenting here, I've tried rebasing from an image that already included a modified `/etc/passwd` and can confirm that it *doesn't* work. For example, Kinoite to a custom `base` image still gives a blank screen. I've also tried `systemd-sysusers` but it fails as none of its "conditions" are met, so it just refuses to make the users. The workaround I've done is to just make a manual system systemd service which is added and enabled during image creation via the `systemd` module, which creates the required/missing user then just disables itself after boot. For example, for SDDM:
```
[Unit]
Description=Create SDDM user on system boot

[Service]
Type=oneshot
ExecStart=/usr/sbin/groupadd -r sddm
ExecStart=/usr/sbin/useradd -r -g sddm -c "SDDM Greeter Account" -d /var/lib/sddm -s /usr/sbin/nologin sddm
ExecStart=/usr/bin/systemctl disable create-sddm-user.service

[Install]
WantedBy=multi-user.target
```
And for GDM (Haven't tried, but it should work):
```
[Unit]
Description=Create GDM user on system boot

[Service]
Type=oneshot
ExecStart=/usr/sbin/groupadd -g 42 gdm
ExecStart=/usr/sbin/useradd -u 42 -g gdm -c "GNOME Display Manager" -d /var/lib/gdm -s /usr/sbin/nologin gdm
ExecStart=/usr/bin/systemctl disable create-gdm-user.service

[Install]
WantedBy=multi-user.target
```

**Comment by sneexy-boi** [comment]
Alternatively, it may be better to just make a script that adds the required line/user directly into `/etc/passwd` during image creation. No idea how I missed that first.
