### ISSUE TITLE
Xwaylandvideobridge

### ISSUE THREAD

**Issue by sekalengrengginang** [ublue-os/main#228]
### Describe the package

I'd like to request the package `xwaylandvideobridge` because 

QOL improvement when doing screensharing with apps that doesn't support xdg-portal/pipewire like discord
it's available at Fedora 38 repo
https://bodhi.fedoraproject.org/updates/FEDORA-2023-45dd2ed8e1
http://blog.davidedmundson.co.uk/blog/xwaylandvideobridge/

### Information on the package

Paste the results of `dnf info packagename` here
```
Available Packages
Name         : xwaylandvideobridge
Version      : 0~git20230504.3445aff
Release      : 2.fc38
Architecture : x86_64
Size         : 66 k
Source       : xwaylandvideobridge-0~git20230504.3445aff-2.fc38.src.rpm
Repository   : updates
Summary      : Utility to allow streaming Wayland windows to X applications
URL          : https://invent.kde.org/system/xwaylandvideobridge
License      : GPL-2.0-or-later
Description  : By design, X11 applications can't access window or screen contents
             : for wayland clients. This is fine in principle, but it breaks screen
             : sharing in tools like Discord, MS Teams, Skype, etc and more.
             : 
             : This tool allows us to share specific windows to X11 clients,
             : but within the control of the user at all times.
```

### Image

Kinoite

**Comment by castrojo** [comment]
Is this kinoite specific or should we do it for all the 38 desktops?

**Comment by sekalengrengginang** [comment]
i think for now just do it at kinoite image since GNOME have color issue 
https://invent.kde.org/davidedmundson/xwaylandvideobridge/-/issues/1

**Comment by castrojo** [comment]
Alright, +1 from me!

**Comment by Arcitec** [comment]
> Is this kinoite specific or should we do it for all the 38 desktops?

The native package has a lot of KDE dependencies:

https://src.fedoraproject.org/rpms/xwaylandvideobridge/blob/rawhide/f/xwaylandvideobridge.spec

Which leads to the following results on Fedora Workstation:

```
$ sudo dnf in xwaylandvideobridge
Dependencies resolved.
================================================================================
 Package                Arch     Version                        Repo       Size
================================================================================
Installing:
 xwaylandvideobridge    x86_64   0~git20230504.3445aff-2.fc38   updates    66 k
Installing dependencies:
 breeze-icon-theme      noarch   5.106.0-1.fc38                 updates   7.6 M
 dbusmenu-qt5           x86_64   0.9.3-0.30.20160218.fc38       fedora     79 k
 kde-settings           noarch   38.2-2.fc38                    fedora     40 k
 kf5-kconfig-core       x86_64   5.104.0-1.fc38                 fedora    352 k
 kf5-ki18n              x86_64   5.104.0-1.fc38                 fedora    1.7 M
 kf5-knotifications     x86_64   5.106.0-1.fc38                 updates   187 k
 kf5-kwindowsystem      x86_64   5.104.0-1.fc38                 fedora    212 k
 kpipewire              x86_64   5.27.5-1.fc38                  updates   129 k
 qt5-qtspeech           x86_64   5.15.9-1.fc38                  updates    44 k
Installing weak dependencies:
 qt5-qtspeech-speechd   x86_64   5.15.9-1.fc38                  updates    24 k
```

So the ideal solution on non-KDE desktops would be to use the Flatpak version of this tool.

**Comment by TheEvilSkeleton** [comment]
Any thoughts on using the Flatpak everywhere (including Plasma)? At least you'd be installing the same version of the package everywhere.

**Comment by castrojo** [comment]
Yeah let's put it in the justfile (someone will need to PR that seperately)!  If someone wants to PR this into the Kinoite image please feel free to do so and one of us will approve it.

**Comment by castrojo** [comment]
Once it's through the merge queue it'll auto close this, if there are any subsequent issues/concerns please open a new issue, thanks everyone for their due diligence on this!
