### ISSUE TITLE
Error at boot with systemd since few days

### ISSUE THREAD

**Issue by Froggy232** [ublue-os/main#238]
Hi,
Since few days ago, I can't boot without an error message.
It seems that systemd-modules-load.service failed to init.
The system seems to run normally, I don't have any bug.
I haven't made modifications in my system I think, just the regular update.
Is this message important?
Does the problem come from my config, or it's a an known problem?
Thanks you

**Comment by EyeCantCU** [comment]
Hi. I'm glad to help with this.

If you run:
`systemctl status systemd-modules-load`
There is a section at the bottom titled "process" and right after that is a number. This represents the process ID. Take that number and do this:
`journalctl _PID=YOUR_NUMBER_GOES_HERE`
And then just paste the output here :)

Thank you!

**Comment by Froggy232** [comment]
Hi,
I'm very sorry, I have since switched back to Fedora Silverblue.
Thanks for your answer!
