### ISSUE TITLE
Package request: Include KSSHAskPass in Kinoite images

### ISSUE THREAD

**Issue by EyeCantCU** [ublue-os/main#240]
### Describe the package

I'd like to request the package `ksshaskpass` because it simplifies the process of managing sh key passwords by allowing you to save them directly to KWallet. For example, typically when you push to a GitHub repository, a username and password are traditionally requested in the console. Instead of the console requesting this info, KSSHAskPass will prompt the user with a dialog allowing them to save the username and password to KWallet for future use.

See: https://github.com/ublue-os/main/pull/239

### Information on the package

Name         : ksshaskpass
Version      : 5.27.5
Release      : 1.fc38
Architecture : x86_64
Size         : 63 k
Source       : ksshaskpass-5.27.5-1.fc38.src.rpm
Repository   : updates
Summary      : A ssh-add helper that uses kwallet and kpassworddialog
URL          : https://cgit.kde.org/ksshaskpass.git
License      : GPLv2
Description  : A ssh-add helper that uses kwallet and kpassworddialog.

### Image

Kinoite

**Comment by castrojo** [comment]
https://github.com/ublue-os/main/pull/239

+1 from me, unless there's any major objections I'll merge this tonight (unless someone gets to it first)
