### ISSUE TITLE
Nautilus Preview - MP3 Files with Embedded Images

### ISSUE THREAD

**Issue by dperson** [ublue-os/main#245]
### Discussed in https://github.com/orgs/ublue-os/discussions/171

<div type='discussions-op-text'>

<sup>Originally posted by **dperson** May 31, 2023</sup>
uBlue-os/main fixed the video thumbnails, but at least for me seems to have broken thumbnails for MP3 files with embedded images. These work under upstream Fedora Silverblue 38, but not either the uBlue-os/main or my lightly tweaked startingpoint spin.

I've deleted the failed (`rm -frv .cache/thumbnails/fail/*`) thumbnails but they just fail again. Not seeing anything in Logs at the point that I reload the directory to have it fail to find the thumbnails again.</div>

**Comment by fiftydinar** [comment]
Works properly here:
![Screenshot from 2023-06-25 19-35-02](https://github.com/ublue-os/main/assets/65243233/4c22b366-c686-4ac5-9c2a-a83ffd835d15)

**Comment by castrojo** [comment]
Yeah I think the last round of thumbnail fixes caught this? Closing but please reopen if it's a problem, thanks!
