### ISSUE TITLE
AppImage Managment

### ISSUE THREAD

**Issue by fiftydinar** [ublue-os/main#246]
### Describe the package

AppImages are useful & probably a more sane solution to snaps, if you want to download some packages not avaliable in flatpak without making a mess to the system.

Some developers use AppImages instead of Flatpak, so you have no other choice. Or you have deb/rpm packages as a choice, which should be avoided when using immutable OSes.
F.e., UBPorts installer app has either .deb, Snap or AppImage.

Currently, there is no way to have AppImages managed automatically when you download them.
If you are lazy, you keep AppImages in Download folder, which is messy.
Or you organize them manually yourself in some special folder.
Things can get more messy when you have different versions of same app in AppImage.
Etc.

I found 2 approaches to this.

1.
Use an frontend like AppImage Pool, which is similar to Gnome's Software or KDE's Discover, where downloading, installing & managing of AppImages are done automatically.

Cons:
- Some open source AppImages are either not avaliable, or they are 3rd party outdated version of it. Latest versions are usually hosted on github/gitlab or app's website, where you have to go manually.
AppImageHub has same issues.
Example: UBPorts Installer.
- application writes to standard /home/user/Applications/ & /home/user/.local folders for .desktops & icons, which is not an ideal, clean solution. Screenshot provided to see that behavior.
- Here's the screenshot (Don't mind the glitch around the window, it's due to Rounded Window Corners extension I use)
![Screenshot from 2023-06-15 15-38-25](https://github.com/ublue-os/main/assets/65243233/528c95a1-b23e-4226-83c6-6f823e67640d)
 
2.
Use Gear Lever, where user is in charge of downloading AppImages they want, but make installing & managing of those AppImages automatic operation.

Cons:
- No automatic & no-worry download of latest AppImages like you have with Flatpaks.
- App is very new, it's yet to be properly tested.

Some of those issues are also probably due to AppImage architerctural nature of itself.

I am not sure if this is something in the scope of main, but I'm sure that uBlue wants to have as better out-of-the-box experience as possible for the end user. If not in the main image, maybe in some more opinionated image.

Someone who researched those topics more seriously can hopefully chime in & discuss some better solutions.

### Information on the package

Source:
AppImage Pool:
https://flathub.org/apps/io.github.prateekmedia.appimagepool
https://github.com/prateekmedia/appimagepool

Gear Lever:
https://www.reddit.com/r/gnome/comments/13s98y9/working_on_an_app_to_install_and_manage_appimages/
https://www.reddit.com/r/gnome/comments/147pye7/gear_lever_appimage_manager_has_been_released/
https://flathub.org/apps/it.mijorus.gearlever
https://github.com/mijorus/gearlever

### Image

All Images

**Comment by sekalengrengginang** [comment]
i don't think appimage is suitable for uBlue.
for example if appimage required some dependency that doesn't exist on uBlue, it will not work since appimage still using host system dependency.

**Comment by fiftydinar** [comment]
> i don't think appimage is suitable for uBlue. for example if appimage required some dependency that doesn't exist on uBlue, it will not work since appimage still using host system dependency.

You're probably right. I thought on using AppImage in case of unavaliable flatpaks, but it seems that distrobox is a way better solution for those issues.

**Comment by castrojo** [comment]
Yeah better appimage management is firmly in distro territory, I don't think we want to sign up for this.
