### ISSUE TITLE
Add HEIF/HEIC thumbnail generation support (fixed)

### ISSUE THREAD

**Issue by fiftydinar** [ublue-os/main#254]
### Describe the package

Original issue:
https://github.com/ublue-os/main/issues/252

I found out that including libheif-tools only is not enough for HEIC/HEIF thumbnails to properly show up.
They disappear on reboot, or in some cases, do not appear at all.

It is something to do with libheif & its gtk-pixbuf-loader component failing to provide that functionality.

Until the issue is fixed on their side, we can use these 2 packages:

- heif-pixbuf-loader
- libheif-freeworld (from RPM-Fusion)

To fix these issues.

Note that libheif-tools is still needed for thumbnailing in combination of these 2.

I tested all combinations, including using normal libheif with libheif-tools & heif-pixbuf-loader, and the combination which I proposed above is the only one which works.

### Information on the package

Name         : heif-pixbuf-loader
Version      : 1.16.1
Release      : 1.fc38
Architecture : x86_64
Size         : 14 k
Source       : libheif-1.16.1-1.fc38.src.rpm
Repository   : updates
Summary      : HEIF image loader for GTK+ applications
URL          : https://github.com/strukturag/libheif
License      : LGPL-3.0-or-later and MIT
Description  : This package provides a plugin to load HEIF files in GTK+
             : applications.

Repository	[RPM Fusion Free Updates x86_64](https://fedora.pkgs.org/38/rpmfusion-free-updates-x86_64/) Third-Party
Package filename	libheif-freeworld-1.16.1-1.fc38.x86_64.rpm
Package name	libheif-freeworld
Package version	1.16.1
Package release	1.fc38
Package architecture	x86_64
Package type	rpm
Homepage	https://github.com/strukturag/libheif
License	LGPL-3.0-or-later and MIT
Maintainer	-
Download size	50.57 KB
Installed size	116.45 KB

### Image

All Images

**Comment by EyeCantCU** [comment]
Your PR with these packages has been merged. Thank you very much :)
