### ISSUE TITLE
Add python-validity support

### ISSUE THREAD

**Issue by bima0302** [ublue-os/main#267]
### Describe the package

I was hoping to get the `python-validity` (https://github.com/uunicorn/python-validity) package out of the box in this image. 
Thus, fingerprints can be used on most types of laptops.

### Information on the package

https://github.com/uunicorn/python-validity
Validity fingerprint sensor driver.

### Image

All Images

**Comment by tulilirockz** [comment]
Considering this is hardware enablement, maybe this issue would better fit the [config layer](https://github.com/ublue-os/config)

**Comment by fiftydinar** [comment]
Interesting.

I would like to know some personal experiences with specific laptop models, which got working fingerprint after installing this package. So far, I could not find any anecdotal experiences on this.

Just a note that those dependencies should be installed as well, as listed in main page:
open-fprintd
fprintd-clients
fprintd-clients-pam

**Comment by jtbrough** [comment]
As an anecdote: python-validity is required to get the fingerprint readers working on both of my ThinkPads (T480s and X1 Nano). I would love to see an option for this.

I suppose it makes sense here given that ublue has a strong foundation of hardware enablement.

`Bus 001 Device 004: ID 06cb:009a Synaptics, Inc. Metallica MIS Touch Fingerprint Reader`

**Comment by castrojo** [comment]
Alright so this isn't in any repo and no one seems to be working on it, if someone wants to work on this please reopen.
