### ISSUE TITLE
Kinoite: why steamdeck packages? dependency errors trying to update

### ISSUE THREAD

**Issue by firefoxlover** [ublue-os/main#275]
### What happened?

Why are there steamdeck packages installed?

I removed it but get the attached error trying to update. 

Can you please make this nonstandard and fix the dependency issue?

### Relevant log output

```shell
Problem: package kmod-steamdeck-6.3.12-200.fc38.x86_64-0.0.git.3.1ff803dd-1.fc38.x86_64 from @System requires steamdeck-kmod-common >= 0.0.git.3.1ff803dd, but none of the providers can be installed
```
```

**Comment by castrojo** [comment]
Where are you getting this error?

**Comment by KyleGospo** [comment]
The `steamdeck-kmod` and `steamdeck-kmod-common` packages provide the needed platform drivers for Valve's Steam deck, they take up < 100KB and do nothing unless you're running on the hardware.

If you still want to remove them you'll need to remove both.

**Comment by firefoxlover** [comment]
Interesting, thanks. I tried removing them but it didnt work. With these names it should work normally.
