### ISSUE TITLE
Default fedora policy doesn't allow rebasing to signed ublue images

### ISSUE THREAD

**Issue by castrojo** [ublue-os/main#277]
From a fresh F38 install. 

```
[jorge@fedora ~]$ rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx
Pulling manifest: ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx
error: Preparing import: Fetching manifest: containers-policy.json specifies a default of `insecureAcceptAnything`; refusing usage
```

I'm not sure if we should encourage people to rebase to unsigned images first and then kick over?

**Comment by castrojo** [comment]
Plopping our policy.json in the right place let's you upgrade from Fedora to one of our images:

```
sudo curl -L https://github.com/ublue-os/config/raw/main/files/usr/etc/containers/policy.json -o /etc/containers/policy.json
```

**Comment by returnofblank** [comment]
Can confirm that I am experiencing this on a fresh F38 install.

**Comment by KyleGospo** [comment]
```podman pull ghcr.io/ublue-os/config && rpm-ostree install --assumeyes --apply-live --force-replacefiles $(find ~/.local/share/containers -name ublue-os-signing.noarch.rpm 2>/dev/null) && rpm-ostree rebase --uninstall $(rpm -q ublue-os-signing-* --queryformat '%{NAME}-%{VERSION}-%{RELEASE}.%{Arch}') ostree-image-signed:docker://ghcr.io/ublue-os/main:latest```

This will download & install the ublue signing RPM, then rebase and uninstall it at the same time.

**Comment by returnofblank** [comment]
> ostree-image-signed:docker://ghcr.io/ublue-os/main:latest

"main" is not an image I don't think, you'd have to specify Silverblue and such. So it would be `podman pull ghcr.io/ublue-os/config && rpm-ostree install --assumeyes --apply-live --force-replacefiles $(find ~/.local/share/containers -name ublue-os-signing.noarch.rpm 2>/dev/null) && rpm-ostree rebase --uninstall $(rpm -q ublue-os-signing-* --queryformat '%{NAME}-%{VERSION}-%{RELEASE}.%{Arch}') ostree-image-signed:docker://ghcr.io/ublue-os/silverblue-main:latest` if you wanted to install the Silverblue UBlue image.

When I ran the command you provided, it failed on the rebase, because the image did not exist. I could just be wrong though.

**Comment by KyleGospo** [comment]
> > ostree-image-signed:docker://ghcr.io/ublue-os/main:latest
> 
> "main" is not an image I don't think, you'd have to specify Silverblue and such. So it would be `podman pull ghcr.io/ublue-os/config && rpm-ostree install --assumeyes --apply-live --force-replacefiles $(find ~/.local/share/containers -name ublue-os-signing.noarch.rpm 2>/dev/null) && rpm-ostree rebase --uninstall $(rpm -q ublue-os-signing-* --queryformat '%{NAME}-%{VERSION}-%{RELEASE}.%{Arch}') ostree-image-signed:docker://ghcr.io/ublue-os/silverblue-main:latest` if you wanted to install the Silverblue UBlue image.
> 
> When I ran the command you provided, it failed on the rebase, because the image did not exist. I could just be wrong though.

I should have noted that that is an example, please change the very end to whichever image you want

**Comment by returnofblank** [comment]
This issue should be fine to close now, with #276 merged, I was able to rebase to the signed images.

**Comment by EyeCantCU** [comment]
I concur

**Comment by larina3315** [comment]
I am on Fedora SB 39 and I am still facing this issue on the cinnamon image

```
rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/cinnamon-main:38
```
```
Pulling manifest: ostree-image-signed:docker://ghcr.io/ublue-os/cinnamon-main:38
error: Preparing import: Fetching manifest: containers-policy.json specifies a default of `insecureAcceptAnything`; refusing usage
```
