### ISSUE TITLE
proposal: use NTS by default

### ISSUE THREAD

**Issue by Renner0E** [ublue-os/main#279]
NTS is a SSL/TLS secured way to authenticate NTP traffic on the net.

[GrapheneOS](https://grapheneos.org/) uses [this config](https://raw.githubusercontent.com/GrapheneOS/infrastructure/main/chrony.conf) for `/etc/chrony.conf`

Fedora ships chronyd by default but [doesn't enable NTS by default.](https://fedoramagazine.org/secure-ntp-with-nts/)
[
Why they don't enable it by default](https://fedoraproject.org/wiki/Changes/NetworkTimeSecurity#Detailed_Description).

I think that this would still be beneficial.

**Comment by KyleGospo** [comment]
Thanks for the suggestion. Regardless of what main decides to do here I went ahead and used this on the deck variant of [Bazzite](https://github.com/ublue-os/bazzite).

https://github.com/ublue-os/bazzite/commit/b0c77432a66f6608fedc407529ce9abddf88198c

**Comment by akdev1l** [comment]
In my opinion we shouldn't drift from Fedora defaults unless there's a very compelling argument.

**Comment by Renner0E** [comment]
> Thanks for the suggestion. Regardless of what main decides to do here I went ahead and used this on the deck variant of [Bazzite](https://github.com/ublue-os/bazzite).
> 
> [ublue-os/bazzite@b0c7743](https://github.com/ublue-os/bazzite/commit/b0c77432a66f6608fedc407529ce9abddf88198c)

Awesome! Glad I could help in some way.
