### ISSUE TITLE
rpm-ostree status shows langpacks-en automatically layered after fresh install

### ISSUE THREAD

**Issue by jkemp814** [ublue-os/main#281]
Is there a way to include langpacks-en in the Coreos with Firefox, which is what I believe it is a dependency for? That way it is not layered? 

State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 8h ago
Deployments:
● ostree-unverified-image:docker://ghcr.io/ublue-os/silverblue-nvidia:38
                   Digest: sha256:dca7652e9d722ca4a12f1126b5f71c52a7577878912db8b646179b0f0f75b12b
                  Version: 38.20230717.0 (2023-07-17T19:40:26Z)
          LayeredPackages: langpacks-en

  ostree-unverified-image:docker://ghcr.io/ublue-os/silverblue-nvidia:38
                   Digest: sha256:dca7652e9d722ca4a12f1126b5f71c52a7577878912db8b646179b0f0f75b12b
                  Version: 38.20230717.0 (2023-07-17T19:40:26Z)

**Comment by jkemp814** [comment]
I see, and understand. I was wondering why it installed itself. Would be nice to have an installation with nothing layered is what I'm trying to achieve.

Thank you for the detailed response.

**Comment by bsherman** [comment]
> When you think about it, they probably wait until after the installation, due to other langpacks around the world.

This is a good insight. I had not thought about that. This would be a good reason to not attempt fixing it as our fix would likely be language specific.

**Comment by jkemp814** [comment]
Yup, I'll close this.
