### ISSUE TITLE
`insecureAcceptAnything`; refusing usage

### ISSUE THREAD

**Issue by firefoxlover** [ublue-os/main#286]
### What happened?

trying to rebase from Kinoite to kinoite-main ublue

This was reported (#28 ) Is there any solution for it? There was onee using podman and installing it as a huge rpm as far as I know.

Using the command from the website it doesnt work.

### Relevant log output

```shell
/v/h/user ❯❯❯ rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/kinoite-main:38

Pulling manifest: ostree-image-signed:docker://ghcr.io/ublue-os/kinoite-main:38
error: Preparing import: Fetching manifest: containers-policy.json specifies a default of `insecureAcceptAnything`; refusing usage```
```

**Comment by hanscees** [comment]
this also happens with the bluefin images

**Comment by castrojo** [comment]
We need to see `rpm-ostree status` to know where you're starting from.

**Comment by castrojo** [comment]
Also just confirming that you've rebased to an unsigned image first? https://universal-blue.org/images/#rebase-to-an-unsigned-image-first

**Comment by firefoxlover** [comment]
for me, yes afaik I can rebase to unsigned and then to signed. would there be any better solution, as this is kind of a "trust me bro" step?

**Comment by castrojo** [comment]
It's a temporary solution until the upstream installer gets support for installing a signed image.

**Comment by hanscees** [comment]
For me rebase to unsigned does not work but gets another error

**Comment by secretmango** [comment]
hi there, what was the workaround for this *before* uBlue decided to go ISO only?

I rebased to signed uBlue images all the time in the past
