### ISSUE TITLE
Possibility for privacy-first hardened version?

### ISSUE THREAD

**Issue by trytomakeyouprivate** [ublue-os/main#287]
### Describe the package

This would be rather complex and may need to be dealt with upstream

- maintain up to date hardened kernel rpm (COPR?)
- hardened malloc rpm (COPR)
- a minimal image
- security aspects similar to [GrapheneOS](grapheneos.org) (?)
- automatic background updates for rpm, firmware and flatpak
- hardened systemd-resolved
- ...

There is (again) a [new continued COPR repo](https://copr.fedorainfracloud.org/coprs/solidcore/coreos-kernel-hardened/) containing both RPMs.

### Information on the package

.

### Image

All Images

**Comment by castrojo** [comment]
Cool project for sure! Let's start by getting them in https://github.com/ublue-os/awesome-custom-images

**Comment by castrojo** [comment]
This is out of scope for us though!
