### ISSUE TITLE
Add framework images

### ISSUE THREAD

**Issue by castrojo** [ublue-os/main#288]
(sorry on a plane will add more detail later)

We may have a volunteer to help do this after I announced the project on the framework forums. Just outlining what we'd need to do this. The TLDR is we're swapping out the gnome-power-manager thing for `tlp`, which means the images would also be handy for people who want to tweak their laptops for power sipping. 

### What we have

- bluefin has a bluefin-framework and bluefin-dx-framework which swaps out tlp and installs some extra packages, which I inline directly in the container file.
- I ship the default recommended tlp configs from framework in /etc/tlp/blah. 
- There's a `just framework-13` post install shortcut to add the kernel parameters since we can't (yet) do that in the containerfile.

This was great to test it, and I'm currently at 35,000 feet and it's rocking in bluefin. Now would be a good time to diversify and unlock the potential in all the images so that if you want goodies but want a different desktop you'll be good to go: 

## What we'd need

- The tlp packages would need to be added as a section in a framework section in `packages.json`
- We'd need to add the tlp configs to ublue-os/config so that we can inherit them, but similar to akmods provide them in there in a way that doesn't pollute people in other images. I just created a "framework" directory in my repo, but whatever makes sense for config would be better. 
- Template out generating the images here, but additionally snag the framework configs from config so that those configs end up on the right image but not on the others, like how bazzite does it.
- We should probably skip 37 and do 38 only and that would get us ready for 39.
- We have to expand the just shortcuts to include specific things for each generation. 
- We should add some empty tlp files with commented out with pointers to encourage others to add their own profiles in ublue-os/config so that we have a good set. Whatever templates/naming conventions we come up with should also be flexible enough to let people do generation specific tweaks so that we don't have to make images for each different one (unless we have to), we can concentrate on tlp and kargs for now and that will help us test.

## Bonus Points

- If we're fixing up `packages.json` anyway then we should split out the x86 specific things, we need this to support ARM anyway. 
- I'll probably need a hand to remove the framework stuff from bluefin so I can inherit it from config/main since that's the right way to do it.
- Docs for framework users. Once it's rocking and rolling we need a /framework page so that anyone with one of these can have one unified page. Since I own one of these I'll volunteer for this one. 

If I missed anything please add it.

**Comment by castrojo** [comment]
After discussing with @bobslept we think that just having a framework repo to generate them based off of main is the way to go so the build matrix here doesn't end up having to make a ton of images at once. 

That way we can build them after main and keep some seperation of concerns.

**Comment by bobslept** [comment]
Current state:
- Publish an image of all the main images in form of `silverblue-framework` or `kinoite-framework` and so on
- `tlp` and `fprintd` added. `power-profiles-daemon` removed via framework-packages.json (including or excluding possible per image if needed)
- things for `tlp` and `fprintd` currently shipped inside container via simple `COPY`

Things todo and probably more things I forgot:
- add iso releases, issue template, reset cosign key that kind of stuff
- ship default configs via configs repo?
- `just framework-kargs` and others probably via configs repo
- ship custom configs based on image, for example set scaling on `silverblue` works different then on `kinoite` 

I think the todo's can be worked on when the repo is embedded inside ublue-os org. I also need some guidance  on how to do things via the configs repo and how to structure that without making a mess there.

Feel free to grab the repo and push it into `ublue-os`
https://github.com/bobslept/framework-wip

**Comment by castrojo** [comment]
Thanks for working on this! We can add the configs later, I think just getting them to build will work for now. Don't worry about the signing we can do that in the org repo.

**Comment by castrojo** [comment]
Thanks for working on this! We can add the configs later, I think just getting them to build will work for now. Don't worry about the signing we can do that in the org repo.

**Comment by castrojo** [comment]
WOOO! DONE!
