### ISSUE TITLE
Implement a community governance structure

### ISSUE THREAD

**Issue by castrojo** [ublue-os/main#289]
Alright everyone, one of the final bits I've been putting off but now it's time to get ready for the big show. THIS IS UNFINISHED. And as you can see, busted links, etc. But it's getting late and I'd rather move fast.

- https://github.com/ublue-os/website/pull/317

This adds a few things. Membership levels with some defined roles and responsibilities. This is basically the Kubernetes governance but stripped down a ton for us. 

Having contributed to that governance I found it difficult to make something that defines well run open source projects but stripped down enough to not be so much work 😄 . So here it is, as always, comments and improvements welcome, and then everyone who has rights in the repo will slot into Approvers and then we'll see where everyone else lies. 

And then we'll have a clear path.

**Comment by castrojo** [comment]
Oh, should have made this more obvious, right now the org admins in main are @akdev1l @bigpod98 @bsherman @EyeCantCU @joshua-stone @KyleGospo @p5 @marcoceppi and @castrojo  

And then we'd structure the teams in github that way, which won't apply until the end of the month because I downgraded us to the free tier to get us out of this mess in the first place lol.

**Comment by bsherman** [comment]
This is looking pretty good!
