### ISSUE TITLE
rpm-ostree failing to update because it can't find usblue-os.pub 

### ISSUE THREAD

**Issue by r890BkzxmD** [ublue-os/main#298]
Hello big n00b here, not sure how I got myself into this.

I get a couple of errors when it's been trying to update

`error: Creating importer: Failed to invoke skopeo proxy method OpenImage: remote error: open /usr/etc/pki/containers/ublue-os.pub: no such file or directory`

I looked into /pki and there isn't a containers folder, but the ublue-os.pub file is there, but I can't make containers because it's read only. 

and the second when I try to update through Discover,
`rpm-ostree transaction failed with:
time="2023-08-12T11:21:19-05:00" level=fatal msg="Error parsing image name \"docker://ghcr.io/ublue-os/kinoite-nvidia:latest\": pinging container registry ghcr.io: Get \"https://ghcr.io/v2/\": dial tcp: lookup ghcr.io: i/o timeout"`

here is my rpm-ostree status -v

`State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-unverified-registry:ghcr.io/ublue-os/kinoite-nvidia:latest (index: 0)
                   Digest: sha256:a2574d5a18bae4f5c907300aa4d76ba9592066db6ec6a595f2cb5ecb713ba52f
                  Version: 38.20230719.0 (2023-07-19T17:07:59Z)
                   Commit: 7bd8c62f7fb752be393872d4168c89b367a6033674cc3a432ee61b781681f2b5
                   Staged: no
                StateRoot: fedora

  ostree-unverified-registry:ghcr.io/ublue-os/kinoite-nvidia:latest (index: 1)
                   Digest: sha256:a2574d5a18bae4f5c907300aa4d76ba9592066db6ec6a595f2cb5ecb713ba52f
                  Version: 38.20230719.0 (2023-07-19T17:07:59Z)
               BaseCommit: 7bd8c62f7fb752be393872d4168c89b367a6033674cc3a432ee61b781681f2b5
                   Commit: f16a5fa29dee2e1f711ded89fbd81f7d84d3dbadcbb1d3ce09ddfdda2134097f
                           ├─ fedora (2023-04-13T20:37:10Z)
                           ├─ rpmfusion-free (2023-04-14T11:37:11Z)
                           ├─ rpmfusion-free-updates (2023-07-14T20:29:32Z)
                           ├─ rpmfusion-nonfree (2023-04-14T12:02:51Z)
                           ├─ rpmfusion-nonfree-updates (2023-07-14T20:44:39Z)
                           ├─ updates (2023-07-19T03:02:28Z)
                           └─ updates-archive (2023-07-19T03:39:10Z)
                StateRoot: fedora
          LayeredPackages: gnome-boxes`

**Comment by castrojo** [comment]
Which instructions were you following? Please paste in the output of `rpm-ostree status`

**Comment by castrojo** [comment]
Looks like you're on our image and just need to rebase, try this:

    rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/kinoite-nvidia:latest

**Comment by r890BkzxmD** [comment]
> Looks like you're on our image and just need to rebase, try this:
> 
> ```
> rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/kinoite-nvidia:latest
> ```

I get this `error: Creating importer: Failed to invoke skopeo proxy method OpenImage: remote error: open /usr/etc/pki/containers/ublue-os.pub: no such file or directory`

**Comment by castrojo** [comment]
Can you do a `rpm-ostree update` in the CLI? Looks like you're on an image from July.

**Comment by r890BkzxmD** [comment]
It's the same error, is the ublue-os.pub file supposed to be in the containers folder? it's currently in the pki folder, but I don't have a containers folder

**Comment by castrojo** [comment]
`/usr/etc/pki/containers/ublue-os.pub` is where mine is. You don't have it on there because the machine hasn't updated since July 19th, which is before we switched to signed images. Let's try this:

    podman pull ghcr.io/ublue-os/config && rpm-ostree install --assumeyes --apply-live --force-replacefiles $(find ~/.local/share/containers -name ublue-os-signing.noarch.rpm 2>/dev/null) && rpm-ostree rebase --uninstall $(rpm -q ublue-os-signing-* --queryformat '%{NAME}-%{VERSION}-%{RELEASE}.%{Arch}') ostree-image-signed:docker://ghcr.io/ublue-os/kinoite-nvidia:latest

**Comment by r890BkzxmD** [comment]
Sorry I should have mentioned I tried that. I still get the same error `Error: Source image rejected: open /usr/etc/pki/containers/ublue-os.pub: no such file or directory` because it can't find ublue-os.pub.

**Comment by castrojo** [comment]
Do you have time to hop in the discord? https://discord.gg/XjG48C7VHx

**Comment by castrojo** [comment]
For future issues with machines with old updates. The most straightforward way is to `rpm-ostree rebase fedora:fedora/38/x86_64/kinoite` to get them back onto stock Fedora, and then reboot. 

And then follow the installation instructions again and it all works out. (You might need to edit the kernel arguments on boot to unblocklist noveau if you're on an nvidia image.)
