### ISSUE TITLE
Move `*-nvidia` image build workflow into `main` repo

### ISSUE THREAD

**Issue by bsherman** [ublue-os/main#313]
Now that [nvidia](https://github.com/ublue-os/nvidia) has removed the building of the nvidia kmod in favor of a build from [akmods](https://github.com/ublue-os/akmods), we can easily migrate the building of `*-nvidia` images into this repo as a job that runs after successful `*-main` builds.

**Comment by castrojo** [comment]
This is going to be so cool, the efficiency benefits on real builders will be awesome!

**Comment by EyeCantCU** [comment]
This is great idea. I'll work on this first thing tomorrow
