### ISSUE TITLE
Ublue media package

### ISSUE THREAD

**Issue by Gecked-Deck** [ublue-os/main#317]
A Ublue media package with all assets such as wallpapers, logos and icons would be much appreciated for people covering ublue.

**Comment by castrojo** [comment]
Just adding that the circular blue icon has always been a placeholder. I'm working on getting new assets, but that shouldn't block this work!

**Comment by rothgar** [comment]
By "package" do you mean an rpm/deb or landing page on the website with media assets?

Bazzite has a press kit https://github.com/ublue-os/bazzite/tree/main/press_kit

**Comment by Gecked-Deck** [comment]
A landing page or something similar to bazzite would be good.

**Comment by castrojo** [comment]
This is out of scope for main.
