### ISSUE TITLE
Set up a -1 release convenience tag

### ISSUE THREAD

**Issue by castrojo** [ublue-os/main#329]
Since the OCI feature from Fedora we need to go stable has been punted to F40 we should set up a convenience tag for the latest release -1 so we can get 2 major upgrades under our belt. Here's the spec from a while back. 

- https://github.com/orgs/ublue-os/discussions/116

**Comment by bobslept** [comment]
For the main repo images this is done in this PR https://github.com/ublue-os/main/pull/301

From @EyeCantCU 
> 39 won't get pushed to that until it is marked as stable. When that happens, we set the flag for latest and stable releases to false for 38 but keep gts true and that will be the release that stays behind. 

So when f39 hits stable, we should see gts pop up in our tags for f38.

**Comment by EyeCantCU** [comment]
> For the main repo images this is done in this PR https://github.com/ublue-os/main/pull/301
> 
> From @EyeCantCU 
> > 39 won't get pushed to that until it is marked as stable. When that happens, we set the flag for latest and stable releases to false for 38 but keep gts true and that will be the release that stays behind. 
> 
> So when f39 hits stable, we should see gts pop up in our tags for f38.
> 
> After looking at the changes, I think we need to implement it for all the other repo's where we want to use this strategy the same way. It will not flow down automaticly.
> 

I can get that setup sometime today :)

**Comment by bobslept** [comment]
Tried to make a list with all the PR's implemented this for easier tracking. I hope i've got them all.
Thanks @EyeCantCU 

- https://github.com/ublue-os/main/pull/301
- https://github.com/ublue-os/bluefin/pull/594
- https://github.com/ublue-os/surface/pull/20
- https://github.com/ublue-os/asus/pull/15
- https://github.com/ublue-os/framework/pull/42

**Comment by bobslept** [comment]
With f39 being marked as stable, all the gts versions are live and usable as `:gts`
