### ISSUE TITLE
Provide instructions to "opt out" of automatic updates

### ISSUE THREAD

**Issue by RedTopper** [ublue-os/main#33]
Hey!

I think having a default auto-update policy is great, but for my workstation I tend to try and "audit" what packages get added and removed between updates and give a chance of pinning deployments should I need to roll back a few versions. I also prevent my TPM from unlocking my root disk if any changes have been made to GRUB, which happens on an update.

I looked at this repo, the config repo, and then the documentation for `rpm-ostreed`. It seems I'll just need to set AutomaticUpdatePolicy to "none" in `/etc/rpm-ostreed.conf` (and if I wanted to, `systemctl disable flatpak-system-update.timer`, but automatic updates to flatpack sounds nice). Would it be reasonable to include these instructions in the README if this is the proper way to do this?

I figured I would open an issue here just to get some discussion on how others use automatic updates and how they administer their systems.

**Comment by castrojo** [comment]
Yeah, don't have time now but whoever wants take a stab at it let's add it to ublue-os/website and the readme.

**Comment by RedTopper** [comment]
Fantastic! I've been using the downstream nvidia image and been poking around these repos before I update to see what's changed. Gives me a chance to see what you're all up to!
