### ISSUE TITLE
[Feature Request] A nix rpm package

### ISSUE THREAD

**Issue by dnkmmr69420** [ublue-os/main#333]
I was thinking that nix should be packaged as an rpm and here are the main reasons why we should do it:

- It can be more easily included
- The systemd unit files would be immutable since it would be at `/usr/lib/systemd/system`
- Harder to accidently uninstall nix (I have accidently uninstalled nix before by pressing 1 instead of 2 with `nix profile remove`)
- Can be easily updated along with the system
- Keeps `/etc/systemd/system` a little cleaner as well
- It may be possible to have nix have GPU acceleration without any wrappers (at least for non NVIDIA systems)
- Other distros can easily install nix by using `sudo rpm-ostree install nix` or `sudo dnf install nix` or what ever package manager that uses rpm as its backend

**Comment by castrojo** [comment]
This is out of scope for main.
