### ISSUE TITLE
chore: turn off the use of this repository as a github repo template

### ISSUE THREAD

**Issue by EinoHR** [ublue-os/main#34]
As this is intended to be the upstream for other Ublue images, I don't think this is supposed to be templated from, rather inherited on.
I don't believe I can do this myself, someone with full perms has to do it.

**Comment by EinoHR** [comment]
One person was confused and was going to template from main to create their own custom image. I believe that that shouldn't be done as main is intended to be the upstream, and the custom image the downest downstream.

**Comment by castrojo** [comment]
Done! (and did config too)
