### ISSUE TITLE
[Membership Request] @xynydev 

### ISSUE THREAD

**Issue by castrojo** [ublue-os/main#341]
As per https://universal-blue.org/membership/#member

This is to sponsor @xynydev to have membership rights across the ublue org. They already have Approver in startingpoint and website, so this is a nobrainer. This is currently adds a default of triage permissions across the org. 

I sponsor, I need one more person from @ublue-os/approver to +1 this nomination and then we'll add them to the team!

**Comment by KyleGospo** [comment]
+1

**Comment by akdev1l** [comment]
+1

**Comment by xynydev** [comment]
<3

**Comment by castrojo** [comment]
Done!

https://i.imgflip.com/kgznq.jpg
