### ISSUE TITLE
[Membership Request]  @bobslept

### ISSUE THREAD

**Issue by castrojo** [ublue-os/main#342]
As per https://universal-blue.org/membership/#member

This is to sponsor @bobslept to have membership rights across the ublue org. They already have Write in bluefin and has already started to dabble in other important repos. Basically Bob is awesome and just showed up one day and fixed a bunch of stuff that was important to people who use bluefin. 

This is currently adds a default of triage permissions across the org.

I sponsor, I need one more person from https://github.com/orgs/ublue-os/teams/approver to +1 this nomination and then we'll add them to the team!

**Comment by bobslept** [comment]
Thank you very much. What an awesome suprise. Means a lot :blue_heart:
