### ISSUE TITLE
[Membership Request] @bketelsen

### ISSUE THREAD

**Issue by castrojo** [ublue-os/main#343]
As per https://universal-blue.org/membership/#member

This is to sponsor @bketelsen to have membership rights across the ublue org. They already have Maintainer in Fleek and is a co-maintainer in Bluefin. Not much to say here other than we know he's a decently responsible adult. 😄 

This is currently adds a default of triage permissions across the org.

I sponsor, I need one more person from https://github.com/orgs/ublue-os/teams/approver to +1 this nomination and then we'll add them to the team!

**Comment by marcoceppi** [comment]
+1

**Comment by akdev1l** [comment]
+1

**Comment by castrojo** [comment]
Done!
