### ISSUE TITLE
[Bug] sometimes the system will default to noveau instead of NVIDIA if `akmod-nvidia` isn't installed

### ISSUE THREAD

**Issue by dnkmmr69420** [ublue-os/main#344]
This is happening on bazzite-desktop nvidia the latest version (f38). This bug only happens if you don't install `akmod-nvidia`. It can easily be fixed by layering `akmod-nvidia` but I have no idea what is causing this issue. I am using the NVIDIA GeForce RTX 2060/PCIe/SSE2

**Comment by EyeCantCU** [comment]
It would be awesome if you could dump your journal and dmesg here so we can get to the bottom of this

**Comment by ArtikusHG** [comment]
You should probably open an issue in [ublue-os/nvidia](https://github.com/ublue-os/nvidia), that is the repo for the main image, the nvidia one is separate.

**Comment by bsherman** [comment]
> You should probably open an issue in [ublue-os/nvidia](https://github.com/ublue-os/nvidia), that is the repo for the main image, the nvidia one is separate.

It's ok. We can move it if needed. No worries.
