### ISSUE TITLE
[Membership Request] @gerblesh

### ISSUE THREAD

**Issue by KyleGospo** [ublue-os/main#345]
As per https://universal-blue.org/membership/#member

This is to sponsor https://github.com/gerblesh to have membership rights across the ublue org. Their work on the ublue updater has been indispensable to Bazzite and a great addition to ublue as a whole, and they have shown themselves to be a capable developer and excellent team player.

I sponsor, I need one more person from https://github.com/orgs/ublue-os/teams/approver to +1 this nomination and then we'll add them to the team!

**Comment by castrojo** [comment]
+1!

**Comment by gerblesh** [comment]
thanks so much! Happy to help with such an amazing project!

**Comment by castrojo** [comment]
Alright, check your inbox! WOO!
