### ISSUE TITLE
Fingerprint Drivers XPS 15 9500

### ISSUE THREAD

**Issue by juliusm254** [ublue-os/main#351]
### Describe the package

I'd like to request Fingerprint Drivers XPS 15 9500 to allow logging into the system with.

I am running on bluefin dx.

### Image

All Images

**Comment by bsherman** [comment]
Per ArchWiki, fingerprint reader [works OOTB on XPS 15 9510](https://wiki.archlinux.org/title/Dell_XPS_15_(9510)), and I can confirm the same on a 9520 (since that's what I use with Universal Blue on a daily basis) 

But... it seems there's a different [device on the 9500, a 27c6:533c](https://forums.linuxmint.com/viewtopic.php?t=323306).  And... that does look to be a supported device from the link @castrojo shared.

> https://gitlab.com/-/snippets/2500389

However, reading that guide... it seems pretty sketchy. Warnings about neither newer or older versions of libusb working, not to mention, it's literally copying a binary out of a tarball and hoping it works... Without having hardware to test, I'm personally hesitant to even think about trying to package this.

**Comment by dhodyn** [comment]
I think I can help with this. Same question here: https://github.com/ublue-os/bluefin/issues/881

Can you share the output of `lsusb` and check the output? If it is one of 27c6:538c, 27c6:533c, 27c6:530c, 27c6:5840 then you are in luck.

I have a XPS 9310 that has Goodix fingerprint reader `27c6:533c Shenzhen Goodix Technology Co.,Ltd. FingerPrint` for which I have been maintaining a _personal_ Copr package hosted on: https://copr.fedorainfracloud.org/coprs/dhodyn/personal/

Github: https://github.com/dhodyn/copr/tree/master

I suspect that yours is from the same series hardware. I know the driver is used by XPS 9300 as well. And it works for me on factory silverblue installation 

## Instructions

- Download the repo into /etc/yum.repos.d

```sudo curl -o /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:dhodyn:personal.repo https://copr.fedorainfracloud.org/coprs/dhodyn/personal/repo/fedora-40/dhodyn-personal-fedora-40.repo```

- Layer the package

```rpm-ostree override remove libfprint --install=libfprint-tod --install=libfprint-2-tod1-goodix```

- Reboot the machine and enable fingerprint 

---

Hopefully, this is absorbed by ubue project. I was checking out the project and came across this question. 

---

## Longer story
- XPS 9310 had a developer edition that shipped with Ubuntu and fingerprint reader works OOTB using a closed source driver which is available to download from Ubuntu.
https://launchpad.net/libfprint-2-tod1-goodix
http://dell.archive.canonical.com/updates/pool/public/libf/libfprint-2-tod1-goodix/

- Arch also has support. In AUR, they would get the driver `so` files from Ubuntu
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=libfprint-2-tod1-xps9300-bin

- There is a dependency that you would need the `libfprint-tod` fork version of `libfprint`. This is to support Touch OEM Fingerprint readers.
https://gitlab.freedesktop.org/3v1n0/libfprint/-/blob/tod/README.tod.md

- Almost every distro ships libfprint-tod except for fedora which has only libfprint (may be Fedora policies - I don't know)
Ubuntu: https://packages.ubuntu.com/focal/libs/libfprint-2-tod1
Arch: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=libfprint-tod-git
OpenSUSE: https://build.opensuse.org/projects/openSUSE:Factory/packages/libfprint/files/libfprint.spec?expand=1
NixOS: https://search.nixos.org/packages?channel=23.11&from=0&size=50&sort=relevance&type=packages&query=fprintd-tod

- So, on my Copr I would build the libfprint-tod from source and fetch the `so` from Ubuntu repos and repackage everything as rpm


Note: Please don't rely on this Copr. It is really for _personal_ use. I don't intend to maintain this in long term.
I recommend someone should fork it as more official version or convince fedora / rpm-fusion to at least ship libfprint-tod.

**Comment by techie6** [comment]
I have a Dell XPS 15 9500 and I was able to make the integrated fingerprint reader work on Bluefin/Aurora using the driver from the following COPR repo:
https://copr.fedorainfracloud.org/coprs/manciukic/libfprint-tod-goodix

I had to layer the package for now, but I don't know if this is something that can be added by default to the main uBlue image.
