### ISSUE TITLE
Rebase silverblue, kinoite, onyx, and sericea to official images

### ISSUE THREAD

**Issue by castrojo** [ublue-os/main#363]
Lots of the stuff got punted but at least we have official quay.io/fedora images, so let's selectively switch what we can to do this. I'm assuming onyx will be up there for F39.

Huge milestone folks, this starts to line us up with images tested by Fedora QA. 
 
This is a partial fix for:

https://github.com/ublue-os/main/issues/78

@bsherman wanted to work on this so you get first dibs I guess!

**Comment by IverCoder** [comment]
So we will be working closer to upstream now? Can't wait for this to be finished ❤️

**Comment by castrojo** [comment]
Just to set expectations no one's really working on this, this would have to come from Fedora.

**Comment by castrojo** [comment]
Oh sorry, wrong one, I meant to leave this comment on the download efficiency one, someone is going to work on this. 😄

**Comment by castrojo** [comment]
This is the issue to track: https://pagure.io/pungi/pull-request/1699

**Comment by bsherman** [comment]
Note that onyx is not yet being published  here: https://quay.io/organization/fedora

So the PR for this covers Silverblue, Kinoite, and Sericea only.

https://github.com/ublue-os/main/pull/407

**Comment by bsherman** [comment]
@castrojo @EyeCantCU and I worked up a cron schedule based on the timings of official upstream images:

```
# cron adjustments

1330 config
1400 akmods (built on silverblue)
1500 main
1530 nvidia
1530 framework
1540 surface, asus
1610 surface-nvidia, asus-nvidia
1645 bazzite/bluefin/beyond
```
