### ISSUE TITLE
Proposal: reduce the scope of ublue-os/main images

### ISSUE THREAD

**Issue by bsherman** [ublue-os/main#369]
## Summary
Revise scope of [Universal Blue Main Images](https://universal-blue.org/scope/#main-images) such that kmods (and associated kernel packages) are no longer included.

## Description
The purpose of this change is to streamline build processes(current and future), maximize use of `*-main` images as a foundation for downstream efforts, and enable maximal flexibility for users running these images.

The primary change removes the following packages from `*-main` images:
  - kernel-devel-matched
  - kmods
      - xpadneo
      - xpad-noone
      - xone
      - openrazer
      - v4l2loopback
      - wl

## Scope of Changes
- Main (repo)
    - Remove above packages from `*-main` builds
    - Stop building `*-nokmods` as those images will be identical to `*-main` after this change
- ASUS/Surface
    - Build directly from `*-main`
- Website
    - Clarify that `*-main` images should not include kmods, kernel-devel, kernel-tools packages
    - Emphasize that `*-main` may be used directly but is primarily a foundational part of the Universal Blue toolkit.
    - Better document use of `akmods`.
    - Announcement of change on Blog/Github/Discord

### Not in scope
- Removal of `*-nvidia` images: they MUST have the nvidia kmod, so that will stay (still based on `*-main` so will lose the other kmods)

## Benefits to Universal Blue
- **Reduce complexity of builds and number of images maintained**
- **Provide a single foundational image for all downstream Universal Blue images/users**
- Prevent artificial restrictions on downstream usage *(kernel specific packages installed in `*-main` cannot be removed downstream or on a running system which prevents use as a base for images like asus/surface, any changes to kernel, as well as layering of related packages on running systems)*

## Feedback
A conversation in [discord](https://discord.com/channels/1072614816579063828/1072617059265032342/1155886903304925185) was had about narrowing the scope of our `*-main` images such that they no longer include kmods. 

There were questions about impact to users of existing `*-main` images, the primary concern being removal of `xpadneo` and `v4l2loopback` as they are the two kmods which have existed for a longer time. 

It was suggested we suggest users use `*-nokmods` images if they have issues with kmods in `*-main`, but that does not address the desire to simplify build processes within the Universal Blue organization.

### Ways to address 
We can suggest use of bazzite, bazzite-gnome or bluefin for users not wishing to build a custom image.

In the future, to partially offset the impact of these changes, `just` scripts may be implemented that simplify the installation of the kmods Universal Blue provides.

## Timeline

To minimize the impact on current users of our `*-main` images, these changes will go into effect with Fedora 39. Fedora 37 and 38 will continue to provide the `*-nokmods` images until their EOL in November and next May. Starting with Fedora 39, `*-main` images would exclude all kmods, focusing only on refinements to the base images.

## Other Thoughts

Hardware enablement has long been included in the [scope of main images](https://universal-blue.org/scope/#main-images), but it was initially focused on the addition of udev rules, not the addition of kmods; those came later.

As of this writing, we have recently created `*-nokmods` because `*-main`'s inclusion of a few kmods prevented it from being used as an upstream foundation for some downstreams needing a kernel swap, specifically `*-asus` and `*-surface` images. 

Additionally, we recently discovered that that this [longstanding bug](https://github.com/ublue-os/main/issues/85) was actually caused by the installation of kmods(and/or kernel-devel packages) in `*-main` images themselves.

These recent changes/discoveries and the increasing burden of managing image hierarchy are the primary motivators for narrowing the focus and "ripping the band-aid off" now, before things have a chance to become more complex.

## Addendum

Impact of removing the kmods from main would be:
1. If a user is relying on such kmods upon an upgrade some their hardware may not work (rare) and additionally v4l2loopback will not be available for software that uses it to create virtual cameras (like OBS)

Impact of not doing this change is that:

1. Users who want to use main images but would rely on local akmod layering cannot easily use ublue as their locally layering will not work
2. Users who are using main images as base for their custom images will also have to add the kmods back if they want them or have the same behaviour as above
3. Users who want to create their own image with main as base but who also rely on kmods or custom kernels will be able to more easily set that up (currently they’d have to use the nokmods image as a workaround)

Above from @akdev1l : https://github.com/orgs/ublue-os/discussions/224#discussioncomment-7104856

## Authors
- @bsherman 
- @EyeCantCU 

Edits:
1. added Addendum with notes from @akdev1l 
2. added Timeline per discussion with @EyeCantCU 
3. removed "kernel-tools" from list of packages removed

**Comment by bsherman** [comment]
FYI @ublue-os/approver 

@EyeCantCU discussed and realized we did not specify timeline in this proposal. As such, I've added a timeline section clarifying this change will be for Fedora 39 forward. We'll maintain existing setup for Fedora 37 and 38.

**Comment by castrojo** [comment]
Just to account for the bot missing this, I initially +0'ed and then changed it to +1 so that might be why I'm non-binding. So just leaving a comment for the record.

**Comment by bsherman** [comment]
@EyeCantCU will tag team on the implementation for this. 

I'd like to have a number of PR's staged so we can roll out cleanly.

**Comment by EyeCantCU** [comment]
> @EyeCantCU will tag team on the implementation for this. 
> 
> I'd like to have a number of PR's staged so we can roll out cleanly.

Sounds great! Happy to get to work on this

**Comment by bsherman** [comment]
Another edit:

I discovered that `kernel-tools` is meant to be on all `*-main` images, even those which don't have kmods, so that has been corrected.

**Comment by bsherman** [comment]
With the merging of https://github.com/ublue-os/main/pull/375 (and https://github.com/ublue-os/main/pull/390) ... the bulk of the work for this proposal has been completed.

`main` now does what was proposed. @EyeCantCU and I also reviewed the `nvidia` repo and believe it will "just work" as we'd anticipated.

**Comment by bsherman** [comment]
Website was also updated to add info about this to the [`main` image section](https://universal-blue.org/images/main/#Features)

**Comment by bsherman** [comment]
And... ASUS has had an update for this: https://github.com/ublue-os/asus/pull/14

**Comment by castrojo** [comment]
Anything left to do or can we close this out?

**Comment by bsherman** [comment]
@EyeCantCU I think the last things related to this were Asus and Surface builds, which you got wrapped up, right?

**Comment by castrojo** [comment]
Ok @EyeCantCU says this is all done, what's the next step?

**Comment by EyeCantCU** [comment]
I believe this is all wrapped up :)

**Comment by bsherman** [comment]
I'm closing it. :-)
