### ISSUE TITLE
Report an issue with an ISO - ../../grub-core/commands/efi.tpm.c:150:unknown  TPM error in Grub 2.06

### ISSUE THREAD

**Issue by RobertsGhostBusterFan** [ublue-os/main#379]
### What happened?

A bug happened!

in grub 2.06 message saying  ../../grub-core/commands/efi.tpm.c:150:unknown  TPM error.  - reads this twice then says press any key then returns to the grub selection menu,

 I been able to start it if I put secure boot into setup, I didn't try disabling secure boot yet for it  even the Troubleshooting loads this error then returns I tried  universalblue-38-x86_64-20230816 from my USB drive, works fine on my older gigabyte desktop but not this laptop, Fedora-Silverblue-ostree-x86_64-38-1.6 and Fedora-Silverblue-ostree-x86_64-39_Beta-1.1 installs fine with secure boot turned on, so I know this laptop can bootup and use Fedora linux. I done so and loaded both the beta and the stable version , for example the touchpad for the mouse buttons works a lot better in Fedora 39 then 38 on this laptop, otherwise I did have to plug in a mouse for fedora 38. also I used the workstation versions too and kde spin on my desktop but not the laptop, I do prefer gnome on my laptop for whatever reason.

this happens only on my laptop which is ASUS Republic of Gamers laptop model is GL702V also on right side says GL702VS-BI7N** two numbers I think this is a build or something info below the barcode, I have been able to boot and install ubuntu, debian 12 versions of linux, unlike fedora there are some things display in the kernel on them that seem to be missing but fedora kernel doesn't show the missing things otherwise linux can be used on this laptop, that supports windows 10 but windows 11 is not offically supported because its processor is not exactly compatable with the newer builds of windows. I don't have any output logs just the text I seen I post that in the log box.

### Relevant log output

from grub version 2.06 in  universalblue-38-x86_64-20230816.iso used Fedora Media Writer to write to usb drive on  ASUS Republic of Gamers laptop model is GL702V (GL702VS-BI7N**) model laptop notebook Pc. has NVidia 3D card hardware in this laptop only.

this error the 3 of them are what happens if secure boot is enabled and turned on this laptop.
```shell

error: ../../grub-core/commands/efi.tpm.c:150:unknown  TPM error.. 
error: ../../grub-core/commands/efi.tpm.c:150:unknown  TPM error.. 
error: ../../grub-core/commands/efi.tpm.c:150:unknown  TPM error.. 

Press any key to continue...
```

if you disable secure boot, the  universalblue-38-x86_64-20230816.iso only goes as far as 
tried install ublue-os/bluefin -->
install bluefin-nvidia:38 (bluefin for Nvidia) --> used in basic graphics mode and also does the same thing for normal graphics mode I tested out both with secure boot disabled.

in the linux kernel the gets this error stopping problem below

```shell
[ok] Started multipathd.service - Device-Mapper Multipath Device Controller
[OK] Finished dracut-pre-pivot.service - dracut pre-pivot and cleanup hook.  -- this line the laptop stops at
```

-- note shows more if you press alt-control-del to reboot in the kernel otherwise it just stops at the above text line.

that with nvidia and safe graphics mode. which worked fine when I used it on my gigabyte desktop, but seems to stall and freeze at the above text right after [ok] Started multipathd.service - Device-Mapper Multipath Device Controller, again it only shows the kernel and its startup if you disable secure boot on this laptop otherwise it gets the above TPM error from this laptop, again which I been able to install even fedora 39 beta on it from their website, I hope this information helps the next iso images get fixes if it needs a fix for this problem, I think I could also use rpm-ostree commands to add this on top of Fedora 38 or Fedora 39 on a install on the laptop but I don't know if it would be stable on this laptop of have startup problems like this ISO image has for me on this one device. 

seems to stop at that line and it doesn't go any far-er than that, USB drive is not accessing no light on it curretnly its like it gets stuck there, again I been able to bootup the normal fedora images and install them so I am guessing some are some bugs in this iso image that are preventing me from installing this version, I might be able to add this from silverblue or kinoite but not this iso image on this device.

**Comment by ThinkSalat** [comment]
I'm getting this same thing on an asrock z790 pg-itx motherboard with secure boot both enabled and disabled. installed iso from releases using fedora media writer, booted from uefi: usb.

**Comment by m2Giles** [comment]
This is still continuing.

Workaround right now for me is to drop to grub command line and ```rmmod tpm ```

This is a hacky workaround and I've only ever experienced these tpm issues with massive nested grub menus.

**Comment by htgar** [comment]
Alternatively, for a more graphical solution, if your motherboard supports it, you can disable tpm in the bios before installing the OS, and re-enable it after.

**Comment by raqbit** [comment]
I'm hitting this while trying to load the installer of Ublue on my XPS 15 9500. The message is printed (repeatedly) for every option selected in grub.

The official Fedora Silverblue installer image loads fine.

**Comment by m2Giles** [comment]
Drop to grub command line.

`rmmod tpm`

Return to menu and select your option. The grub tpm module has issues with heavily nested menus
