### ISSUE TITLE
Should we make lxqt-main and mate-main?

### ISSUE THREAD

**Issue by castrojo** [ublue-os/main#38]
Right now we're making LXQt and MATE images but they're directly from the ostree builds and not derived from main. I was wondering if we should add (not replace) -main variants? 

Personally I think we should make these so people who use those desktops can enjoy the QoL of -main, but they're not derived from Fedora so we should probably just say that.

I think it'd be useful to make them so people can try it, and then if there's interest we can help onramp them to Fedora to make an official build if there's interest.

**Comment by EinoHR** [comment]
I think yea. Would that be a -main images based on LXQt and MATE, or LXQt and MATE images based on base-main?

**Comment by hyperreal64** [comment]
I agree, we should make lxqt-main and mate-main.

**Comment by castrojo** [comment]
Woo! One more bug slain!
