### ISSUE TITLE
ISO: Kinoite install failed, no verification

### ISSUE THREAD

**Issue by trytomakeyouprivate** [ublue-os/main#386]
### What happened?

```
rpm-ostree deploy failed, no signature verification
```

Something like this. I got the same issue when trying to install regular Kinoite.

I installed from a normally flashed USB stick, as ventoy indeed did not work.

No logs yet, but I can say I removed some former Linux partitions, and have Windows, including boot entries coinstalled.

### Relevant log output

```shell
Please attach or paste the logs from the Anaconda Installer https://docs.fedoraproject.org/en-US/quick-docs/anaconda/anaconda_logging/
```

**Comment by trytomakeyouprivate** [comment]
I also seem to not be able to get any logs, as after closing the popup error window, it shuts down the installer

**Comment by cig0** [comment]
Hey @trytomakeyouprivate, I came here to report another issue related to `kinoite-main` and found your post.

I can't reproduce your issue using the Atomic Kinoite or Universal Blue 2.0 ISO image. Have you tried with a recent image to check if the problem persists for you or if it's gone?

**Comment by castrojo** [comment]
Hi there,

This issue was filed on old ISOs. We have a new ISO generation tool, check here for download instructions: 

https://universal-blue.org/installation/

The new ISOs use a more reliable method of creation and should work much better, thanks!
