### ISSUE TITLE
A Matrix room for Discussions?

### ISSUE THREAD

**Issue by trytomakeyouprivate** [ublue-os/main#388]
Matrix / Element are better than Discord in many ways.
- work throug the browser
- decentralized, federated
- No weird proprietary clients needed
- Secure and encrypted if wanted
- Permission system etc 

I guess many features are similar or en-par with Discord, but its opensource, secure, federated and encrypted. Not the best chat possible, but probably the best currently existing.

An inofficial Element room would be great. I would start one, invite people and see how things go!

A bridge from and to Discord could be a goal in the future, but that has to run somewhere, would not be crucial.

For me currently there is no normal way to communicate with you all, and I think many people are in the same situation!

What do you think?

**Comment by trytomakeyouprivate** [comment]
another question, should we ask to use the Fedora servers? Would this be impossible, not wanted etc?

It is chat.fedoraproject.org

**Comment by castrojo** [comment]
We're not going to set up a bridge but if you want to do this with others just make sure we have quorum from enough people interested.

**Comment by trytomakeyouprivate** [comment]
[I created a Matrix space! Feel free to join, everyone viewing this](https://matrix.to/#/#universal-blue:matrix.org)

I would just keep it as a seperate communication medium?

**Comment by nicknamenamenick** [comment]
I have seen on Mastodon and elsewhere that some users would prefer to have a chat outside of Discord.  I'm not sure if the maintainers use Matrix themselves, and if they are missing then support might not be that good in comparison to Discord.

Here's all of the text channels on Discord to get parity with the Matrix room:

![Discord images](https://github.com/ublue-os/main/assets/121328689/9a11525e-61d8-448a-9a13-b9c4c5ab510f)

**Comment by bigpod98** [comment]
I dont really use matrix personally i fimd it kludgy

**Comment by castrojo** [comment]
Alright looks like this is done, closing this.
