### ISSUE TITLE
Add python3-icoextract for other DE's

### ISSUE THREAD

**Issue by fiftydinar** [ublue-os/main#399]
### Describe the package

It's like icoutils for KDE. Allows support for .exe files thumbnailing. Recently added in Bazzite.

Supports Gnome, MATE, Cinnamon & XFCE.
LxQT support needs to be tested.

### Information on the package

python3-icoextract-0.1.4-4.fc38.noarch.rpm
python3-icoextract-0.1.4-6.fc39.noarch.rpm
Download size: 30.96 KB
Installed size: 47.53 KB

### Image

Silverblue,
Vauxite,
MATE,
Cinnamon

**Comment by KyleGospo** [comment]
Also need to manually add one file for it to work, upstream doesn't ship the thumbnailer definition

**Comment by castrojo** [comment]
This doesn't need to be in main
