### ISSUE TITLE
Revert kate integration over kwrite in Kinoite

### ISSUE THREAD

**Issue by GarciaLnk** [ublue-os/main#400]
### Describe the package

The inclusion of `kate` over `kwrite` is an opinionated decision that diverges from upstream. KWrite serves as a simpler text editor without extra features that are targeted only to developers.

#257 argues that Kate "would be more useful for ublue-os demographics", but I don't see how the target demographics of ublue main images should be different from Kinoite's. Therefore, the decision of including one package over another should be, in any case, from Kinoite (or a downstream fork).

### Information on the package

```
Name         : kwrite
Version      : 23.08.1
Release      : 1.fc38
Architecture : x86_64
Size         : 253 k
Source       : kate-23.08.1-1.fc38.src.rpm
Repository   : @System
From repo    : updates
Summary      : Text Editor
URL          : https://apps.kde.org/kate/
License      : LGPLv2+
Description  : Text Editor.
```

### Image

Kinoite

**Comment by castrojo** [comment]
We don't appear to be explicitly excluding kwrite, from reading #257 and looking at the list kate is additive.

**Comment by castrojo** [comment]
Oh, I found it, ok +1 from me on this one. Ideally we'd want to not include kate on the image but I'm also not finding it on flathub and it'd suck to remove it without a discussion.
