### ISSUE TITLE
Obexd not starting with --symlink breaks bluetooth file transfer

### ISSUE THREAD

**Issue by marinmo** [ublue-os/main#402]
Hello,

I'm using startingpoint as a base for my own image, however this error might be applicable to ublue itself too; however I've only recreated it with my own image.

The problem is that obexd can't handle symlinks without additional arguments. In startingpoint, $HOME is set to /home/$USER which is then symlinked to /var/home/$USER. As described, and experienced by myself just now, in https://discussion.fedoraproject.org/t/cannot-receive-file-over-bluetooth/1813/5 this breaks obexd which then creates the termporary file for the transfer in $HOME/.cache/obexd/ but then throws an error (e.g. Oct 27 13:00:15 computername obexd[3022]: open(/home/marinmo/.cache/obexd/RTJCD2): Operation not permitted (1)).

Solution as described above is either to set $HOME to /var/home/$USER or create an override as such;
```
[Service]
ExecStart=
ExecStart=/usr/libexec/bluetooth/obexd --symlinks
```
(if on an existing installation, systemctl --user daemon-reload && systemctl --user restart obex is also needed)

Thanks for your consideration!

**Comment by marinmo** [comment]
Thank you for moving to the appropriate repo.

For the record, I previously installed Silverblue (somewhere in 2022) and then rebased to ublue. This issue did not occur on that installation, but as I recently reinstalled and used install media created with startingpoint I happened upon it. It therefore seems to me that this is fixed in Silverblue, probably due to $HOME being set to /var/home/$USER

**Comment by marinmo** [comment]
This issue doesn't seem to garner a lot of attention :)

I'm thinking the best way to solve this would be to add an override to the obexd systemd service file. The service only starts at a user, not on a system level. It seems to me, from my brief research, that this file would be located here:
https://github.com/ublue-os/config/tree/main/files/usr/lib/systemd/user
adding a obex.service.d directory and an override.conf in it with the contents in the first post.

I could create a PR for this, however I'm not super familiar with how the ublue image is built so I'd be happy for someone to confirm the above being the correct solution before I go ahead.

Thanks in advance!

**Comment by marinmo** [comment]
Hello,

This issue has been stale for almost 6 months now. Would there be any issue with pointing $HOME to /var/home/$USER or implementing the fix suggested in the original report?

**Comment by castrojo** [comment]
This seems like a Fedora issue and not a ublue one?

**Comment by marinmo** [comment]
Hello,

I just installed silverblue to a VM to make sure. The difference is this:
```
marinmo-vm@fedora:~$ echo $HOME
/var/home/marinmo-vm
```
versus
```
marinmo@fedora ~> echo $HOME
/home/marinmo
```

The former is a clean Silverblue 39 installation, the latter is an uBlue startingpoint image, installed/first generated around september 2023. Ie, the Silverblue image sets $HOME to the actual path of where the home directory is located, while uBlue sets it to where home usually resides which is then symlinked to the actual path, which breaks obexd as described. Thus not a Fedora bug!

**Comment by marinmo** [comment]
I tried installing Bluefin (38, latest) to a VM, which showed expected behavior ($HOME is set to /var/home/$USER) so depending on which image will be the main one going forward, this might be fixed since ... Sometime? :)
