### ISSUE TITLE
Rebasing from Silverblue fails

### ISSUE THREAD

**Issue by KibSquib48** [ublue-os/main#403]
I'm on Fedora Silverblue 38 trying to rebase to ublue silverblue-framework but when I follow the rebasing to unsigned image step on https://universal-blue.org/images/ I get this error:
`error: Creating importer: Failed to invoke skopeo proxy method OpenImage: remote error: A signature was required, but no signature exists`

Output of `rpm-ostree status`:
```
State: idle
Deployments:
● fedora:fedora/38/x86_64/silverblue
                  Version: 38.20231027.0 (2023-10-27T00:53:29Z)
                   Commit: 9956bd0c9569fd6a536d8d942246451405f6a707da4e8e889c23f9ab24e82b6d
             GPGSignature: Valid signature by 6A51BBABBA3D5467B6171221809A8D7CEB10B464

  fedora:fedora/38/x86_64/silverblue
                  Version: 38.20231027.0 (2023-10-27T00:53:29Z)
               BaseCommit: 9956bd0c9569fd6a536d8d942246451405f6a707da4e8e889c23f9ab24e82b6d
             GPGSignature: Valid signature by 6A51BBABBA3D5467B6171221809A8D7CEB10B464
          LayeredPackages: langpacks-en
                   Pinned: yes
```

Output of `rpm-ostree rebase ostree-unverified-registry:ghcr.io/ublue-os/silverblue-framework`:
```
Pulling manifest: ostree-unverified-registry:ghcr.io/ublue-os/silverblue-framework
error: Creating importer: Failed to invoke skopeo proxy method OpenImage: remote error: A signature was required, but no signature exists
```

**Comment by hanscees** [comment]
I am trying to do the same thing. 
In my case I copied the command from blue in, but this fails in a different way

https://universal-blue.org/images/bluefin/

`sudo rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bluefin:38`

gives error : Fetchong manifest: containers-policy.json specifies a default of insecureAcceptAnything refusing image

**Comment by camaz** [comment]
I'm having the same issue attempting to rebase from Fedora Silverblue 39:

`sudo rpm-ostree rebase ostree-unverified-registry:ghcr.io/ublue-os/silverblue-nvidia:39`
fails with:
`error: Creating importer: Failed to invoke skopeo proxy method OpenImage: remote error: A signature was required, but no signature exists`
