### ISSUE TITLE
Can't boot into unsigned image

### ISSUE THREAD

**Issue by gregorni** [ublue-os/main#404]
I tried rebasing from Fedora Silverblue 39 beta onto the `silverblue-main` image following the instructions in the  [wiki](https://universal-blue.org/images/). However, after rebasing onto the unsigned image, the system boot into emergency mode and gets stuck there:

![IMG_20231028_154640_DRO](https://github.com/ublue-os/main/assets/119804311/9d26b500-dc24-4df3-82ae-d28d258b4a53)

**Comment by trytomakeyouprivate** [comment]
Do you have UEFI enabled? Disable it to be sure, this could be a proble,

**Comment by gregorni** [comment]
No, that doesn't do it: If I disable UEFI support, the BIOS doesn't even recognize my hard drive as a boot disk.

**Comment by trytomakeyouprivate** [comment]
yeah that totally sounds like UEFI crap to me. I had a very similar case.

Go into your BIOS ans search for things like "legacy first" or "compatibility mode". Once I did that my laptop finally showed real devices instead of Secureboot entries

**Comment by gregorni** [comment]
So it started working randomly after I updated some packages. Also, Fedora 39 is stable now, no idea if that has anything to do with it.
