### ISSUE TITLE
Proposal: Increase number of Pull Request approvers

### ISSUE THREAD

**Issue by bsherman** [ublue-os/main#411]
## Summary
Increase the number of approvals required for Pull Requests from 1 to 2 on `config`, `akmods`, `main` and `nvidia` repos.

## Description
As Universal Blue becomes more popular and its core images become more stable, it seems desirable to have more eyes on changes. Each change is potentially more impactful and it's been not uncommon for changes to pass through very quickly without opportunity for feedback. This MAY slow down change but will HOPEFULLY increase awareness of changes among approvers.

**Comment by bsherman** [comment]
@ublue-os/approver please read and give any feedback. We can enact the formal voting process later if appropriate, but I think it helpful to have the opportunity to discuss first.

**Comment by EyeCantCU** [comment]
I like this idea. Having more eyes on things coming into core repositories would be nice and I think we certainly have enough people here to do this effectively without it causing disruption

**Comment by castrojo** [comment]
Strong +1, let's tighten it up as we mature!

**Comment by KyleGospo** [comment]
+1

**Comment by p5** [comment]
+1

**Comment by castrojo** [comment]
Ok let's give it the full 72h and then turn it on.

**Comment by bigpod98** [comment]
+1

**Comment by fiftydinar** [comment]
+1

**Comment by castrojo** [comment]
This is now set to 2.
