### ISSUE TITLE
Creating a move-to-UBlue script?

### ISSUE THREAD

**Issue by trytomakeyouprivate** [ublue-os/main#412]
Rebasing to ublue images is already pretty easy. But what if it was fully automated?

Example:

I am on Fedora Kinoite and have the packages `kate fish /home/user/RPMs/some-random-RPM.rpm` layered and the package `kwrite` removed. Now when moving to ublue, those overrides and layers would be gone, and it would be somewhat of a headache to build the command like:

```
rpm-ostree rebase ostree-unverified-registry:ghcr.io/ublue-os/kinoite-main:38  && rpm-ostree override remove kwrite --install A --install B --install C
```

There are some problems here: 1. That command f**ing sucks 2. You cant do an override-remove as a second argument for some reason, at least I think so 3. The packages may not need to be changed, as ublue uses kate instead of kwrite for example. Having those repalacements sit there spams the "rpm-ostree update" in my experience with "Package already provided" etc.

So why not automate this? It would be a really great improvement.

1. Get the users OS version and desktop
2. let them decide what version (main, nokmods, asus, framework, surface, asahi?)
3. detect if they use nvidia
4. Then I would say easiest would be to somehow read the rpm-ostree changes (layers, overrides) they did, and in that script hardcode packages ublue already changes, so they should be skipped. 
5. Build the command for the unsigned image, add the signed image rebase command to run automatically after reboot

Questions:
- what do you think of this?
- do you think this is useful, or is the new fancy web installer already "chosen"?
- how should package changes be dealt with?
- how do you detect the path of locally installed RPMs? Or should that be entered manually?
- how would you implement such a reboot autostart? would you need the user layering twice?
- would you wait for this until direct rebasing to signed works?

**Comment by dnkmmr69420** [comment]
I like this idea

**Comment by castrojo** [comment]
This is pretty out of scope for us, unless someone wants to work on this outside the org.
