### ISSUE TITLE
Cannot update: error: No installed package matches 'kwrite'

### ISSUE THREAD

**Issue by firefoxlover** [ublue-os/main#414]
I have "rpm-ostree override remove kwrite" sitting there, as it was installed on regular Kinoite.

Now I switched to ublue Kinoite and rebasing to 39 worked fine.

But updating doesnt work anymore?

Is there a command to reset a single override? Currently this blocks updates.

**Comment by castrojo** [comment]
We can't answer this question without an `rpm-ostree status`, thanks!

**Comment by firefoxlover** [comment]
This was a previous version a week old or so. I had an `rpm-ostree override remove kwrite` pending.

I solved it by resetting and relayerind my packages, a rough method that I would like to solve.

The issue here: how do I remove a removal? How do I reset a single change of the deployment?

**Comment by castrojo** [comment]
Can't answer the question without an `rpm-ostree status`.
