### ISSUE TITLE
Will not install, get error

### ISSUE THREAD

**Issue by wilburns5** [ublue-os/main#418]
### What happened?

I get this error ,  I also get this on any fedora I try to install
I am running Windows, Opensuse and Centos on this PC without any problem.
So how do I fix this?

Thank You

![20231108_165414](https://github.com/ublue-os/main/assets/121656086/0406615a-7be5-457c-ac02-0ed9188e9013)

### Relevant log output

```shell
Please attach or paste the logs from the Anaconda Installer https://docs.fedoraproject.org/en-US/quick-docs/anaconda/anaconda_logging/
```

**Comment by ctpforr** [comment]
I had the exact problem attempting to install from ublue, both silverblue and the cinnamon option.   

It just occurred to me that perhaps it's because I did not configure my network (wifi only).   I have not had a chance to verify that this is the case.

**Comment by castrojo** [comment]
Yeah this is in the install docs: https://universal-blue.org/installation

Although sometimes it might show you that anyway. Try it with a solid connection and see if it keeps failing.

**Comment by ctpforr** [comment]
I should have known better - however, the installation screen does let you proceed without a network connection, unlike the other things like destination, keyboard, etc.    I remember thinking, "I don't need to set up my complicated connection, just let it do dhcp!", forgetting that I was on a wifi-only box!

**Comment by wilburns5** [comment]
I had tried to install the 1.9  the 1.10 and the 2.0 ISO, I was connected to the internet with all 3 got the same error.

**Comment by wilburns5** [comment]
Plus I had tried to install other Fedoras ISO and get the same error

**Comment by wilburns5** [comment]
and I'am running Opensuse and centos now

**Comment by castrojo** [comment]
Hi there,

This issue was filed on old ISOs. We have a new ISO generation tool, check here for download instructions: 

https://universal-blue.org/installation/

The new ISOs use a more reliable method of creation and should work much better, thanks!
