### ISSUE TITLE
Blank screen after andaconda tries to start

### ISSUE THREAD

**Issue by matteodev8** [ublue-os/main#419]
### What happened?

After anaconda tries to start, I am left with a blank screen and a static text cursor in the top left

I tried with secure boot and without secure boot, both are stuck on this, tried switching tty, still doesn't work

(I also get a GRUB TPM error when having tpm enabled)

CPU: Intel Core i7-9700
GPU: RTX 3060
MB: Aorus Z390 Pro WiFi

**Comment by htgar** [comment]
I ran into this issue, but it was solved after I reflashed the drive.

For the TPM issue, you'd have to disable your TPM in the bios. You can re-enable it after the OS is installed.

Hope this helps!

**Comment by EyeCantCU** [comment]
You may have better luck using the installer for Fedora Silverblue, found [here](https://fedoraproject.org/silverblue/download).

After installing Silverblue, you can rebase to any Universal Blue image you'd like by running:

```bash
rpm-ostree rebase ostree-unverified-registry:ghcr.io/ublue-os/<IMAGE NAME HERE>:latest
```

Then reboot. Following the reboot, you can rebase to a signed image:

```bash
rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/<IMAGE NAME HERE>:latest
```

**Comment by castrojo** [comment]
Hi there,

This issue was filed on old ISOs. We have a new ISO generation tool, check here for download instructions: 

https://universal-blue.org/installation/

The new ISOs use a more reliable method of creation and should work much better, thanks!
