### ISSUE TITLE
Rebasing from base-main without DE to Bazzite doesn't set the default target to graphical

### ISSUE THREAD

**Issue by manan-gup** [ublue-os/main#423]
### What happened?

Hi, I had a USB with the ublue ISO flashed but wanted to install Bazzite. So, I decided to install the version without a DE and then rebase to Bazzite.

First, as mention in this issue, #187, the base image boots to a black screen and requires the user to switch to a different tty without any visual indication for doing so.

Second, after I rebased to Bazzite and rebooted the machine I was again booted into a tty environment. The rebasing doesn't change the default systemd target from multi-user to graphical. You have to run `sudo systemctl set-default graphical.target` and then reboot again.

Third, the new initramfs is only built on the first boot after rebasing, so, you have to reboot twice anyway. I'm not sure if this is a bug or something that can't be overcome at the moment.

**Comment by EyeCantCU** [comment]
Hello. Thanks for reporting this. Opened a PR over in Bazzite to get this addressed
