### ISSUE TITLE
feat: Abillity to reset `/etc`

### ISSUE THREAD

**Issue by dnkmmr69420** [ublue-os/main#427]
There really needs to be a way to reset `/etc` to the default (except for a few files like fstab, passwd, and shadow). A good way to detect what needs to be reset is using the command `sudo ostree admin config-diff` which lists what has been deleted, modified, or added to `/etc`. The reset function should make a new deployment with the reset `/etc`. There could be a bash script or possibly a python script that does the function called `reset-etc` in `/usr/sbin` which needs to be ran by `sudo`. It could also be activated by `ujust reset-etc` which would run `sudo reset-etc`.

**Comment by castrojo** [comment]
This looks like: https://github.com/ublue-os/main/issues/95
