### ISSUE TITLE
Feat: include neowofetch for all ublue images

### ISSUE THREAD

**Issue by dnkmmr69420** [ublue-os/main#428]
We should start including hyfetch along with neowofetch in all images. Right now it is only included in Bazzite and that's it. If it is included in all images, bluefin, main. main-nvidia, ucore server, can have neowofetch along with bazzite. It may even be a good idea to have neowofetch use the ublue logo for the main variants ans the bluefin logo for bluefin.

**Comment by castrojo** [comment]
This is way out of scope: https://universal-blue.org/scope/?h=scope#main-images
