### ISSUE TITLE
The kinoite-39 image rpmfusion packages frequently lag behind by 1week+

### ISSUE THREAD

**Issue by qoijjj** [ublue-os/main#431]
Up until today, kinoite-39-nokmods was pulling in ffmpeg version 6.0-16 while the base image and silverblue image were pulling in ffmpeg 6.0.1-2:
https://github.com/ublue-os/main/actions/runs/6945636372/job/18895477669
https://github.com/ublue-os/main/actions/runs/6945636372/job/18895482286

This should not be the case, as if a new version is available in rpmfusion, they should all pull it in.

**Comment by bobslept** [comment]
The builds got returned a different mirror from mirrors.rpmfusion.org.

https://github.com/ublue-os/main/actions/runs/6945636372/job/18895477669#step:8:251
https://github.com/ublue-os/main/actions/runs/6945636372/job/18895482286#step:8:251

So probably the one mirror updates faster then the other mirror.

**Comment by qoijjj** [comment]
> The builds got returned a different mirror from mirrors.rpmfusion.org.
> 
> https://github.com/ublue-os/main/actions/runs/6945636372/job/18895477669#step:8:251 https://github.com/ublue-os/main/actions/runs/6945636372/job/18895482286#step:8:251
> 
> So probably the one mirror updates faster then the other mirror.

Makes sense. It would be good to ensure that, not necessarily all of the builds use the same mirror, but that they're all reasonably up to date. a day or so of lag is one thing, but if a mirror is a week+ lagging, we should detect it and not use it for that build.

I can think of a few ways to do this but most of them would involve some kind of check to compare a handful of rpmfusion packages between builds and use a different mirror for the ones that return an older version. Or if there's a way to automatically find out what the most up to date version of a package is across mirrors, that could work too.

**Comment by bobslept** [comment]
This is strange, not sure why but I noticed the  ser
https://github.com/ublue-os/main/actions/runs/6945636372/job/18895479268#step:8:251

**Comment by EyeCantCU** [comment]
> Maybe we can try to do a `rpm-ostree refresh-md --force` or something. I'm not sure, maybe someone else has better understanding why this could happen.

This is worth a shot. Wouldn't know why it's getting cached myself

**Comment by bobslept** [comment]
That generation date is corresponding with the timestamp found in the metafile generated by `https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-released-39&arch=x86_64`. If I'm correct, that is where my `rpmfusion-free-updates.repo` points to. 

So the caching would be somewhere in the infra. Don't think a hard resfresh would solve it, as they are already non cached variants. If it was in rpm-md cache it should have a "(Cached)" on that line.

**Comment by bobslept** [comment]
After seeing arrive another update on ffmpeg today, it all seems to be working fine after all. 

@qoijjj can we close this issue?

**Comment by qoijjj** [comment]
@bobslept Yes that's fine. Although it's all but guaranteed to happen again at some point.
