### ISSUE TITLE
Firefox stuck at 118.0.1

### ISSUE THREAD

**Issue by firefoxlover** [ublue-os/main#433]
### What happened?

I am using kinoite-nokmods:39 and for some reason my Firefox is still at version 118.0.1?

https://packages.fedoraproject.org/pkgs/firefox/firefox/

It should be at 120??

Is this because nokmods is now main? Do I need to rebase? Didnt I get updates since f39 ?

**Comment by firefoxlover** [comment]
ok guys this is a huge problem!

`kinoite-nokmods` had a F39 version for some reason but not a single update after that.

There has to be some way to inform uses of that, as I didnt get any updates for some reason, not even sure if the F39 was "real"?

Rebasing to `kinoite-main` fixed this and I am not on an updated system

**Comment by castrojo** [comment]
Yeah you seem to have been on an old beta image, you should be on kinoite-main moving forward.

**Comment by firefoxlover** [comment]
yes and this is a problem. For at least one version or so it looked like `-nokmods` is the right image to use. Then you decided to drop the kmods from main.

But everyone that uses `-nokmods` has to see that they need to rebase! Updates are done in the background, I wondered a bit but didnt really see that there where no updates.

Is there a way to see how many people are still using the nokmods image? Probably all the downloads, but not who downloaded them. This is pretty important and an automatic rebase is needed in some way
