### ISSUE TITLE
Having installed from 'bluefin-38-2023-10-27-x86_64-rc.iso' I recieve an error in Other Software

### ISSUE THREAD

**Issue by twelsh37** [ublue-os/main#434]
### What happened?

I had just completed the first installation of bluefin. It had finished the section on setting up the software.
I then went to the 'Other software'( It might be called something else but It is in the last part where you can read the documentation as well as join discourse etc.

Having gone into the software part I recieved a message stating 'Unable to install "British English" as not supported.

![image](https://github.com/ublue-os/main/assets/4956770/885fd676-45ae-4edc-ab78-65f9a6e92233)

More than happy to help troubleshoot/test this at a later stage if required.

**Comment by castrojo** [comment]
Can you go into the language settings and select british english, log out and back in, and then see if it's set correctly?

![image](https://github.com/ublue-os/main/assets/1264109/2aaa2fe1-f09f-4aaa-a795-271f46433eaf)

**Comment by twelsh37** [comment]
Just did a install on a HP laptop ( Nothing special) I ran into the same issue. but after the install I then went into settings as requested. 
Language and Formats is both set to English (United Kingdom)
Then going into software I no longer get the message.
I suppose the lesson here is not to try and install software at the initial install phase in the 'ALL Done' Section
It work perfectly after install though the Keyboard layout is still English (US) so things like the '£' above the number three key returns a '#', '@' returns a '"', and the Number two key returns an '@'
Removing the English (US) and replacing with English (UK, extended, Windows) fixed my layout.

**Comment by castrojo** [comment]
I think it's just the ususal gnome-software-not-being-awesome error.

**Comment by twelsh37** [comment]
im happy enough for this to beclosed off. As yu state it is a 'gnomeism'

**Comment by bobslept** [comment]
Alright glad you got it solved!
