### ISSUE TITLE
Add a "copr" command

### ISSUE THREAD

**Issue by trytomakeyouprivate** [ublue-os/main#435]
### Describe the package

[I wrote my own solution in bash](https://github.com/trytomakeyouprivate/COPR-command), it uses polkit so only necessary commands need elevated privileges.

[34N0 has their own one in Go](https://github.com/34N0/rpm-copr)

### Information on the package

Both simply recreate the `sudo dnf copr` command syntax and functionality. It is pretty simple, so it doesn't need to be added to rpm-ostree or something.

But adding it to rpm-ostree was what the Fedora people told me should be done. I guess in the meantime, ublue could use a solution?

### Image

All Images

**Comment by castrojo** [comment]
Yeah this should be in rpm-ostree not in ublue, repo config goes in the build step.
