### ISSUE TITLE
[Package Request] firefoxpwa - A tool to install, manage and use Progressive Web Apps (PWAs) in Mozilla Firefox 

### ISSUE THREAD

**Issue by Heus-Sueh** [ublue-os/main#439]
### Describe the package

It would be really cool if I could use web apps in Firefox, but the [extension](https://addons.mozilla.org/en-us/firefox/addon/pwas-for-firefox/) requires a [native package](https://packagecloud.io/filips/FirefoxPWA/packages/rpm_any/rpm_any/firefoxpwa-2.9.0-1.x86_64.rpm?distro_version_id=227) to be installed on the host

I created an issue in the extension author's repository so that at least the package can be included in the official repository or in copr
https://github.com/filips123/PWAsForFirefox/issues/430

### Information on the package

I don't have the package installed to provide the info

### Image

All Images

**Comment by castrojo** [comment]
Sorry this is out of scope for the main images, someone could include it in a custom image though!
