### ISSUE TITLE
Micro terminal editor

### ISSUE THREAD

**Issue by atimeofday** [ublue-os/main#44]
### Describe the package

I'd like to request the package (binary) `micro` from https://github.com/zyedidia/micro because it provides a very light-weight and user-friendly terminal editor option with "conventional" keybinds used by a majority of apps across multiple operating systems. 

It is dramatically more usable as a basic text editor than Nano, the nearly ubiquitous default which it is named as a successor to. For example, Micro uses Ctrl+C and Ctrl+V for copy and paste. Nano uses "M-6" and "^U".

Within the same singular binary, it also provides syntax highlighting for most file types and languages, text completion, and a variety of powerful configurable features. 

Personally, I would enjoy not needing to layer this anymore. If it is included via package, it should be confirmed that the package is up to date. Some package managers have an older version where, among other things, the system clipboard does not work, much like other terminal editors (in my experience).

### Image

All Images

**Comment by castrojo** [comment]
We have vi and nano, which is the usual editor couple in distros these days. This is probably custom-image/distrobox territory.

We can revisit later once we get the core stuff sorted.

**Comment by atimeofday** [comment]
Vi and nano are standard. They are not usable by ~99.5% of people. 

I agree that it's not a high priority, especially relative to core stuff, because there are other considerations of how users would be informed of the existence and usability of Micro, and because the majority of that 99.5% are not comfortable with a command line anyway.

**Comment by EinoHR** [comment]
I 100% support adding Micro, but that's only because I use it and prefer it over (n)vi(m) and nano. If uBlue wishes to exist in some beginner distro category, it would certainly be easier to tell someone to edit some file from the cli using micro than teaching them vi bindings.

**Comment by castrojo** [comment]
I'm going to out of scope this as we're not going to deviate too far from Fedora for a text editor: https://ublue.it/scope/#ublue-images-mainnvidia
