### ISSUE TITLE
Add /etc/vconsole.conf to initramfs

### ISSUE THREAD

**Issue by flexagoon** [ublue-os/main#445]
Due to an [upstream issue](https://github.com/fedora-silverblue/issue-tracker/issues/3), the disk decryption screen always uses the en-US keyboard layout, even if you selected a different one during install. The [suggested workaround](https://docs.fedoraproject.org/en-US/fedora-silverblue/installation/#known-limitations) is to run `rpm-ostree initramfs-etc --track=/etc/vconsole.conf`.

I don't know if that's possible, but it would be great if uBlue did that by default.

**Comment by bsherman** [comment]
This is a good suggestion for either https://github.com/ublue-os/bazzite or https://github.com/ublue-os/bluefin, but changing initramfs configs is probably out of scope on the `*-main` images.

@ublue-os/approver   any thoughts on this?

**Comment by EyeCantCU** [comment]
Unfortunately, I have to agree with @bsherman. While this would be a great addition to downstream images, configuring this here could be problematic in that, for example, someone may want to use a full initramfs configuration or they may not want to enable it at all - in which case they'd need to disable whatever service we add here in their installation or in their image downstream

**Comment by flexagoon** [comment]
Do you at least know if this is possible to do in my own uBlue image? I tried to do this with the `scripts` module, but the `rpm-ostree initramfs-etc` command requires a booted system

**Comment by fiftydinar** [comment]
@flexagoon You need to have initramfs-etc service which would do that stuff on system. You can check Bazzite repo, they did it in details. You can check mine too, but it's not up to date with Bazzite one due to complexity.
