### ISSUE TITLE
missing emoji font for swaybar in sericea

### ISSUE THREAD

**Issue by qoijjj** [ublue-os/main#447]
### Describe the package

I'm unsure what exact package is missing, but the disk icon on swaybar doesn't show up. The same is the case upstream. I'm guessing it's a missing proprietary font.

### Information on the package

To repro, rebase to a sericea image, observe the disk space icon is missing

### Image

Sericea

**Comment by qoijjj** [comment]
cut an upstream ticket too in case this is resolvable there: https://gitlab.com/fedora/sigs/sway/sway-config-fedora/-/issues/6

If it is, I will close this ticket.

**Comment by bsherman** [comment]
Question: the disk icon you mention, is that on the stock, pre-configured swaybar configuration?

Also, was the reproducible in upstream sericea or only in a ublue sericea?

**Comment by qoijjj** [comment]
> Question: the disk icon you mention, is that on the stock, pre-configured swaybar configuration?

Yes

> Also, was the reproducible in upstream sericea or only in a ublue sericea?

Yes, it's reproducible upstream. I cut the ticket I linked above for that reason. If it's because they can't include a proprietary font there, then I think ublue would be the right place to pull it in.

**Comment by qoijjj** [comment]
This has been fixed upstream
