### ISSUE TITLE
Add Epub thumbnails package to silverblue images 

### ISSUE THREAD

**Issue by OBC96** [ublue-os/main#449]
### Describe the package

Request the package [“gnome-epub-thumbnailer”](https://src.fedoraproject.org/rpms/gnome-epub-thumbnailer ) to be added to the silveblue images as epub files does not have thumbnails.

### Information on the package

Thumbnailers for Epub and MOBI books

### Image

Silverblue

**Comment by castrojo** [comment]
```
Name         : gnome-epub-thumbnailer
Version      : 1.7
Release      : 3.fc39
Architecture : x86_64
Size         : 28 k
Source       : gnome-epub-thumbnailer-1.7-3.fc39.src.rpm
Repository   : fedora
Summary      : Thumbnailers for EPub and MOBI books
URL          : https://git.gnome.org/browse/gnome-epub-thumbnailer
License      : GPLv2+
Description  : Thumbnailers for EPub and MOBI books
```

This seems fine to me, +1

**Comment by castrojo** [comment]
This should be working now, please reopen this if it isn't, thanks!
