### ISSUE TITLE
[Membership Request] HikariKnight

### ISSUE THREAD

**Issue by KyleGospo** [ublue-os/main#452]
As per https://universal-blue.org/membership/#member

This is to sponsor https://github.com/HikariKnight to have membership rights across the ublue org. Hikari has made numerous contributions to Bazzite in the form of fixes and features in the interest of making virtualization easier, and has expressed interest in a wider maintainer role for ublue.

I sponsor, I need one more person from https://github.com/orgs/ublue-os/teams/approver to +1 this nomination and then we'll add them to the team!

**Comment by EyeCantCU** [comment]
They've made several valuable contributions to the project. Definite +1!

**Comment by castrojo** [comment]
https://github.com/ublue-os/bazzite/pulls?q=author%3AHikariKnight+

List of PRs, ok, that's the +1 we needed! Let's see if there are other comments and I'll action on this tomorrow.

**Comment by castrojo** [comment]
Done, check your inbox, welcome to the team!
