### ISSUE TITLE
Universal Blue Sericea distrobox permission errors

### ISSUE THREAD

**Issue by brandflake11** [ublue-os/main#453]
### What happened?

Hello,
After freshly installing universal blue sericea, it looks like distrobox is not working properly. I can create a container, but when I try to enter it, I get this error: `Error: unable to start container "d26a061e9e53e15393c42ea7a6c2fa78268bd33d72e6d43d2c75ba4384c337de": crun: make `/var/home/brandon/.local/share/containers/storage/overlay/daaf476633d847190290c64911628ba7c330918ed23e5ba400b4558cc48000f9/merged` private: Permission denied: OCI permission denied`

This is also not a bug from the ISO per say, as it looks like this happens when migrating a fedora sericea install. I have not tried the official universal blue iso.

**Comment by sandmuel** [comment]
hmm, for me it's working just fine, and just like you I rebased from a fedora sericea install. Are you on `:latest`?

**Comment by brandflake11** [comment]
No, I rebased to fedora 39. Let me rebase to :latest and see (I guess I don't know the difference between the two).

**Comment by brandflake11** [comment]
Okay, I rebased to :latest and I am still having this issue.

**Comment by brandflake11** [comment]
It seems this is affecting podman as well, as I can't start a container with it as well. It get the same error: `Error: unable to start container "fb0631f2e02535c35f599873526daeed4adfad08b5fed87ca1338ba2551ed12a": crun: make `/var/home/brandon/.local/share/containers/storage/overlay/d42cba2791b52073031974e106424fbaa669feac5dcfbbada8c7fa4e21128ea5/merged` private: Permission denied: OCI permission denied`

**Comment by brandflake11** [comment]
I didn't know what to do to fix this, so I went ahead and reinstalled, with silverblue as my image, universal blue directly from the official iso and it all worked great. I don't know what the issue was, maybe something of a bad install. I'm not sure, but I hope it never happens again and no one else is plagued by this.
