### ISSUE TITLE
libheif-tools not generating thumbnails

### ISSUE THREAD

**Issue by samicokar** [ublue-os/main#459]
### Describe the package

I'd like to request the package `libheif-tools` to allow for additional functionality around HEIF files such as viewing thumbnails from HEIF files. 

### Information on the package

Last metadata expiration check: 0:00:08 ago on Sat 23 Dec 2023 12:13:51 PM MST.
Available Packages
Name         : libheif-tools
Version      : 1.16.2
Release      : 2.fc38
Architecture : x86_64
Size         : 73 k
Source       : libheif-1.16.2-2.fc38.src.rpm
Repository   : updates
Summary      : Tools for manipulating HEIF files
URL          : https://github.com/strukturag/libheif
License      : MIT
Description  : This package provides tools for manipulating HEIF files.

### Image

All Images

**Comment by fiftydinar** [comment]
> ### Describe the package
> 
> I'd like to request the package `libheif-tools` to allow for additional functionality around HEIF files such as viewing thumbnails from HEIF files.
> ### Information on the package
> 
> Last metadata expiration check: 0:00:08 ago on Sat 23 Dec 2023 12:13:51 PM MST. Available Packages Name : libheif-tools Version : 1.16.2 Release : 2.fc38 Architecture : x86_64 Size : 73 k Source : libheif-1.16.2-2.fc38.src.rpm Repository : updates Summary : Tools for manipulating HEIF files URL : https://github.com/strukturag/libheif License : MIT Description : This package provides tools for manipulating HEIF files.
> ### Image
> 
> All Images

This package is already available:
https://github.com/ublue-os/main/blob/main/packages.json#L21C1-L21C33

**Comment by castrojo** [comment]
The packages are there but they don't appear to be working. https://github.com/tigranbs/test-heic-images 

![image](https://github.com/ublue-os/main/assets/1264109/def6b25b-2d59-467c-8978-8081988228a2)

**Comment by bsherman** [comment]
Hmm... this is odd. I'm running a `ublue-os/main` Silverblue F39 derivative image but I don't think I'm adding anything related to thumbnails and heic preview works for me.

![Screenshot from 2023-12-27 20-37-23](https://github.com/ublue-os/main/assets/60557/28af445e-08be-4778-89eb-04f798d9ac7c)

**Comment by bsherman** [comment]
@samicokar what image are you using? silverblue/kinoite based? Or one of the others?
