### ISSUE TITLE
add `xone` and `xpadneo` akmods

### ISSUE THREAD

**Issue by bsherman** [ublue-os/main#46]
Today in discord #general I responded to a question about how to get one/both of these drivers into a ublue image. An ensuing chat prompted the creation of this issue for further discussion on the topic.

[xpadneo](https://github.com/atar-axis/xpadneo) specifically supports xbox one wireless controller via bluetooth
[xone](https://github.com/medusalix/xone) supports xbox one controllers/accessories via USB or the USB wireless dongle, aims to replace `xpad`

I've personally been building my own image atop ublue-os main and nvidia to add these two drivers. As akmods, like the nvidia drivers, they also need a signing key to support Secure Boot systems.

So this is a multipart question:

**1) should both `xpadneo` and `xone` be added to `ublue-os/main` ? just one? which? why?**
It was suggested in chat that we already have udev rules for various devices so adding drivers like this doesn't seem like much of a stretch. 

`xpadneo`  pros:
- xbox one controllers will work via bluetooth (I don't believe they function via bluetooh without this driver)

`xpadneo` cons:
- ???

`xone` pros:
- xbox one wireless usb dongle support 
- claims to be " a modern replacement for xpad, aiming to be compatible with Microsoft's Game Input Protocol (GIP)."

`xone` cons:
- when installed will take priority over `xpad` for any supported devices, which some users may not prefer

**2) If either are added, they need a signing key to enable Secure boot. How to handle this?**

I'd personally suggest moving the existing key from `nvidia` into `main` and renaming it to `ublue` such that `main` would provide instructions to import like:   `sudo mokutil --import /etc/pki/akmods/certs/akmods-ublue.der` 

If so, it would be nice for this same key get re-used by the `nvidia` build so that only one key needs to be imported.

Though, there could be two distinct keys.

For reference, here's my repo and build of these akmods: https://github.com/bsherman/ublue-kmods/

**Comment by mitchejj** [comment]
Shouldn't main be the starting point of in building our own adventure and not the kitchen sink?

Looking at the uBlue architecture as one flows down the chart the resulting image becomes specialized (aka more opinionated). Adding a game controller is specialized. I fully understand that many enjoy gaming on their computers. I understand the main image is going to be opinionated. However, not all individuals care about gaming. I'm in the non-gaming camp and have no use for these drivers. Just like many don't have a use for NVIDIA drivers So why not just add the NVIDIA drivers to all builds?

What percent of users are looking to use a Xbox controller, how many users have a need for NVIDIA drivers? I think something like this could exist just under main; and that would be in the realm of a custom image(s).

**Comment by castrojo** [comment]
I think we should add this, there are millions of controllers in the wild and Windows has had plug and play support for controllers for a long time now. Getting this working is really difficult for most users, especially on coreos-style systems. The NVidia drivers are gigs and gigs of space so they kind of have to be in their own image. 

@bsherman how big are the modules+firmware on disk? I'm not expecting them to be large. (I don't know where to look in the image). 

We'd have to see how it does with F38 builds but we can easily revert if it becomes a long term issue.

**Comment by bsherman** [comment]
I'm perfectly happy building my own custom images, so obviously I agree a user can add akmod drivers themselves in a custom image build, but it's a lot easier to layer an `rpm-ostree override remove xone-kmod-common xpadneo-kmod-common` (or remove in an image build) than to add them later, especially for a user doesn't have the knowledge or desire to build a personalized desktop image.

I believe adding these drivers is complementary to the choice already demonstrated in the opinionated main image which enables out of box support for game devices (and other devices) via https://github.com/ublue-os/config 's udev rules, etc. The purpose is not to create a "gamer focused" main, but to provide an "it just works" experience for a reasonably wide set of potential users.

I do agree with @mitchejj that "main" shouldn't be a "gamer focused" image; to that end, I wouldn't want games, game launchers, or other gaming specific patches to be installed. However, "main" is the foundation of the ublue-os desktop distribution images, based on Fedora, and Fedora's kernel already includes the `xpad` driver and other game controller support. So, saying no to the proposed drivers based on the argument that all downstream users won't use them is not far from the idea of purging all game controller drivers from Fedora's kernel for the same reason, and certainly not consistent with the inclusion of the already mentioned udev rules.

I also appreciate the comment that this could cause problems with F38 builds. I want to explore that and make sure no builds would break.


@castrojo sizes of packages in bytes on my current image.
```
rpm --queryformat='%12{SIZE}  %{NAME}\n' -q `rpm -qa |grep -E "xone|xpadneo|custom-key" | xargs`
       11908  kmod-xpadneo-6.1.14-200.fc37.x86_64
       98305  xpadneo-kmod-common
       50932  kmod-xone-6.1.14-200.fc37.x86_64
       93518  xone-kmod-common
        1578  akmods-custom-key
```
So,  250 KiB total.

**Comment by Zoialord** [comment]
Just my opinion here as an average "user" but things like this are IMO what separates a good base from a not-so-good one, If people really want a "base" system they would use either Silverblue or Kinoite. These images are as much about ease of use and maintenance as anything else.

Personally, I'd go with having them included as a default, if people need them they are there if they don't the space consumed is negligible and anyone not wanting them can remove them. At the end of the day we all run a kernel with plenty of stuff included that we never use, but we don't go building our own (well most people) to disable them.

**Comment by castrojo** [comment]
As of right before this post this webpage is 183K. This seems like a nobrainer to me. 

Let's talk about ways we can make this more composable for folks though: 

- https://github.com/orgs/ublue-os/discussions/106

**Comment by mitchejj** [comment]
I suppose if the drivers are that small... it doesn't seem that bad.

**Comment by bsherman** [comment]
> this currently would break F38 builds.

**Confirmed.** My personal `ublue-kmods` repo is building `xpadneo` and `xone` akmods from [negativo17 fedora-steam 37 repo](https://negativo17.org/repos/steam/fedora-37/x86_64/) and as of now, the RPMs are missing from [negativo17 fedora-steam 38 repo](https://negativo17.org/repos/steam/fedora-38/x86_64/).

This raises a good question about sources. RPMfusion is "trusted", but there are also some COPRs being used in a few places, though it looks they are COPRs by kyle, ublue-os, and kde_sig, so fairly "official" or directly related to this project.

What is needed to include a third party package into "ublue-os"? I'm starting to think if we want this included, it may be best to build it in a ublue-os COPR.

**Comment by bsherman** [comment]
There's been generic work for adding `akmods` support:
pending PRs:
- https://github.com/ublue-os/akmods/pull/1
- https://github.com/ublue-os/nvidia/pull/72

@dhoell and I have discussed working to move this forwared.

**Comment by marczuverink** [comment]
I'd really like to see this added.

**Comment by bsherman** [comment]
I'm incredibly happy to close this as we've added these to ublue akmods repo!
https://github.com/ublue-os/akmods/issues/4
