### ISSUE TITLE
Bluefin 2.0.0 ISO: too many WLANs, can't confirm selection

### ISSUE THREAD

**Issue by MikeTRose** [ublue-os/main#460]
### What happened?

Trying to install Bluefin in a wireless-dense environment, and the list of available WLANs overflows the display so it is not possible to select and configure any of them.

Workaround: used Ethernet.

### Relevant log output

```shell
Please attach or paste the logs from the Anaconda Installer https://docs.fedoraproject.org/en-US/quick-docs/anaconda/anaconda_logging/
```

**Comment by castrojo** [comment]
There's nothing we can do about this one unfortunately. We're waiting for the new web installer in fedora (and also working on an offline ISO) so it'll be solved by Fedora at some point. 

Thanks for the report though!
