### ISSUE TITLE
nix-install fails error code 1

### ISSUE THREAD

**Issue by firefoxlover** [ublue-os/main#461]
I just tried `just nix-install` and:

info: downloading installer https://install.determinate.systems/nix/tag/v0.15.1/nix-installer-x86_64-linux
Error: 
   0: Planner error
   1: Error executing action
   2: Action `configure_init_service` errored
   3: `/etc/systemd/system/nix-daemon.service` already exists, consider removing it with `rm /etc/systemd/system/nix-daemon.service`

Location:
   src/cli/subcommand/install.rs:197

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

```
Consider reporting this error using this URL: https://github.com/DeterminateSystems/nix-installer/issues/new?title=%3Cautogenerated-issue%3E&body=%23%23+Error%0A%60%60%60%0AError%3A+%0A+++0%3A+Planner+error%0A+++1%3A+Error+executing+action%0A+++2%3A+Action+%60configure_init_service%60+errored%0A+++3%3A+%60%2Fetc%2Fsystemd%2Fsystem%2Fnix-daemon.service%60+already+exists%2C+consider+removing+it+with+%60rm+%2Fetc%2Fsystemd%2Fsystem%2Fnix-daemon.service%60%0A%60%60%60%0A%0A%23%23+Metadata%0A%7Ckey%7Cvalue%7C%0A%7C--%7C--%7C%0A%7C**version**%7C0.15.1%7C%0A%7C**os**%7Clinux%7C%0A%7C**arch**%7Cx86_64%7C%0A
cp: der Aufruf von stat für '/nix/var/nix/profiles/default/lib/systemd/system/nix-daemon.service' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
cp: der Aufruf von stat für '/nix/var/nix/profiles/default/lib/systemd/system/nix-daemon.socket' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
error: Recipe `nix-install` failed with exit code 1
```

not sure if this is upstream?

I am using kinoite-main

**Comment by castrojo** [comment]
This script has been removed from the justfile.

**Comment by rafaeletc** [comment]
it will be interesting to keep at least the part that removes the installation of the nix, to facilitate the lives of the users that it has installed via `ujust nix`
