### ISSUE TITLE
Selinux Troubleshooting Tools

### ISSUE THREAD

**Issue by noelmiller** [ublue-os/main#465]
### Describe the package

I'd like to request the package `setroubleshoot` and `setools` because ... Bazzite and Bluefin both ship SELinux as part of the distribution. We may want to consider adding `cockpit-selinux` if we are shipping cockpit in any of the images as well.  This should be part of the main image.

### Information on the package

Packages information from `quay.io/fedora/fedora:39`:
```
Name         : setroubleshoot
Version      : 3.3.32
Release      : 7.fc39
Architecture : x86_64
Size         : 84 k
Source       : setroubleshoot-3.3.32-7.fc39.src.rpm
Repository   : fedora
Summary      : Helps troubleshoot SELinux problems
URL          : https://gitlab.com/setroubleshoot/setroubleshoot
License      : GPL-2.0-or-later
Description  : setroubleshoot GUI. Application that allows you to view setroubleshoot-server
             : messages.
             : Provides tools to help diagnose SELinux problems. When AVC messages
             : are generated an alert can be generated that will give information
             : about the problem and help track its resolution. Alerts can be configured
             : to user preference. The same tools can be run on existing log files.
```

```
Name         : setools
Version      : 4.4.3
Release      : 1.fc39
Architecture : x86_64
Size         : 8.2 k
Source       : setools-4.4.3-1.fc39.src.rpm
Repository   : fedora
Summary      : Policy analysis tools for SELinux
URL          : https://github.com/SELinuxProject/setools/wiki
License      : GPL-2.0-only and LGPL-2.1-only
Description  : SETools is a collection of graphical tools, command-line tools, and
             : Python modules designed to facilitate SELinux policy analysis.
```

```
Name         : cockpit-selinux
Version      : 307
Release      : 1.fc39
Architecture : noarch
Size         : 411 k
Source       : cockpit-307-1.fc39.src.rpm
Repository   : updates
Summary      : Cockpit SELinux package
URL          : https://cockpit-project.org/
License      : LGPL-2.1-or-later
Description  : This package contains the Cockpit user interface integration with the
             : utility setroubleshoot to diagnose and resolve SELinux issues.
```

### Image

All Images

**Comment by KyleGospo** [comment]
+1

**Comment by noelmiller** [comment]
If this gets added, we will want to remove setroubleshoot and setools from Bazzite.

**Comment by noelmiller** [comment]
Talking with @KyleGospo, it sounds like we needed to remove setroubleshoot and setools from Bazzite as we were getting a lot of alerts regarding upstream packages in Bazzite. This brings up a general question of how we want to approach SELinux.

It appears we have 2 options for adding the packages: 
1. We can disable alerting from sealert by default so the user is not receiving alerts from it while still providing the command line tools for troubleshooting (less secure)
2. Creating policies in SELinux when we add packages from upstream so they do not alert in the first place and leave sealert in place to alert the user of issues (more secure)

I will double check which package provides a GUI for SELinux troubleshooting, as that is also helpful when handling alerts. 

If we end up adding these packages, there should be a section in the documentation discussing SELinux, its benefits, and what to do if users receive alerts from it. I am personally of the opinion that the general attitude of disabling SELinux when there is a problem with it is harmful in the long run (and some distros like Red Hat won’t even let you disable it anymore, best you can do is set it to permissive). It may be worth reaching out to the Fedora team and see how they handle SELinux alerting on the desktop as well.

I think giving the user feedback about issues is important, but SELinux tooling isn’t exactly the greatest at accomplishing that. 

Wondering what others think on this topic?

**Comment by alexispurslane** [comment]
I'd like to have SELinux as enabled as possible, and would appreciate having the tools to manage that installed by default (especially if the philosophy is that everything necessary for a base system, and to manage a base system, but no more than that, is installed in rhe image).

**Comment by castrojo** [comment]
This should be done in upstream Fedora or downstream, not in main.
