### ISSUE TITLE
[Membership Request] @noelmiller

### ISSUE THREAD

**Issue by EyeCantCU** [ublue-os/main#471]
As per https://universal-blue.org/membership/#member

I sponsor @noelmiller for membership rights across the Ublue org. Noel has been troubleshooting issues with maintainers and users as well as filing detailed and insightful issues on GitHub. Noel would be helpful with project management - specifically in helping with the prioritization, creation, and moderation of issues in addition to improving documentation for both Ublue and Fedora Silverblue. Noel can also help us find others more knowledgeable about problems we'd like to resolve and solutions we'd like to implement.

One more person from @ublue-os/approver is needed for sponsorship.

**Comment by KyleGospo** [comment]
Big +1

**Comment by bsherman** [comment]
+1 here, also.

**Comment by castrojo** [comment]
Alright, setting perms! WELCOME TO THE TEAM!
