### ISSUE TITLE
modify rpm-ostree module to add a repository with a signature

### ISSUE THREAD

**Issue by ecocode** [ublue-os/main#477]
Adding a repository with a signature is currently not supported.

An example is https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo which needs the accompanying signature file to allow installation of the package ```brave-browser``` which is located at https://brave-browser-rpm-release.s3.brave.com/brave-core.asc .

The rpm-ostree module doesn't have an option to add this, which makes the build of the image fail due to missing signature file.

**Comment by castrojo** [comment]
This is an upstream issue.
