### ISSUE TITLE
REISUB/REISUO support

### ISSUE THREAD

**Issue by TriMoon** [ublue-os/main#479]
### What happened?

Due to a problem i just encountered with _"being stuck at logout"_ in `Bazzite`, i suggest you guys to enable <kbd>SysRq</kbd> in all your builds, so people can do gracefull reboots/shutdowns...

For a nice explanation of what `REISUB/REISUO` is, see this fine [[HowTo] reboot / turn off your frozen computer: REISUB/REISUO](https://forum.manjaro.org/t/howto-reboot-turn-off-your-frozen-computer-reisub-reisuo/3855) on a manjaro forum, but the functionality works for **All Linux distros** :wink:

**Comment by KyleGospo** [comment]
End users can enable this functionality by creating `/etc/sysctl.d/90-sysrq.conf` with the contents: `kernel.sysrq = 1`
