### ISSUE TITLE
Remove "Maximize build space" step where not needed

### ISSUE THREAD

**Issue by bsherman** [ublue-os/main#489]
Since Github increased the amount of disk on builders, our "Maximize build space" step is not really needed and if not needed it causes jobs to run longer than otherwise required.

See if we can remove this everywhere.

**Comment by castrojo** [comment]
+1 but Bazzite and Bluefin will probably keep it.

**Comment by bsherman** [comment]
main and nvidia are done... do we want to remove it from the HWE builds?

**Comment by bsherman** [comment]
I think just doing as part of consolidation is fine. I don't want to touch all those repos if I can help it.

**Comment by bsherman** [comment]
> I think just doing as part of consolidation is fine. I don't want to touch all those repos if I can help it.

This was actually done as part of consolidation of hwe repos.
