### ISSUE TITLE
Use better defined buildah techniques

### ISSUE THREAD

**Issue by castrojo** [ublue-os/main#498]
Noel's friend was working on this. We're just using the vanilla buildah action, ends up you can optimize. This is at least 600MB, we could probably squeeze out some savings here:

https://github.com/JasonN3/ublue-os-main/pull/1

```
REPOSITORY                                                   TAG         IMAGE ID      CREATED         SIZE
ghcr.io/jasonn3/base                                         6854aa4-38  3bd3c54caee4  15 minutes ago  4.04 GB
ghcr.io/ublue-os/base-main                                   latest      a63c9e5d4a59  3 hours ago     4.69 GB
```

**Comment by bsherman** [comment]
Turns out the 600MB space savings were reported in error. 

There could be some value in a similar approach for Bazziite/Bluefin, but they may also just benefit from keeping their `Containerfile` but building with `podman build --squash` instead of using the redhat action.
