### ISSUE TITLE
Snapper + BTRFS Assistant to allow automatic BTRFS snapshots and a GUI to manage it

### ISSUE THREAD

**Issue by Nitrousoxide** [ublue-os/main#504]
### Describe the package

BTRFS Assistant + Snapper might be a good addition to ublue.  It gets you the timeshift gui experience with much greater flexibility for arbitrary subvolume setups.  It would let the user setup automatic /home snapshotting (/ snapshotting obviously being unnecessary, and probably impossible, with ostree)
https://gitlab.com/btrfs-assistant/btrfs-assistant

BTRFS Assistant is nice for this usecase because timeshift expects ubuntu @ and @home subvolumes which are not the default subvolume setup for fedora/silverblue/ublue, while Snapper will happily manage the snapshotting for any arbitrary subvolumes (including the real "/var/home" one for silverblue/ublue). This gives you a gui tool to roll back so you don't need to use the terminal, and while BTRFS snapshots are not a complete 3-2-1 backup strategy, giving people an easy way to get at least part of that backup procedure down will help to reduce the risk of dataloss.

### Information on the package

Available Packages
Name         : btrfs-assistant
Version      : 1.9
Release      : 1.fc39
Architecture : x86_64
Size         : 180 k
Source       : btrfs-assistant-1.9-1.fc39.src.rpm
Repository   : updates
Summary      : GUI management tool to make managing a Btrfs filesystem easier
URL          : https://gitlab.com/btrfs-assistant/btrfs-assistant
License      : GPL-3.0-or-later
Description  : Btrfs Assistant is a GUI management tool to make managing a Btrfs
             : filesystem easier.
             : 
             : The primary features it offers are:
             : 
             : * An easy to read overview of Btrfs metadata
             : * A simple view of subvolumes with or without Snapper/Timeshift
             :   snapshots
             : * Run and monitor scrub and balance operations
             : * A pushbutton method for removing subvolumes
             : * A management front-end for Snapper with enhanced restore
             :   functionality
             :     * View, create and delete snapshots
             :     * Restore snapshots in a variety of situations
             :         * When the filesystem is mounted in a different distro
             :         * When booted off a snapshot
             :         * From a live ISO
             :     * View, create, edit, remove Snapper configurations
             :     * Browse snapshots and restore individual files
             :     * Browse diffs of a single file across snapshot versions
             :     * Manage Snapper systemd units
             : * A front-end for Btrfs Maintenance
             :     * Manage systemd units
             :     * Easily manage configuration for defrag, balance and srub
             :       settings

Available Packages
Name         : snapper
Version      : 0.10.4
Release      : 2.fc39
Architecture : x86_64
Size         : 490 k
Source       : snapper-0.10.4-2.fc39.src.rpm
Repository   : fedora
Summary      : Tool for filesystem snapshot management
URL          : http://snapper.io
License      : GPL-2.0-only
Description  : This package contains snapper, a tool for filesystem snapshot
             : management.

### Image

All Images

**Comment by Mortifier13** [comment]
I use both and have to layer them, so it would be great if it was integrated.

I have BTRFS subvolumes set up for home, var, cache, log, tmp, containers, and  VM images as well.  Seems to be working fine.  I attempted Timeshift first but it was too limiting.

**Comment by nandiferd** [comment]
Given that btrfs-assistant is a qt app, opting for snapper-gui which is a gtk app might provide a better integration with GNOME (adw-gtk3). Sadly the latest commit was made two years ago, but the app works.

Timeshift acts weird on btrfs and the cli tool is way too complicated.

**Comment by Nitrousoxide** [comment]
I would personally prefer that actively developed and maintained Btrfs-Assistant over something working but abandoned.  It's not like ublue is gnome only either, so having qt apps is hardly unusual.

**Comment by castrojo** [comment]
This is out of scope for ublue, Fedora is the place to convince to do filesystem integration.
