### ISSUE TITLE
Approver access for Noel Miller

### ISSUE THREAD

**Issue by castrojo** [ublue-os/main#513]
As [per the governance](https://universal-blue.discourse.group/t/universal-blue-project-governance/51/3#approver-8) I'd like to nominate Noel Miller for org-wide approver. 

The ISO has been a bane of our existence and Noel made it happen. 

Additionally I've synced with Marco and he's happy to emeritus out of org ownership, so I've moved Kyle and bsherman into owners. He's still around in Discord just busy with a new kid and happily consuming ublue instead. 

cc @ublue-os/approver @ublue-os/member

**Comment by p5** [comment]
:+1

**Comment by bigpod98** [comment]
:+1:

**Comment by bsherman** [comment]
:+1:

**Comment by EyeCantCU** [comment]
Well deserved 👍

**Comment by KyleGospo** [comment]
+1

**Comment by HikariKnight** [comment]
👍

**Comment by bketelsen** [comment]
+1

**Comment by marcoceppi** [comment]
👍

**Comment by noelmiller** [comment]
Thanks everyone! Looking forward to approving things :P
