### ISSUE TITLE
Add a Cosmic build

### ISSUE THREAD

**Issue by castrojo** [ublue-os/main#517]
Ryan has this working already and is working inside the scope of Fedora to make Cosmic with packaging, etc.

https://github.com/ryanabx/fedora-cosmic-atomic/blob/main/Containerfile

I'm not sure what the plan on getting it into Fedora but the endstate would be us deriving from an official image. The outstanding question I have for the team is:

- other repo or do it in main? I'm leaning towards a new repo so it can rev fast without adding churn to main. Then when Fedora's ready the image namespace will already be in place and users won't notice. 
- We've been purposely trying to archive repos and one off desktops but since this work is happening in Fedora I think it's lower risk for us. 

cc @ublue-os/approver @ublue-os/member 

My initial thought is importing it into ublue-os/cosmic and moving from there.

**Comment by fiftydinar** [comment]
Sounds good to me

**Comment by bsherman** [comment]
Since there's no upstream cosmic image, this can't be done directly in main. 

But we could add an "atomic-cosmic" repo, build an image there which matches what we'd expect fedora's official image to someday look like and then we use that image as our upstream here in main.

**Comment by bsherman** [comment]
My comment agrees with @castrojo 's suggestion, though I'd probably use "atomic-cosmic" than "cosmic" since it's more likely to match the future upstream name.

**Comment by fiftydinar** [comment]
> My comment agrees with @castrojo 's suggestion, though I'd probably use "atomic-cosmic" than "cosmic" since it's more likely to match the future upstream name.

cosmic-atomic*, as they use that pattern now for sway, cinnamon & other variants.

**Comment by p5** [comment]
I think a Cosmic spin would be great!

Personally, I imagine it working like this:
1. ublue-os/cosmic builds the base image (adding ONLY the desktop environment)
2. ublue-os/main adding the hardware enablement and others on top of the cosmic base

So we are treating cosmic as all other images, except we are doing the initial build.

**Comment by KyleGospo** [comment]
+1

**Comment by castrojo** [comment]
https://github.com/ublue-os/cosmic

Alright, feel free to dig in and help!
