### ISSUE TITLE
Nvidia driver not installed/loaded properly on Asus/Nvidia image

### ISSUE THREAD

**Issue by sinniti1** [ublue-os/main#542]
Hi ublue-os team,

On both `silverblue-nvidia` and `silverblue-asus-nvidia`, I am facing the same issue. Secure boot is disabled and the MOK key is also not enrolled.

After I rebased from fedora silver blue to `silverblue-asus-nvidia` I configured the nvidia kargs by `ujust configure-nvidia`.

In flatpak OBS, NVENC is not appear on video encoder. In distrobox OBS (distrobox container installed by ujust), when I want to use NVENC as the encoder for streaming or recording, it will output an error:

```
Failed to open NVENC codec: Unknown error occured

Try installing the latest NVIDIA driver.
```

Also when I trying to test CUDA support by `ujust configure-nvidia`. The output is:

`The Nvidia kernel module is not loaded. You may be using secure boot without the needed signing key, lacking the needed kargs, or may not be a Nvidia image. See "just enroll-secure-boot-key" and "just nvidia-set-kargs".`

Therefore IMO the Nvidia driver is not installed/loaded properly.

**Comment by qoijjj** [comment]
please provide your current `rpm-ostree status` and `rpm-ostree kargs`

**Comment by sinniti1** [comment]
`rpm-ostree status`:

```
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/secureblue/silverblue-asus-nvidia-userns-hardened:latest
                   Digest: sha256:4c46da84acc797519ffdb15cfbf1a954c56129c1edaf271fe4de12a891558594
                  Version: 39.20240406.0 (2024-04-06T18:17:45Z)
          LayeredPackages: brave-browser langpacks-en

  ostree-image-signed:docker://ghcr.io/ublue-os/silverblue-asus-nvidia:latest
                   Digest: sha256:9467f3da525a366cc3f596f8aaf9057c8957aa0ef724547778d671b3c5cdc6ab
                  Version: 39.20240406.0 (2024-04-06T15:38:22Z)
          LayeredPackages: brave-browser langpacks-en
```


`rpm-ostree kargs`:

> `rd.luks.uuid=luks-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXXX rhgb quiet root=UUID=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX rootflags=subvol=root rw init_on_alloc=1 init_on_free=1 slab_nomerge page_alloc.shuffle=1 randomize_kstack_offset=on vsyscall=none lockdown=confidentiality random.trust_cpu=off random.trust_bootloader=off iommu=force intel_iommu=on amd_iommu=force_isolation iommu.passthrough=0 iommu.strict=1 pti=on module.sig_enforce=1 mitigations=auto,nosmt ostree=/ostree/boot.1/default/e03263ebe99e5ca066f3e280cf1a05037bac8bd60dfa1492912d114d965382aa/0 rd.driver.blacklist=nouveau modprobe.blacklist=nouveau nvidia-drm.modeset=1`

**Comment by qoijjj** [comment]
remove the secureblue kargs and rebase to a ublue main image, otherwise this isn't a proper repro on ublue.

also, since this is asus specific, it should be in the hwe repo

**Comment by sinniti1** [comment]
But I also have the issue when I use the ublue-os silverblue-nvidia image, so I report the issue here.

**Comment by qoijjj** [comment]
@sinniti1 even without the secureblue kargs?

**Comment by sinniti1** [comment]
After remove the secureblue kargs, the following images: `silverblue-nvidia`, `silverblue-asus-nvidia` from ublue upstream,  `silverblue-nvidia-userns-hardened`, `silverblue-asus-nvidia-userns-hardened` from secureblue are able to use Nvidia driver properly now.

**Comment by qoijjj** [comment]
`silverblue-nvidia` is part of hwe as well

**Comment by qoijjj** [comment]
@sinniti1 then this is a secureblue karg issue. Please test the kargs to determine which one is causing the issue, then open a new issue on secureblue.

Please close this issue.

**Comment by sinniti1** [comment]
Ok, thanks for your help.
