### ISSUE TITLE
m2giles for member

### ISSUE THREAD

**Issue by castrojo** [ublue-os/main#548]
@m2giles has had write in bluefin for a while and has been helping across the board in other repos, I'd like to nominate to ublue-os/member.

**Comment by noelmiller** [comment]
+1 absolutely an amazing contributor.

**Comment by p5** [comment]
:+1: a great help in the Bluefin repo, and will be great to have them helping out in other places!

**Comment by EyeCantCU** [comment]
+1

**Comment by m2Giles** [comment]
I love this project.

**Comment by bsherman** [comment]
+1

**Comment by castrojo** [comment]
Invite in your inbox, close this issue after you've accepted! WELCOME. 

![image](https://github.com/ublue-os/main/assets/1264109/0e091657-9f49-4b8e-9866-ba92a61e0bfc)
