### ISSUE TITLE
package request: tumbler

### ISSUE THREAD

**Issue by mitchejj** [ublue-os/main#55]
### Describe the package

The default file manager in Sericea is Thunar which requires tumbler and not ffmpegthumbnailer (#49) I would also suggest excluding ffmpegthumbnailer for Sericea builds.

[xfce:thunar:4.16:tumbler [Xfce Docs]](https://docs.xfce.org/xfce/thunar/4.16/tumbler)
[Arch Linux - thunar 4.18.4-1 (x86_64)](https://archlinux.org/packages/extra/x86_64/thunar/)

### Image

Sericea

**Comment by castrojo** [comment]
Ok so same as with Kinoite, we need to move `ffpmegthumbnailer` to each flavor, I'll try to get this today but if you want to send a PR feel free!

**Comment by ribbanya** [comment]
Can these kinds of things be abstracted somehow, maybe into `just` tasks? Like, `main` can say "I need a thumbnail provider" and then the flavor can provide it further down?

**Comment by castrojo** [comment]
The packages.json is designed so we can do any combo of packages for any desktop just for this purpose. Things in the justfiles would be after image creation.

**Comment by castrojo** [comment]
Just reopening this, if you could confirm that it's working as expected in the latest image and close this that'd be awesome. Thanks for the feedback!

**Comment by mitchejj** [comment]
Works.
