### ISSUE TITLE
bootupd upgrade issue tracking (F40)

### ISSUE THREAD

**Issue by castrojo** [ublue-os/main#551]
Heads up @ublue-os/approver @ublue-os/member this one is very important:

https://github.com/fedora-silverblue/issue-tracker/issues/543

**Comment by bsherman** [comment]
Some comments from Discord...

Ublue main images have included `bootc` for months... and it seems `bootc` pulls in `bootupd` as a weak dependency.

So all users of current ublue-os main derived images already have `bootupd-0.2.18-2.fc39.x86_64` on their system.

I've already updated several different machines to ublue/silverblue with the new 6.8.4 kernel and have not run into this issue, but as mentioned we have bootupd.

A [suggested workaround/solution in the upstream bug report](https://github.com/fedora-silverblue/issue-tracker/issues/543#issuecomment-2027060689) is to add `bootupd`, so I am wondering if already having this on our images may have already updated our bootloaders and avoided this issue for ublue users?

**Comment by castrojo** [comment]
Ok so the current line of thinking is since we've turned on F40:

a) We haven't had any reports of anything like this (searched through the discord just in case)
b) We're not making ISOs of F40 at this time so everyone who has been using our F40 images had to have gotten there via a rebase.

So we're thinking the early inclusion of bootc/bootupd might have saved the day - so we'll keep some eyes open and let the situation develop.

**Comment by castrojo** [comment]
Seems like we were unaffected?

**Comment by bsherman** [comment]
> Seems like we were unaffected?

thankfully, yes, it does seem to be

**Comment by teal77** [comment]
Don't know if this is user error but ran into this today with ublue kinoite main:gts 39.20240618.0 
`load the kernel first`
Posting this here if it helps someone, I worked around it by disabling secure boot in BIOS

**Comment by castrojo** [comment]
See also:
https://universal-blue.discourse.group/t/bluefin-no-longer-boots-after-update-bad-shim-signature/2373/14
