### ISSUE TITLE
PROPOSAL: Add Codacy to check code quality

### ISSUE THREAD

**Issue by noelmiller** [ublue-os/main#552]
Since we are considering splitting out our container files into smaller bash scripts (rather than doing inline bash), I think it would be helpful to have a code analysis tool to help with consistency and code quality: https://www.codacy.com/pricing

The open source plan is free and it can be added as a check in Github on a repo. 

See https://github.com/JasonN3/build-container-installer/pull/100 as an example.

**Comment by castrojo** [comment]
+1, I was thinking a shellcheck action but this should be fine to test. I can add it at an org level but would prefer to test it in one repo that isn't main first to get a feel for it.

I don't mind just turning it on as a nonblocking check in bluefin for a while, lmk.

**Comment by castrojo** [comment]
I've got this on in Bluefin and a few others and it seems fine. Any other feedback from approvers?
