### ISSUE TITLE
Remove flatpak-system-update.timer and flatpak-user-update.timer in post-install.sh?

### ISSUE THREAD

**Issue by ispanos** [ublue-os/main#555]
I think [this line](https://github.com/ublue-os/main/blob/410e630ef1c77bf2c0072396da9bb622aa1cb08d/post-install.sh#L10) and the one after it should be removed. These timers are not present in Bluefin and I can't find any recent reference to them.

```
❯ systemctl status flatpak-system-update.timer 
Unit flatpak-system-update.timer could not be found.
```

**Comment by bsherman** [comment]
These services are installed via the `ublue-os-update-services` RPM and you can see the source in this search: https://github.com/search?q=repo%3Aublue-os%2Fconfig+update.timer&type=code

I agree it may not be obvious how this is installed:

1. This line https://github.com/ublue-os/main/blob/main/Containerfile#L20 copies the RPM (and others) from the latest `config` image.
2. This line https://github.com/ublue-os/main/blob/main/install.sh#L19-L20 installs the RPM (and others) from the copied location.
3. This line https://github.com/ublue-os/main/blob/main/post-install.sh#L10 correctly enables the service as it is the desired behavior for `*-main` images 

I haven't inspected closely, but I believe bazzite and aurora/bluefin may be manually removing the timers in favor of `ublue-update`? 

@castrojo maybe you can comment on this? Maybe we need to improve how bluefin switches from the config/main update flow to the ublue-update service?

**Comment by castrojo** [comment]
I think I'm using both in Bluefin, using the timers as a backup to ublue-update.

**Comment by ispanos** [comment]
> ❯ systemctl status flatpak-system-update.timer 
> Unit flatpak-system-update.timer could not be found.

I run this on a freshly installed bluefin vm.
