### ISSUE TITLE
Include v4l2loopback akmod

### ISSUE THREAD

**Issue by dhoell** [ublue-os/main#57]
### Describe the package

The potential akmod change discussed in https://github.com/orgs/ublue-os/discussions/106 would be a perfect opportunity to include the v4l2loopback package. 

Since it is an akmod from RPMfusion, it would be a giant pain in the behind to layer and thus perfect candidate for inclusion in main.
Unified signing infrastructure, as discussed above, should make this hopefully painless. I'm currently trying to get it to world on the nvidia image.

The most common use-case is probably obs-virtualcam, it is the only thing keeping me from using ublue on my daily drivers, as I absolutely require it to make various videoconferencing software, which do not play nice on linux, work. 

### Image

All Images

**Comment by castrojo** [comment]
Have you tested how well it works with the obs flatpak? It'd be interesting to see what all the setup steps are.

**Comment by dhoell** [comment]
Got it to work on my ublue-os/nvidia fork, works perfectly with the OBS flatpak out of the box.

Itspretty simple, just adding the required packages (akmod-v4l2loopback in the builder step and the built kmod rpm and v4l2loopback package (which are the utils for it) in the image.

I would not open a pull request because it belongs in base, not nvidia, but currently it utilizes the akmod build process only found on nvidia. This evening when I have more time I'll look into making this more streamlined.

**Comment by castrojo** [comment]
This is in now, woo!
