### ISSUE TITLE
main-fsync as an image variant

### ISSUE THREAD

**Issue by HikariNeee** [ublue-os/main#585]
the fsync kernel being used in Bazzite (as well as my image) requires some changes to the nvidia driver to be built correctly which bazzite performs
A lot of these steps can be generalized into one image.

This makes bazzite and future images less  complicated.

**Comment by castrojo** [comment]
The purposes of these images is to remain close to stock Fedora, a third party kernel is out of scope.

(Though there might be enough people around to create a set of main-fsync images outside of ublue)
