### ISSUE TITLE
Add X11 support back in

### ISSUE THREAD

**Issue by mikae1** [ublue-os/main#587]
### Describe the package

I'd like to request the package `plasma-workspace-x11` because that lack of it sadly makes `kinoite-main` [unusable for us photographers](https://discuss.pixls.us/t/wayland-color-management/10804/) that want to profile our monitors and have a color manged workflow. Before the disappearance of X11 in Fedora 40 I found `kinoite-main` to be ultimate reliable Linux alternative for the working professional. `kwin-x11` is likely needed too, but I believe `plasma-workspace-x11` brings it in as a dependency.

### Information on the package

```
Available Packages
Name         : plasma-workspace-x11
Version      : 6.0.5.1
Release      : 1.fc40
Architecture : x86_64
Size         : 91 k
Source       : plasma-workspace-x11-6.0.5.1-1.fc40.src.rpm
Repository   : updates
Summary      : Xorg support for Plasma
URL          : https://invent.kde.org/plasma/plasma-workspace
License      : BSD-2-Clause AND BSD-3-Clause AND CC0-1.0 AND GPL-2.0-only AND GPL-2.0-or-later AND GPL-3.0-only AND LGPL-2.0-only AND
             : LGPL-2.0-or-later AND LGPL-2.1-only AND LGPL-2.1-or-later AND LGPL-3.0-only AND LGPL-3.0-or-later AND (GPL-2.0-only OR GPL-3.0-only)
             : AND (LGPL-2.1-only OR LGPL-3.0-only) AND MIT
Description  : Support for the legacy X11 window system in KDE Plasma, as opposed to the
             : default Wayland. This package provides the legacy "Plasma (X11)" session type
             : and the startplasma-x11 executable required by that session type. (Other
             : requirements such as kwin-x11 are found in the package dependencies.) The
             : session type can be switched between "Plasma (X11)" and the default "Plasma
             : (Wayland)" in the display manager (e.g., SDDM).
             : 
             : This version is maintained by individual Fedora packagers and NOT supported by
             : the Fedora KDE SIG. (See plasma-workspace-wayland for the default version, using
             : Wayland, maintained by the KDE SIG.)
```

### Image

Kinoite

**Comment by p5** [comment]
You might want to have a look at Aurora, since they have added X11 back.

I'm not sure of adding it in the `main` images though, since they should be close to stock with uncontroversial packages.  
Let's wait to see what other maintainers think.

**Comment by mikae1** [comment]
> You might want to have a look at Aurora, since they have added X11 back.

Oh, thanks! Did not know.

> I'm not sure of adding it in the `main` images though, since they should be close to stock with uncontroversial packages.

I see! And I’m officially a terrible searcher. It looks like [they said no for Kinoite already](https://github.com/ublue-os/main/issues/482). I’d be happy if it was available in any Plasma image. A more minimal, less developer oriented than Aurora, would of course be preferable. But I guess you can’t have it all (until you learn how to create your own image 🙂).

**Comment by noelmiller** [comment]
It is my opinion that the main images are meant to be a base image to be built on top of with minimal quality of life changes. The main images in my view should not be consumed directly unless you intend to build your own image. 

Adding the X11 packages would be a major diversion from Fedora and would add future tech debt that will ultimately need to be removed. 

In my view, You have 3 options to solve this problem: (easiest to hardest)
1. Use Bazzite or Aurora as they ship the package by default (I'm not sure how much longer Bazzite intends to ship it once the new Nvidia driver ships) 
2. Layer the packages yourself
3. Build your own custom images and layer the packages there.

**Comment by HikariKnight** [comment]
From my understanding it will be completely gone in F41, not even installable...

I have an ex that does art so i get the frustration of not being able to have color management.
But I sadly cannot agree with adding it back to `main` since upstream will not accept any bug reports where x11 is used, if you want it you can make a custom image that just takes the main image you want to use and add x11 back.
close to 0 maintenance for you (at most you will have to accept some PR from dependabot)

i would agree with looking at https://getaurora.dev/ if you do need x11 on fedora and dont want to make a custom image.

**Comment by HikariKnight** [comment]
>     1. Use Bazzite or Aurora as they ship the package by default (I'm not sure how much longer Bazzite intends to ship it once the new Nvidia driver ships)

IIRC Kyle wanted to remove it ASAP

**Comment by mikae1** [comment]
> From my understanding it will be completely gone in F41, not even installable...

Thanks, this saves me some trouble and time investment. If that’s the case I will have to go with another distro. Sad, because the Fedora approach to Atomic desktops was the holy grail for me.

**Comment by KyleGospo** [comment]
What's the issue preventing you from using Plasma Wayland exactly? Both GNOME and KDE have support for ICC color profiles under Wayland now.

**Comment by marcdeop** [comment]
I am Fedora KDE maintainer and despite us not supporting `plasma-workspace-x11` I also wonder where:
```
From my understanding it will be completely gone in F41, not even installable...
```
is coming from.

If you are gonna scare people away, at least provide sources to backup your claims

**Comment by mikae1** [comment]
> What's the issue preventing you from using Plasma Wayland exactly? Both GNOME and KDE have support for ICC color profiles under Wayland now.

Honestly. I can’t keep up with the “why’s” anymore. It’s a mess. I can however understand from [this thread](https://discuss.pixls.us/t/wayland-color-management/10804/712?u=mikae1) (go from the latest messages and back in time if you’re interested) that my spectrophotometer with [DisplayCAL](https://displaycal.net/) will not give a result that I can trust and the apps I use (mainly darktable) will be capped to sRGB. I’m not a developer.

Here’s [a recent quote](https://discuss.pixls.us/t/wayland-color-management/10804/670?u=mikae1):
> Now tell me are the fedora devs working on colour management that they spread this falsehood or do we believe the actual developers who are working on things? Yes I agree i have seen that MR they link the person who tested used display cal to calibrate but it is not accurate because there are issues with argyll cms which is used by display cal we can’t be sure that the measurement are accurate. Moreover even fedora devs accept there is no implementation on the application side. So knowing this truth why do they spread falsehood like saying it is on [par with X11 1](https://mail.kde.org/pipermail/plasma-devel/2023-October/123201.html) and then use this to justify dropping X11 without fallback? So no amount of pointless rebuttal from the fedora team counters the two point that I mentioned in my post above. Colour profiling and calibration is not ready right now. All or most apps are now in legacy mode which is sRGB only ( if they blame applications, a user does not care whose fault it is, they need things to work)

**Comment by fiftydinar** [comment]
> I am Fedora KDE maintainer and despite us not supporting `plasma-workspace-x11` I also wonder where:
> 
> ```
> From my understanding it will be completely gone in F41, not even installable...
> ```
> 
> is coming from.
> 
> If you are gonna scare people away, at least provide sources to backup your claims

I agree that's false.

I think that X11 session set of packages will be installable from COPR repos, as someone will hopefully maintain that.

**Comment by noelmiller** [comment]
> I am Fedora KDE maintainer and despite us not supporting `plasma-workspace-x11` I also wonder where:
> 
> ```
> From my understanding it will be completely gone in F41, not even installable...
> ```
> 
> is coming from.
> 
> If you are gonna scare people away, at least provide sources to backup your claims

It is not installed by default in F40 and will be removed in F41: https://news.itsfoss.com/fedora-41-to-drop-xorg/

**Comment by KyleGospo** [comment]
> I am Fedora KDE maintainer and despite us not supporting `plasma-workspace-x11` I also wonder where:
> 
> ```
> From my understanding it will be completely gone in F41, not even installable...
> ```
> 
> is coming from.
> 
> If you are gonna scare people away, at least provide sources to backup your claims

https://fedoraproject.org/wiki/Changes/KDE_Plasma_6#Why_drop_the_X11_session?
https://discussion.fedoraproject.org/t/f40-change-proposal-kde-plasma-6-system-wide/89794/11

**Comment by KyleGospo** [comment]
> > I think that X11 session set of packages will be installable from COPR repos, as someone will hopefully maintain that.
> 
> And it can easily be layered from there with the Kinoite image?

Yes, since we'd have nothing installed on that front you should be able to layer anything you like.

**Comment by KyleGospo** [comment]
> > What's the issue preventing you from using Plasma Wayland exactly? Both GNOME and KDE have support for ICC color profiles under Wayland now.
> 
> Honestly. I can’t keep up with the “why’s” anymore. I’m not a developer and it’s a mess. I can however understand from [this thread](https://discuss.pixls.us/t/wayland-color-management/10804/712) (go from the latest messages and back in time if you’re interested) that my spectrophotometer with [DisplayCAL](https://displaycal.net/) will not give a result that I can trust and the apps I use (mainly darktable) will be capped to sRGB.
> 
> Here’s [a recent quote](https://discuss.pixls.us/t/wayland-color-management/10804/670?u=mikae1):
> 
> > Now tell me are the fedora devs working on colour management that they spread this falsehood or do we believe the actual developers who are working on things? Yes I agree i have seen that MR they link the person who tested used display cal to calibrate but it is not accurate because there are issues with argyll cms which is used by display cal we can’t be sure that the measurement are accurate. Moreover even fedora devs accept there is no implementation on the application side. So knowing this truth why do they spread falsehood like saying it is on [par with X11 1](https://mail.kde.org/pipermail/plasma-devel/2023-October/123201.html) and then use this to justify dropping X11 without fallback? So no amount of pointless rebuttal from the fedora team counters the two point that I mentioned in my post above. Colour profiling and calibration is not ready right now. All or most apps are now in legacy mode which is sRGB only ( if they blame applications, a user does not care whose fault it is, they need things to work)

You might want to give it a shot
https://discussion.fedoraproject.org/t/f40-change-proposal-kde-plasma-6-system-wide/89794/22

**Comment by mikae1** [comment]
> Yes, since we'd have nothing installed on that front you should be able to layer anything you like.

Thanks. Seems a bit shaky considering the following though:
> https://fedoraproject.org/wiki/Changes/KDE_Plasma_6#Why_drop_the_X11_session? 
> https://discussion.fedoraproject.org/t/f40-change-proposal-kde-plasma-6-system-wide/89794/11

> It is not installed by default in F40 and will be removed in F41: https://news.itsfoss.com/fedora-41-to-drop-xorg/

Thanks for confirming.

**Comment by marcdeop** [comment]
> > I am Fedora KDE maintainer and despite us not supporting `plasma-workspace-x11` I also wonder where:
> > ```
> > From my understanding it will be completely gone in F41, not even installable...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > is coming from.
> > If you are gonna scare people away, at least provide sources to backup your claims
> 
> It is not installed by default in F40 and will be removed in F41: https://news.itsfoss.com/fedora-41-to-drop-xorg/

This link is only talking about Fedora Workstation which has no control over the packages that are available to the users (exactly the same as we, the kde sig, do not have control over `plasma-workspace-x11`)

**Comment by mikae1** [comment]
> but you can calibrate with the X11 session and then use your calibration under Wayland.

Thanks, but with darktable and the software I use I’d be capped to sRGB on a wide gamut display? That’s a no from me.

**Comment by marcdeop** [comment]
> > I am Fedora KDE maintainer and despite us not supporting `plasma-workspace-x11` I also wonder where:
> > ```
> > From my understanding it will be completely gone in F41, not even installable...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > is coming from.
> > If you are gonna scare people away, at least provide sources to backup your claims
> 
> https://fedoraproject.org/wiki/Changes/KDE_Plasma_6#Why_drop_the_X11_session? https://discussion.fedoraproject.org/t/f40-change-proposal-kde-plasma-6-system-wide/89794/11

That only says that we, the KDE SIG, do not support those packages (and we actually do not want them existing).

However, contributors are maintaining the packages themselves because the Fedora rules allow them to do so

**Comment by KyleGospo** [comment]
> > > I am Fedora KDE maintainer and despite us not supporting `plasma-workspace-x11` I also wonder where:
> > > ```
> > > From my understanding it will be completely gone in F41, not even installable...
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > is coming from.
> > > If you are gonna scare people away, at least provide sources to backup your claims
> > 
> > 
> > https://fedoraproject.org/wiki/Changes/KDE_Plasma_6#Why_drop_the_X11_session? https://discussion.fedoraproject.org/t/f40-change-proposal-kde-plasma-6-system-wide/89794/11
> 
> That only says that we, the KDE SIG, do not support those packages (and we actually do not want them existing).
> 
> However, contributors are maintaining the packages themselves because the Fedora rules allow them to do so

Yes, "not installable" is incorrect, but that is also not a scenario I would ship to an end user by default under any circumstance. uBlue's position is we will honor the KDE SIG's wishes.

**Comment by marcdeop** [comment]
I encourage anybody who needs something specific to come to our Matrix channel #kde:fedoraproject.org and talk to us and to the KDE devs so we can provide whatever is missing for you to enjoy the wayland session :-)

**Comment by mikae1** [comment]
> I encourage anybody who needs something specific to come to our Matrix channel #kde:fedoraproject.org and talk to us and to the KDE devs so we can provide whatever is missing for you to enjoy the wayland session :-)

I did that some months ago. 🙂 Thanks again for caring. I hope that some day Wayland will do the job.

> You might want to have a look at Aurora, since they have added X11 back.

 Thanks again @p5 @noelmiller and @HikariKnight for the Aurora recommendation, it actually looks exactly like the image I’ve been looking for! 💫

It seems like Aurora will be the choice for my image editing workstation. I’ll pray to the Fedora overlords that the X11 packages will stay in there. 🙂 Not everyone is a gamer or a developer, please remember that when you consider whether it should stay or go. 💕
