### ISSUE TITLE
Add Initramfs build to all images

### ISSUE THREAD

**Issue by m2Giles** [ublue-os/main#593]
### Describe the package

Currently a user will have to create a local initramfs if they wish to use tpm2, fido, and pkcs11 for LUKs deceyption.

### Information on the package

We've been building a custom initramfs in bluefin and Bazzite for a few months. With Nvidia now requiring early loading for Wayland support in Gnome, we are now building a custom initramfs in all but our main images.

Since we are already building them, we can enable hardware support.

### Image

All Images

**Comment by bsherman** [comment]
I've chatted with @KyleGospo a bit about this topic.

First, I 100% think we should be adding support for tpm2/fide/pkcs11 LUKS ulock to our dracut configs... and given we already have an RPM related to this ( see https://github.com/ublue-os/config/tree/main/build/ublue-os-luks ), I think we can accomplish that goal by adding this [file from bazzite](https://github.com/ublue-os/bazzite/blob/341941bb54ba8e3650bcf3ee82f6167edb986f53/system_files/desktop/shared/usr/lib/dracut/dracut.conf.d/90-ublue.conf) to the config repo for the ublue-os-luks RPM build. I'd probably rename it to `90-ublue-luks.conf`.

Second, I'm having doubts about actually building the initramfs as part of the main image. By adding the config file, we'll be enabling this for any user who runs `main` and chooses to build it at runtime, plus enabling all downstreams (including hwe, bazzite, bluefin/aurora) to automatically get this benefit, BUT... by building initramfs in `main` we'll add a few hundred MB to that image which also gets wasted in all the downstreams. 

Perhaps we add documentation for anyone who REALLY wants to run `main` images on how to rebuild this... as well as adding some support for this to our [image template](https://github.com/ublue-os/image-template).

**Comment by p5** [comment]
Adding the required configs but leaving the generation sounds good to me.

We probably already do it ourselves everywhere, but we should document that it's good to make a habit of calling the generation as one of the final commands in any downstream build.

**Comment by bsherman** [comment]
> We probably already do it ourselves everywhere, but we should document that it's good to call the generation as one of the final commands in any downstream build.

Yes, where to do that documentation is one of my outstanding unknowns.
