### ISSUE TITLE
update all cosign public key files/references in ublue-os org repos

### ISSUE THREAD

**Issue by bsherman** [ublue-os/main#599]
Due to cosign key rotation, all cosign pub key files in repos must be updated:

At the least, this includes files in:
- https://github.com/ublue-os/config - https://github.com/ublue-os/config/pull/296
- https://github.com/ublue-os/main - https://github.com/ublue-os/main/pull/601
- https://github.com/ublue-os/hwe - https://github.com/ublue-os/hwe/pull/261
- https://github.com/ublue-os/bazzite - https://github.com/ublue-os/bazzite/pull/1314
- https://github.com/ublue-os/bluefin - https://github.com/ublue-os/bluefin/pull/1483
- https://github.com/ublue-os/akmods - https://github.com/ublue-os/akmods/pull/210
- https://github.com/ublue-os/ucore - https://github.com/ublue-os/ucore/pull/169
- https://github.com/ublue-os/ucore-akmods - https://github.com/ublue-os/ucore-kmods/pull/19
- https://github.com/ublue-os/fsync - https://github.com/ublue-os/fsync/pull/4
- https://github.com/ublue-os/toolboxes - https://github.com/ublue-os/toolboxes/pull/109
- https://github.com/ublue-os/bazzite-arch - https://github.com/ublue-os/bazzite-arch/pull/37
- https://github.com/ublue-os/arch-distrobox - https://github.com/ublue-os/arch-distrobox/pull/5
- https://github.com/ublue-os/fedora-distrobox - https://github.com/ublue-os/fedora-distrobox/pull/10
- ... ADD OTHER REPOS TO THIS LIST ...

**Comment by p5** [comment]
Images to attempt to resign (please add to this list as and when you think of them):

- From @HikariKnight - last f39 Bazzite due to Polaris cards

**Comment by bsherman** [comment]
I believe we've wrapped this up....

a few other repos were updated outside this ticket, but the situation has been resolved.
