### ISSUE TITLE
Prune inactive members

### ISSUE THREAD

**Issue by castrojo** [ublue-os/main#618]
Alright, now that donations are covering the infra costs we need to trim inactive members in the GitHub org. Part of the reason to do this now is we need more builders. Trimming the list will let us move to the GitHub enterprise plan which gets us 500 concurrent builders instead of the 60 we have now.  

- When F41 goes beta we'll be building adding another version across the org, that's 33% more demand
- Bluefin or Bazzite can each max out the builders in one PR/merge. Concurrent development isn't fun, and if you have to kick off akmods/kernel-cache we can easily hit a queue

On the plus side we'll be able to kill surface images with the fsync kernel being available. Ok back to the membership, here's what I propose:

First we'll create an EMERITUS.md with each person - the governance allows anyone to just come back after periods of inactivity anyway, so this effectively becomes our running log of contributors. I'll make sure we include jstone too. 

## Should Move to Approvers
Might as well have this reflect reality. Both are doing multiple work across repos, and should apply for approver. Can another approver file a seperate nomination for each?

@HikariKnight
@m2Giles 

## Move to Emeritus 
(Living the Chillops dream)

@bobslept 
@akdev1l 
@bigpod98

**Comment by bigpod98** [comment]
Yea i agree i should be moved to some sort of inactive as well i really dont do anything

**Comment by bketelsen** [comment]
sounds good to me!

**Comment by bsherman** [comment]
@castrojo I have filed nominations for new members and agree with the creation of an "Emeritus" title and moving "chill ops" members to it.

See:
- #619 
- #620

**Comment by KyleGospo** [comment]
+1

**Comment by gerblesh** [comment]
LGTM

**Comment by xynydev** [comment]
I don't make much code contributions, but appear to still be part of the org. Possibly another candidate for pruning then? I still read the GitHub and Dircord actively.

**Comment by castrojo** [comment]
I'd like to keep you active xyny, the diagram has been clutch in many occasions, worth it!

**Comment by castrojo** [comment]
Implemented, thanks everyone.
