### ISSUE TITLE
Approver Nomination for Mark Mihalik

### ISSUE THREAD

**Issue by bsherman** [ublue-os/main#619]
Per our [project governance doc](https://universal-blue.discourse.group/t/universal-blue-project-governance/51/3), I nominate Mark Mihalik ( @m2giles ) for approver role in the Universal Blue organization.

He's been a long contributing member who repeatedly jumps in to help others, contributing PRs of his own, and giving feedback on others' PRs. While initially being active in Bluefin, his efforts have grown to substantially impact and improve the entire project.

cc @ublue-os/approver @ublue-os/member

**Comment by castrojo** [comment]
+1

**Comment by p5** [comment]
Definite 👍

**Comment by castrojo** [comment]
Oh and also, kernel-cache!!

**Comment by HikariKnight** [comment]
+1 for sure

**Comment by noelmiller** [comment]
+1

**Comment by KyleGospo** [comment]
+1

**Comment by gerblesh** [comment]
+1

**Comment by EyeCantCU** [comment]
+1!

**Comment by castrojo** [comment]
Done!
