### ISSUE TITLE
Approver Nomination for HikariKnight

### ISSUE THREAD

**Issue by bsherman** [ublue-os/main#620]
Per our [project governance doc](https://universal-blue.discourse.group/t/universal-blue-project-governance/51/3), I nominate HikariKnight ( @HikariKnight ) for approver role in the Universal Blue organization.

A long contributing member, he helps others, contributes PRs of his own, and provides feedback on others' PRs. While very active in the Bazzite, he has also contributed to config, akmods, bluefin, and maybe more.

cc @ublue-os/approver @ublue-os/member

**Comment by castrojo** [comment]
+1!

**Comment by p5** [comment]
+1 🪨

**Comment by noelmiller** [comment]
+1

**Comment by KyleGospo** [comment]
+1

**Comment by m2Giles** [comment]
+1

**Comment by gerblesh** [comment]
+1

**Comment by EyeCantCU** [comment]
+1

**Comment by castrojo** [comment]
Done!
