### ISSUE TITLE
[FEAT] set no-install-recommends by default across ublue

### ISSUE THREAD

**Issue by qoijjj** [ublue-os/main#632]
As of rpm-ostree 2024.7, this is available:

https://github.com/coreos/rpm-ostree/pull/4974

**Comment by castrojo** [comment]
Can we figure out a way to see what would be dropped on the images when using this? 

I'd love to have this on but don't want to wake up one day and a tool someone depends on is missing without giving people a heads up.

**Comment by qoijjj** [comment]
@castrojo For sure, I'm testing it now. Gonna generate a set of `main` images with my patched config, then rebase between the two and see what the delta is.

That will only get us part of the way there though, since this will affect every `rpm-ostree install` call across all of ublue, from main to hwe to bluefin to bazzite

**Comment by castrojo** [comment]
Yeah if you wouldn't mind documenting the steps we could spread the work, as I'm sure custom image builders would want to know how to check. Thanks!

**Comment by qoijjj** [comment]
interesting findings so far:

![image](https://github.com/user-attachments/assets/c1483d49-2732-415f-a70d-833de2543988)
![image](https://github.com/user-attachments/assets/00802da6-fa50-43e9-8746-eea3074d414c)

This means that either none of the packages installed in ublue-os/main have any recommends (which seems unlikely) or rpm-ostree being called in packages.sh is ignoring the rpm-ostreed.conf installed into the image earlier in the containerfile.

@castrojo do you know which config file rpm-ostree reads from when called from the containerfile inside buildah?

**Comment by KyleGospo** [comment]
> interesting findings so far:
> 
> ![image](https://github.com/user-attachments/assets/c1483d49-2732-415f-a70d-833de2543988)
> ![image](https://github.com/user-attachments/assets/00802da6-fa50-43e9-8746-eea3074d414c)
> 
> This means that either none of the packages installed in ublue-os/main have any recommends (which seems unlikely) or rpm-ostree being called in packages.sh is ignoring the rpm-ostreed.conf installed into the image earlier in the containerfile.
> 
> @castrojo do you know which config file rpm-ostree reads from when called from the containerfile inside buildah?

It's ignored, found that a few months ago when I built rpm-ostree and upgraded mine to test this.

**Comment by qoijjj** [comment]
> It's ignored, found that a few months ago when I built rpm-ostree and upgraded mine to test this.

why is it ignored? and how can we make it not? :smile:

**Comment by qoijjj** [comment]
it's ignored because rpm-ostreed isn't running because systemd isn't:

```
System has not been booted with systemd as init system (PID 1). Can't operate.
```

**Comment by qoijjj** [comment]
tried `rpm-ostree reload` and `rpm-ostree start-daemon`

neither works because the daemon can't be run from inside the container.

@castrojo @KyleGospo I think we can just go ahead and merge the rpm-ostreed.conf change. It won't do anything in our builds, but it will affect local user layers which is better than nothing

**Comment by fiftydinar** [comment]
I know some Gnome extension recommends Gnome Extensions app as an example

Very dirty if you have Extension Manager already installed
