### ISSUE TITLE
Desktop Entry for `ujust --choose`

### ISSUE THREAD

**Issue by Malix-off** [ublue-os/main#633]
# Feature Request

A desktop entry directly launching `ujust --choose`
This would definitely make Universal Blue more user-friendly

**Comment by castrojo** [comment]
main images are mostly stock, we don't add menu entries, etc. here.

**Comment by Malix-off** [comment]
@castrojo sorry about that ; could you transfer the issue in the right repository for me ?

**Comment by castrojo** [comment]
I'm not sure which repo this would go in.

Bazzite includes most of their commands in their GUI config tool and
bluefin purposely wouldn't expose this in the menu as it's day 1 stuff.

**Comment by Malix-off** [comment]
> Bazzite includes most of their commands in their GUI config tool

I guess at least it would correspond more to Bluefin and Aurora than Bazzite
I'm not sure about uCore, never tried it nor know if there are some `ujust` / `ujust --choose` commands

> Bluefin purposely wouldn't expose this in the menu as it's day 1 stuff

I guess you are referring to https://docs.projectbluefin.io/introduction#day-1---deployment-and-configuration
Do you mean that `ujust` is **only** meant as a day 1 tool and not meant to be used afterwards?

**Comment by Malix-off** [comment]
@castrojo ⬆️

**Comment by castrojo** [comment]
Yeah there's no reason to put this in the menu, it implies that people are using ujust regularly, those are there for workarounds and for initial setup.

**Comment by Malix-off** [comment]
Understandable
