### ISSUE TITLE
Mouse/Music stutter when starting many docker containers

### ISSUE THREAD

**Issue by tomrutsaert** [ublue-os/main#644]
### Describe the bug

I’ve experienced stuttering issues with my desktop environment, specificly when running Docker containers or performing Maven builds (that use Docker test-containers in tests), on three different UBlue-based operating systems (Aurora, Bluefin-DX, and a custom Sway image) on two separate machines.

The culprit is /lib/udev/rules.d/30-linksys-ae1200.rules 
overriding this file by placing an empty file in /etc/udev/rules.d/30-linksys-ae1200.rules, the stuttering goes away. 

This was experienced by 3 different users, and the workaround fixes it for all.

More info see: https://universal-blue.discourse.group/t/mouse-music-stutter-when-starting-many-docker-containers/3470

### What did you expect to happen?

I did not expect any stutter, as fedora workstation 40 for the same workload also does not have the stutter.

**Comment by bsherman** [comment]
I've created a PR with the revert for the problematic rule.

Users which desire it can certainly create it locally, but it's far too problematic to exist by default IMHO.

**Comment by bsherman** [comment]
This was resolved by https://github.com/ublue-os/config/commit/2c66163f748d46ce85bfe8701213f8a9cfd60ffd
