### ISSUE TITLE
[Nvidia] could not perform rpm-ostree update

### ISSUE THREAD

**Issue by kdwk** [ublue-os/main#647]
```
Pulling manifest: ostree-image-signed:docker://ghcr.io/ublue-os/silverblue-nvidia:latest
error: Creating importer: Failed to invoke skopeo proxy method OpenImage: remote error: cryptographic signature verification failed: invalid signature when validating ASN.1 encoded signature
```

**Comment by p5** [comment]
Hey
I'm guessing your image hasn't had an update in quite some time.

Please find remediation steps and an explanation about what happened in this Discourse post
https://universal-blue.discourse.group/t/important-announcement-regarding-system-updates-action-needed/2689

Apologies for the inconvenience

**Comment by p5** [comment]
Since I've not heard back, and those docs have been used by many others who had the same issue, I'll close this issue.
Please @p5 if it's still not resolved.
