### ISSUE TITLE
ISO Generator

### ISSUE THREAD

**Issue by marcoceppi** [ublue-os/main#68]
Create a GHA
min ks from each repo
defines the location of custom image
slipstream into fedora iso
mkksiso
each of these is 560mb net installer for each flavor of image
attach to each release

installer checks if it's nvidia and can determine if it's an nvidia machine

**Comment by marcoceppi** [comment]
Blocked on: https://github.com/rhinstaller/anaconda/pull/4561

**Comment by akdev1l** [comment]
We have ISOs that work on most conditions now, there's still some work left but I think we can track that separately

**Comment by akdev1l** [comment]
I want to leave it open until we either figure out how to make downstream images work or we put bluefin on the existing iso
