### ISSUE TITLE
Need  a way to enable vi instead of nano easily

### ISSUE THREAD

**Issue by wiltaylor** [ublue-os/main#698]
Need a ujust script or something to globally enable vi instead of nano for everything. I get using nano by default because its easier for new users but if you have learnt the muscle memory of vi having to use nano is really frustrating and something I would like to avoid.

I have set it in my bashrc but when I do things with root like systemctl --edit it keeps coming back. Would be nice if this was a ujust script that could be enabled when you instal your system to just set everything back to vi instead of nano.

**Comment by m2Giles** [comment]
Set EDITOR=vim in /etc/environment or edit /etc/profile.d file that sets it.
