### ISSUE TITLE
AKMods/Nvidia Split

### ISSUE THREAD

**Issue by marcoceppi** [ublue-os/main#71]
https://github.com/orgs/ublue-os/discussions/106

**Comment by bsherman** [comment]
There's been generic work for adding `akmods` support:
pending PRs:
- https://github.com/ublue-os/akmods/pull/1
- https://github.com/ublue-os/nvidia/pull/72

@dhoell and I have discussed working to move this forward.

**Comment by bsherman** [comment]
This blocks #46

**Comment by castrojo** [comment]
Ref: https://github.com/ublue-os/nvidia/issues/100

**Comment by bsherman** [comment]
I've been working on this akmod stuff and the key split:

current status:
- `config` repo provides `just` commands to import new akmod key AND legacy nvidia key
- `akmods` repo signs kmods with new key (and provides key in RPM)
- the installer ISO installs BOTH old and new key
- `nvidia` repo signs nvidia kmods with old key (and provides both old and new key in RPM)

PR I'll post shortly in draft mode will:
- cutover `nvidia` to new signing key on June 17 (waiting users a chance to install new key)

**Comment by bsherman** [comment]
Welcome!  I think technically the "split" won't happen until after June 17 when i move the nvidia akmod building from `nvidia` to `akmods` repo... but, i'll take credit now ;-)
