### ISSUE TITLE
BUG: Some symlinks missing from the OCI images (Can't add printer via SMB)

### ISSUE THREAD

**Issue by celsomiranda** [ublue-os/main#77]
Hi.

As discussed over on Discord. I've been having this wierd bug with images based on `main`, including itself.

If I go to CUPS admin in [http://localhost:631/](http://localhost:631/) there is no option `Windows Printer via SAMBA` under `Add Printer > Other Network Printers`.

This doesn't happen on a vanilla fresh install of Silverblue.

The output of `rpm -qa '*samba*'` is the same on both systems:
```sh
samba-common-4.17.6-0.fc37.noarch
samba-client-libs-4.17.6-0.fc37.x86_64
samba-common-libs-4.17.6-0.fc37.x86_64
samba-client-4.17.6-0.fc37.x86_64
```
Both systems are freshly installed side by side so I can test the differences between the two.

**Comment by celsomiranda** [comment]
### Output of `rpm -qa --queryformat '%{NAME}\n' | sort`

#### quay.io/fedora-ostree-desktops/silverblue:37
[vanilla-sb-quay.io-oci-image-packages.txt](https://github.com/ublue-os/main/files/10993204/vanilla-sb-quay.io-oci-image-packages.txt)

#### vanilla ublue-main
[ublue-all.txt](https://github.com/ublue-os/main/files/10993207/ublue-all.txt)

**Comment by castrojo** [comment]
Let's keep this open for now as a reminder and then see how the move to quay.io/fedora goes over the next few days and then see if the images still differ.

**Comment by vrothberg** [comment]
https://github.com/fedora-sysv/chkconfig/pull/135 has been merged which should fix the issue.
