### ISSUE TITLE
Rebase onto quay.io/fedora images

### ISSUE THREAD

**Issue by castrojo** [ublue-os/main#78]
We've been using the images at: quay.io/fedora-ostree-desktops/ 
The new location is: quay.io/fedora/fedora-silverblue (as an example)

This issue is to track that change.

See also https://pagure.io/releng/issue/11047#comment-846909

**Comment by castrojo** [comment]
This won't be for 1.0, the quay.io/fedora namespace is only doing 39 and rawhide so it's unlikely they'll backfill that, so we'll revisit for F39.

**Comment by castrojo** [comment]
Just realized that the quay.io/fedora images will be 39 only and probably only official images, so we'd probably prefer quay.io/fedora images for everything they provide, but fall back to quay.io/silverblue-desktops to backfill the catalog with other desktops.

**Comment by john-ghatas** [comment]
What does using images from quay.io/silverblue-desktops mean? Updates that are a day ish behind for example?

**Comment by castrojo** [comment]
quay.io/silverblue-desktops are unofficial images, Fedora is in the process of making official images but they will live in quay.io/fedora. So at some point we'll switch to those images when Fedora says they're ready. For now we're assuming that they're still going to remain being daily builds.

**Comment by bsherman** [comment]
Also, maybe the question relates to use of `quay.io/fedora-ostree-desktops` vs  `quay.io/silverblue-desktops` ?

I don't know that `quay.io/silverblue-desktops` exists (if so, please show me what I'm missing), because we are currently using `quay.io/fedora-ostree-desktops` and I think maybe you just wrote the former by accident?

**Comment by castrojo** [comment]
Ooops yea, pre-caffeinated comment, I meant `quay.io/fedora-ostree-desktops`

**Comment by castrojo** [comment]
Fedora has official container builds now for some of them here:

https://quay.io/organization/fedora

We need to special case slurping in silverblue,kinoite,and sericea

**Comment by bsherman** [comment]
I was eager to do this, but I want to hold off for a bit... the recent big changes to organization and the in-flight F39 stuff seems like a bad time to introduce more complexity. I'd like to see some stability before adding this change.

**Comment by noelmiller** [comment]
I would like to reopen this for discussion. There are official images available for [silverblue](https://quay.io/repository/fedora/fedora-silverblue) and [kinoite](https://quay.io/repository/fedora/fedora-kinoite). 

Are there any technical barriers to us moving to using the official images for our Silverblue and Kinoite based variants?

**Comment by bsherman** [comment]
> I would like to reopen this for discussion. There are official images available for [Silverblue](https://quay.io/repository/fedora/fedora-silverblue) and [Kinoite](https://quay.io/repository/fedora/fedora-kinoite).

I don't think these images are any more official today as they were when I implemented the PR for it in #363 ... and then Timothee suggested holding off... so we backed away... as he is the one maintaining our current upstream at https://quay.io/repository/fedora-ostree-desktops/  I not too eager to switch until he thinks it good.

> Are there any technical barriers to us moving to using the official images for our Silverblue and Kinoite based variants?

As I mentioned, I've already implemented this once. The only real technical issue is the "official" images are currently only Silverblue/Kinoite, not any of the other upstream spins (Sericea, Onyx, etc), and certainly not an upstream `base` image.

So it's doable, but a minor headache as some of our images would be "more official" than others due to a different upstream source.

**Comment by noelmiller** [comment]
> I don't think these images are any more official today as they were when I implemented the PR for it in #363 ... and then Timothee suggested holding off... so we backed away... as he is the one maintaining our current upstream at https://quay.io/repository/fedora-ostree-desktops/ I not too eager to switch until he thinks it good.

I 100% agree and I would even debate not switching to the "official images" until F40 so we aren't switching mid-release.

> As I mentioned, I've already implemented this once. The only real technical issue is the "official" images are currently only Silverblue/Kinoite, not any of the other upstream spins (Sericea, Onyx, etc), and certainly not an upstream `base` image.
> 
> So it's doable, but a minor headache as some of our images would be "more official" than others due to a different upstream source.

Yeah, that would be a headache. 

What might be valuable is if we can get a better understanding on where the initiative is at from Fedora themselves. I'm curious who is responsible for the Atomic Desktops in general at the project and where we can look to get updates on Atomic Desktop related things. I do know the [Fedora Discourse](https://discussion.fedoraproject.org/) and [Matrix](https://chat.fedoraproject.org/) exists (I'm just not sure who monitors those channels). There is also an [issue tracker](https://github.com/fedora-silverblue/issue-tracker/issues) 

It would be helpful if they had like a project board or something to view so we can get a better idea of where their priorities are. Or even a conversation with a Project PM for Atomic Desktops would be helpful too!

Just some thoughts I had.

**Comment by travier** [comment]
This is our main issue tracker for Atomic desktops: https://gitlab.com/fedora/ostree/sig/-/issues
For this issue (https://gitlab.com/fedora/ostree/sig/-/issues/2) ,we now produce the images (ociarchives) and we need to sync them to quay.io. Once we have that, Ublue can start using them.

Fedora only produces Silverblue, Kinoite, Sericea & Onyx right now so the other images will likely have to stay on the experimental ones for now. I can keep building a subset of the images until they're made official in Fedora.

**Comment by castrojo** [comment]
We're just going to stick to fedora-ostree-desktops and encourage people to work out of that repo.

**Comment by bsherman** [comment]
@castrojo by closing this do you mean this will never be a goal to use Fedora upstream, or not for F40, or not for at least a few releases?

The answer matters to me because if we don't even have this goal anymore I'll rip out some code which has been staged for the switch.

**Comment by castrojo** [comment]
I'd love to say short term but it's been three cycles, dunno man, up to you. I'm totally ok with a "never unless things get better" if you are lol.

**Comment by bsherman** [comment]
Fine with me, I just wanted to make sure I'm tracking with you. 

If we are thinking long term, I'll cleanup that extra build code because it's annoying to maintain.

**Comment by travier** [comment]
I would say: don't ditch the code! We're getting really close :)

**Comment by castrojo** [comment]
Al this rate we're never going to go on vacation lol.

**Comment by bsherman** [comment]
> I would say: don't ditch the code! We're getting really close :)

:) it's always in the git history and it's not complex.
