### ISSUE TITLE
[Bug] you can't install akmod-wl

### ISSUE THREAD

**Issue by dnkmmr69420** [ublue-os/main#85]
When I install akmod-wl on my laptop using the silverblue-main:37 image, I get the following error. It works fine on the official silverblue image but this error apears on ublue. To reproduce, install silverblue, rebase to silverblue-main:37 image, type `sudo rpm-ostree install akmod-wl` then you get this error. The same thing happens on my laptop and in a vm.

`Downloading from 'rpmfusion-nonfree'... done
Importing packages... done
Checking out packages... done
Running pre scripts... done
Running post scripts... done
error: Running %post for akmod-wl: bwrap(/bin/sh): Child process killed by signal 1; run `journalctl -t 'rpm-ostree(akmod-wl.post)'` for more information`

**Comment by sekalengrengginang** [comment]
can you run  `journalctl -t 'rpm-ostree(akmod-wl.post)'` and send the output in github gist?

**Comment by bsherman** [comment]
Hi @dnkmmr69420 , I noticed you wanted the `wl` akmod.

Not sure if you got any further with this, but akmods can't be built trivially with an `rpm-ostree install` as on Fedora Workstation.

That's part of why the ublue-os project exists, trying to take some of that headache out of the system.

I know the team is working on a process to enable more akmods, but in the meantime, I added `akmod-wl` to the kmods I'm building on my image.  https://github.com/bsherman/ublue-kmods/

If you are interested in how the build process works, take a look at the changes I made to add this new akmod to what I was already doing: https://github.com/bsherman/ublue-kmods/pull/1/files

Hope it's helpful!

**Comment by bsherman** [comment]
@dnkmmr69420 bonus! 

We just added this driver to the new ublue akmods repo so it'll be in all ublue main and derivative images after the next build cycle.

**Comment by dnkmmr69420** [comment]
that's good

**Comment by xalt7x** [comment]
@castrojo , can you please reopen it?
I have exactly the same issue.

Reproduced with such steps:
1. clean install from  "universalblue-38-x86_64-20230701.iso"
2. `rpm-ostree update`
3. Restart
4. `rpm-ostree install akmod-wl`

My logs bellow (actually they're the same as @dnkmmr69420 [had](https://github.com/ublue-os/main/issues/85#issuecomment-1479806457))
[akmod-wl_rpm-ostree_output.txt](https://github.com/ublue-os/main/files/12269064/akmod-wl_rpm-ostree_output.txt)
[akmod-wl_journalctl_output.txt](https://github.com/ublue-os/main/files/12269065/akmod-wl_journalctl_output.txt)

P.S. After [rebasing to Fedora Silverblue 38](https://communityblog.fedoraproject.org/how-to-rebase-to-fedora-silverblue-38-beta/) & [adding RPMFusion](https://docs.fedoraproject.org/en-US/quick-docs/setup_rpmfusion/#proc_enabling-the-rpmfusion-repositories-for-ostree-based-systems_enabling-the-rpmfusion-repositories) installation succeed.
P.P.S. I guess until this issue is resolved users need to fork repo and enable required RPMs (as mentioned [here](https://github.com/ublue-os/akmods/pull/46#issuecomment-1648516368))

**Comment by bsherman** [comment]
@xalt7x  I'm going to close this issue again. The original problem described here and as you describe, is not a problem with Universal Blue. What y'all have described is the general difficulty of using dynamically built kmods on an immutable  system, specifically Fedora Silverblue/CoreOS/etc.

We did briefly include `akmod-wl` in the Universal Blue main images, before realizing when installed it prevents newer broadcom wireless devices from working.

> P.P.S. I guess until this issue is resolved users need to [produce custom image](https://github.com/ublue-os/startingpoint), fork akmod repo and https://github.com/ublue-os/akmods/pull/46#issuecomment-1648516368 required RPMs.

You have started to reference the recommended process here. 

If you want to build akmods not provided in our [akmods repo](https://github.com/ublue-os/akmods), you can fork and add to it. However, I'd suggest the following if you desire a kmod we provide, such as the legacy broadcom wl driver:

Generally speaking, please follow these instructions: https://github.com/ublue-os/akmods/blob/main/README.md?plain=1#L11-L13

But those instructions will have you installing every kmod available. In general, you probably only want to add one or a few from that repo.

Using those instructions as a template, I'd change it to look like this:
```
# Run the build script, then clean up temp files and finalize container build.
COPY --from=ghcr.io/ublue-os/akmods:${FEDORA_MAJOR_VERSION} /rpms/ /tmp/rpms
RUN rpm-ostree install /tmp/ublue-os-wallpapers-0.1-1.fc38.noarch.rpm && \
        chmod +x /tmp/scripts/build.sh && \
        /tmp/scripts/build.sh && \
        rpm-ostree install /tmp/rpms/kmods/kmod-wl-*.rpm && \
        rm -rf /tmp/* /var/* && \
        ostree container commit
```

This presupposes you will build a custom image based on `silverblue-main`, `kinoite-main`, etc which has rpmfusion repo enabled by default.

**Comment by bsherman** [comment]
Also, I did file this ticket to remind us to improve the readme in akmods  https://github.com/ublue-os/akmods/issues/49

**Comment by xalt7x** [comment]
> The original problem described here and as you describe, is not a problem with Universal Blue. What y'all have described is the general difficulty of using dynamically built kmods on an immutable system, specifically Fedora Silverblue/CoreOS/etc.

Well, as a user I can say that:
1) On Fedora Silverblue after [RPM Fusion setup](https://docs.fedoraproject.org/en-US/quick-docs/setup_rpmfusion/#proc_enabling-the-rpmfusion-repositories-for-ostree-based-systems_enabling-the-rpmfusion-repositories) I'm able to install "akmod-wl" and it even survives release upgrades.
2) On "Universal Blue" simple installation of that package didn't work.
---
Is there any way to resolve this without building custom image?

**Comment by bsherman** [comment]
> Well, as a user I can say that:
> 2) On "Universal Blue" simple installation of that package doesn't work.

I do appreciate the distinction, thank you  for clarifying. 

> Is there any way to resolve this without building a custom image?

My guess is this is one of the quirky problems with our unofficial upstream images. Every time we find one of those, it's just work to find out exactly what isn't working, how the upstream image differs from standard, and fix/mitigate it if possible. 

I'll reopen, sorry for rushing to re-close.

**Comment by xalt7x** [comment]
Can we debug this issue somehow?
Looks like any random akmod from RPMFusion ([free](https://download1.rpmfusion.org/free/fedora/releases/38/Everything/x86_64/os/Packages/a/) or [non-free](https://download1.rpmfusion.org/nonfree/fedora/releases/38/Everything/x86_64/os/Packages/a/) or some other place will fail to install on top of Universal Blue images.

Packages that failed to install on silverblue-main:38
- VirtualBox (which depends on akmod-VirtualBox)
- akmod-wl
- ndiswrapper (which depends on akmod-ndiswrapper)
I'm pretty sure that legacy akmod-nvidia-390xx and akmod-nvidia-340xx won't install as well

All of them fail with the same error (posted [here](https://github.com/ublue-os/main/issues/85#issuecomment-1479806457) and [here](https://github.com/ublue-os/main/issues/85#issuecomment-1666791683) )

So if users need VirtualBox or have some specific hardware covered by out-of-tree drivers, they have to produce their own UBlue-based images. That's a pretty big limitation comparing to the original Fedora images.

@castrojo , @bsherman 
Do you think the exclusion of the pre-built [drivers/akmods](https://github.com/ublue-os/akmods) from the image can solve this problem?

**Comment by xalt7x** [comment]
Thanks for the explanation. Now I see the bigger picture
Well, to me, this issue kind of breaks the idea of general-purpose operating systems. For now, I'd stick with upstream and wait for "Ostree Native Container". As I didn't have major problems with kmods, I don't feel like the installation of some random driver packages is worth creating full-blown forks.

**Comment by xalt7x** [comment]
Hello @bsherman and @castrojo ,

I'm happy to inform that the new "nokmods" branches don't seem to be affected by this issue and [bazzite issue #229](https://github.com/ublue-os/bazzite/issues/229)

---

Today I've re-tested installation of the proprietary Nvidia driver on non-Nvidia ublue-os images
```
rpm-ostree install akmod-nvidia-470xx xorg-x11-drv-nvidia-470xx
rpm-ostree kargs --append=rd.driver.blacklist=nouveau --append=modprobe.blacklist=nouveau --append=nvidia-drm.modeset=1 initcall_blacklist=simpledrm_platform_driver_init
```
Results:
1. silverblue-main:38 version 38.20230924.0 (2023-09-24T07:15:11Z)  - failed to build akmod
2. silverblue-nokmods:38 version 38.20230924.0 (2023-09-24T07:09:46Z) - Nvidia driver worked after restart

---

Should I open a new issue in the [akmods repo](https://github.com/ublue-os/akmods)?

**Comment by bsherman** [comment]
> Hello @bsherman and @castrojo ,
> 
> I'm happy to inform that the new "nokmods" branches don't seem to be affected by this issue and [bazzite issue #229](https://github.com/ublue-os/bazzite/issues/229)

Wow! That's good to know! And, I apologize for directly answering your question above completely incorrectly; apparently removing all our pre built akmods DID solve this. I truly thought the solution had been attempted and not halped. 

> Should I open a new issue in the [akmods repo](https://github.com/ublue-os/akmods)?

What would the new issue be for?

**Comment by xalt7x** [comment]
> > Should I open a new issue in the [akmods repo](https://github.com/ublue-os/akmods)?
> 
> What would the new issue be for?
Well, original issue was about an old Broadcom driver (for which we already have a [simple workaround](https://github.com/ublue-os/bazzite/issues/229#issuecomment-1728210016). And now we're discussing other, more global one (well, my bad :-) ) . So I thought, maybe it will be a good idea to open a new issue with more appropriate title, description, location etc...

**Comment by bsherman** [comment]
> maybe it will be a good idea to open a new issue with more appropriate title, description, location etc...

You are always welcome to open issues where you think appropriate. :-)
