### ISSUE TITLE
Investigate bootc usage

### ISSUE THREAD

**Issue by castrojo** [ublue-os/main#86]
Tracking issue for: https://github.com/cgwalters/bootc-examples

Add bootc to https://github.com/ublue-os/main for all image builds in base.

**Comment by castrojo** [comment]
Testing this in Bluefin, once the package is in Fedora we'll add it, or maybe we should use the repo from upstream.

**Comment by marcoceppi** [comment]
https://github.com/containers/bootc

**Comment by bsherman** [comment]
There is an issue which prevents its use for me.

If the initramfs gets regenerated by rpm-ostree, then bootc doesn't like it and fails. This is a problem if using TPM or FIDO2 for LUKS unlocking.

**Comment by bobslept** [comment]
> Testing this in Bluefin, once the package is in Fedora we'll add it, or maybe we should use the repo from upstream.

This is currently added to main in PR https://github.com/ublue-os/main/pull/367 to keep track if we change our minds.

**Comment by castrojo** [comment]
> There is an issue which prevents its use for me.

Can you file this upstream? https://github.com/containers/bootc/issues

**Comment by castrojo** [comment]
Also let's leave it along side rpm-ostree for a while, I tried the symlink thing and while that's fine for me bootc can't upgrade layered packages so that's probably a bridge to far for everyone else.

**Comment by castrojo** [comment]
bootc is in all the images, closing.
