### ISSUE TITLE
Incorrect label confuses KDE Discover

### ISSUE THREAD

**Issue by Zoialord** [ublue-os/main#88]
Since the tag changed on the builds to "nightly" I've noticed that Discover (the update app for KDE) always shows an available update from nightly > [date tag]. 

To me looks like a tagging/naming problem, but Jorge said to post an issue so (blame him lol).

https://drive.google.com/file/d/12wL7Ix6rRrLYLeG6iFsAM3xlJIHpwdAS/view?usp=sharing

**Comment by marcoceppi** [comment]
Will put up a branch to address later today

**Comment by castrojo** [comment]
Additional info, in bluefin it does: 

```
 "org.opencontainers.image.version": "main",
```

**Comment by marcoceppi** [comment]
Yeah, I think we need to maintain the version from upstream. The docker/metadata-action is automatically putting `nightly` it's not being explicitly set somewhere. There's no way to skip this label in the metadata-action - so either we read that value from the upstream container and set it explicitly or use something like sed to remove that label once it's set. This will need to be propagated to all the other build jobs that use this - nvidia, bluefin, etc

**Comment by castrojo** [comment]
Let's keep this open until we confirm main and nvidia images.

**Comment by marcoceppi** [comment]
Confirmed resolved
